### PR TITLE
http-api: T4071: allow API to bind to unix domain socket

### PR DESCRIPTION
**Pull request by jestabro**
## Change Summary

Allow API to bind to unix domain socket.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4071

## How to test

```
vyos@vyos# set service https api uds
[edit]
vyos@vyos# commit

vyos@vyos:~$ curl --unix-socket /run/api.sock -X POST -Fkey=qwerty -Fdata='{"op": "showConfig", "path": []}' http://localhost/retrieve
```

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [X] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]

**Review by sever-sever — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
Maybe rename uds to socket?

**Comment by jestabro** [comment]
@c-po yes, that's definitely better

**Comment by sever-sever** [comment]
Set please a correct Task number T4071

**Comment by jestabro** [comment]
Thanks, @sever-sever !

**Pull request merged**
