### PR TITLE
vlan: T2427: fix iteraration of vif

### PR DESCRIPTION
**Pull request by thomas-mangin**

### CODE REVIEW

**Comment by jjakob** [comment]
config['vif'] is a dict, not list. It was changed in #393.

**Comment by jjakob** [comment]
```
ifdict = {
...
    vif: {
        '2': {
            vif 2 config dict
            },
        '100': {
            vif 100 config dict
            }
    },
...
```

**Comment by jjakob** [comment]
https://github.com/vyos/vyos-1x/blob/e3064f763f1976993a616e141dd9ce39165f6fe3/python/vyos/configdict.py#L403

**Comment by jjakob** [comment]
https://github.com/vyos/vyos-1x/pull/393/commits/023b6b772ee6d6853e1c0e585b7f7d207e9926ce

**Comment by thomas-mangin** [comment]
You can iterate the keys of a dict like a list .. I ran "make iso; make test" and smoketest was happy. So if it is not the right fix, I am happy to withdraw the PR and let you provide the right patch :-D

**Comment by thomas-mangin** [comment]
I was trying to provide a fix to:
```
03:42:04  DEBUG - Traceback (most recent call last):
03:42:04  DEBUG -   File "/usr/libexec/vyos/conf_mode/interfaces-wireless.py", line 810, in <module>
03:42:04  DEBUG -     verify(c)
03:42:04  DEBUG -   File "/usr/libexec/vyos/conf_mode/interfaces-wireless.py", line 621, in verify
03:42:04  DEBUG -     verify_vlan_config(wifi)
03:42:04  DEBUG -   File "/usr/lib/python3/dist-packages/vyos/ifconfig_vlan.py", line 155, in verify_vlan_config
03:42:04  DEBUG -     for vif in config['vif'].values():
03:42:04  DEBUG - AttributeError: 'list' object has no attribute 'values'
03:42:04  DEBUG - 
03:42:04  DEBUG - 
03:42:04  DEBUG - 
03:42:04  DEBUG - [[interfaces wireless wlan10]] failed
03:42:04  DEBUG - Commit failed
```

**Comment by jjakob** [comment]
You can iterate the keys, but here you want to iterate the values, because the key is just the VLAN ID, the values are the config dicts where all the config is stored. So the current code is correct. I built the vyos-1x package and tested it with an actual running system with VLANs and the code works fine. I think that's better than a smoketest :)

**Comment by thomas-mangin** [comment]
I have not had the time to fully review your changes, so could you fix this correctly ?

**Comment by jjakob** [comment]
Ah, that's a completely different thing, I forgot to update the other interfaces to use the common VLAN functions. https://github.com/vyos/vyos-1x/pull/393/commits/312cffce31cf3a411a87559bf99f78cde5facd60 https://github.com/vyos/vyos-1x/pull/393/commits/d637a1cd2af0bc6bb2d47b8b661da262892046a2

Will do.

**Pull request closed without merging**
