### PR TITLE
config: T2689: cache the result of get_config_dict

### PR DESCRIPTION
**Pull request by thomas-mangin**
The code otherwise requires JSON parsing and parsing for the key replacement each time.

### CODE REVIEW

**Comment by thomas-mangin** [comment]
while this patch works will all the code, it assumed (as I missed the case) that two following call will have the same path. Change the patch to provide a naive per path caching (could be improved by loading [] and then looking up the path).

The forced push below changed that.

**Comment by jestabro** [comment]
@thomas-mangin this is definitely much needed; two comments:
1) the line 304 will need to use _make_path for path to respect _level, and allow string paths in get_config_dict, which begs the following question
2) do we really want to cache per path? It is rare that the same path will be used more than once, and if running under a daemon, it will mean all paths for all conf_mode scripts will be cached; honestly asking, as I'm not sure gains vs overhead

**Comment by jestabro** [comment]
Also, since we will cache the global dicts anyway, we should allow setting key_mangling globally --- I'm setting that up (cache would have unmangled and mangled, so one could re-mangle if needed); that avoids another need of caching by path.

--- likely a huge bottleneck to apply globally; strike that

**Comment by thomas-mangin** [comment]
@jestabro I agree we should have a global dict cache and seek into it. Thanks for pointing the _make_path issue. I believe this would be worth implementing as it makes calling the function free'ish in term of CPU.

**Comment by jestabro** [comment]
Committed the modified version discussed with @thomas-mangin .

**Pull request closed without merging**
