### PR TITLE
op-mode: ip: T3283: Support for IPv4/IPv6 neigh tables

### PR DESCRIPTION
**Pull request by jack9603301**
## Change Summary

op-mode: ip: T3283: Support for IPv4/IPv6 neigh tables

## Types of changes

 
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://phabricator.vyos.net/T3283

## Component(s) name

ip,ipv6

## Proposed changes

- Support for IPv4 neigh tables
- Reformat the IPv6 Neigh tables with a script

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
What is the advantage over `show arp`?

**Comment by jack9603301** [comment]
@c-po This will actually output the neigh table

```
vyos@vyos:~$ ip -f inet neigh list 
192.168.0.47 dev br1  FAILED
192.168.0.57 dev br1  FAILED
192.168.0.186 dev br1  FAILED
192.168.0.196 dev br1  FAILED
192.168.0.198 dev br1  FAILED
192.168.0.200 dev br1  FAILED
192.168.0.87 dev br1  FAILED
192.168.101.210 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.208 dev br1  FAILED
192.168.0.81 dev br1  FAILED
192.168.101.208 dev br1.2  FAILED
192.168.101.214 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.212 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.218 dev br1.2 lladdr 6c:c2:17:ea:83:48 REACHABLE
192.168.101.216 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.101 dev br1  FAILED
192.168.0.103 dev br1  FAILED
192.168.101.198 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.196 dev br1.2 lladdr 72:af:f5:b0:d5:fa STALE
192.168.0.111 dev br1  FAILED
192.168.101.202 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.232 dev br1  FAILED
192.168.101.200 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.107 dev br1  FAILED
192.168.101.206 dev br1.2  FAILED
192.168.0.244 dev br1  FAILED
192.168.101.204 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.113 dev br1  FAILED
192.168.101.246 dev br1.2  FAILED
192.168.0.254 dev br1 lladdr b8:27:eb:88:f3:7a REACHABLE
192.168.0.123 dev br1  FAILED
192.168.0.133 dev br1  FAILED
192.168.0.4 dev br1 lladdr 32:2a:41:6e:0f:47 REACHABLE
192.168.0.6 dev br1 lladdr 46:cc:90:80:c4:c9 STALE
192.168.0.2 dev br1  FAILED
192.168.101.228 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.8 dev br1  FAILED
192.168.0.10 dev br1 lladdr 3a:d4:30:8a:f7:00 STALE
192.168.101.236 dev br1.2 lladdr 8c:53:c3:a8:8e:b0 DELAY
192.168.0.32 dev br1  FAILED
192.168.0.54 dev br1  FAILED
192.168.101.181 dev br1.2 lladdr d8:9b:3b:d5:88:22 REACHABLE
192.168.101.185 dev br1.2 lladdr 34:46:ec:76:f8:9b REACHABLE
192.168.0.58 dev br1  FAILED
192.168.101.191 dev br1.2 lladdr 7a:4c:0b:82:1c:b9 STALE
192.168.0.199 dev br1  FAILED
192.168.0.70 dev br1  FAILED
192.168.0.195 dev br1  FAILED
192.168.101.211 dev br1.2  FAILED
192.168.0.211 dev br1  FAILED
192.168.0.82 dev br1  FAILED
192.168.101.209 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.215 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.213 dev br1.2  FAILED
192.168.0.90 dev br1  FAILED
192.168.101.217 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.100 dev br1  FAILED
192.168.0.102 dev br1  FAILED
192.168.0.98 dev br1  FAILED
192.168.101.199 dev br1.2  FAILED
192.168.0.110 dev br1  FAILED
192.168.101.197 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.104 dev br1  FAILED
192.168.101.203 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.201 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.207 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.118 dev br1  FAILED
192.168.101.205 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.112 dev br1  FAILED
192.168.101.243 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.101.245 dev br1.2 lladdr 50:01:d9:8c:8e:8e STALE
192.168.0.122 dev br1  FAILED
192.168.0.5 dev br1 lladdr ca:c2:a4:51:e5:3b STALE
192.168.0.7 dev br1  FAILED
192.168.101.227 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.3 dev br1 lladdr 90:b1:1c:0d:7e:8f REACHABLE
192.168.101.225 dev br1.2 lladdr c2:cb:fa:bf:a0:35 STALE
192.168.0.15 dev br1  FAILED
192.168.0.9 dev br1  FAILED
192.168.101.235 dev br1.2 lladdr 6c:c2:17:ea:83:48 STALE
192.168.0.21 dev br1  FAILED
192.168.0.150 dev br1  FAILED
192.168.101.237 dev br1.2  FAILED
192.168.0.19 dev br1  FAILED
192.168.0.25 dev br1  FAILED

```

**Comment by c-po** [comment]
Could the output please be reformatted to have a proper aligned table like:

```
192.168.0.47      br1    FAILED                        
192.168.0.57      br1    FAILED                     
192.168.0.186     br1    FAILED                     
192.168.0.196     br1    FAILED                     
192.168.0.198     br1    FAILED                     
192.168.0.200     br1    FAILED                     
192.168.0.87      br1    FAILED                     
192.168.101.210   br1.2  STALE     6c:c2:17:ea:83:48
192.168.0.208     br1    FAILED                     
192.168.0.81      br1    FAILED                     
192.168.101.208   br1.2  FAILED                     
192.168.101.214   br1.2  STALE     6c:c2:17:ea:83:48
192.168.101.212   br1.2  STALE     6c:c2:17:ea:83:48
192.168.101.218   br1.2  REACHABLE 6c:c2:17:ea:83:48
192.168.101.216   br1.2  STALE     6c:c2:17:ea:83:48
192.168.0.101     br1    FAILED                     
```

**Comment by jack9603301** [comment]
@c-po Maybe I can reformat it. I'll look at that

**Comment by jack9603301** [comment]
note:

```
# ip -j -f inet neigh list | jq
[
  {
    "dst": "192.168.101.8",
    "dev": "enp0s25",
    "lladdr": "78:d2:94:72:77:7e",
    "state": [
      "STALE"
    ]
  },
  {
    "dst": "192.168.101.185",
    "dev": "enp0s25",
    "lladdr": "34:46:ec:76:f8:9b",
    "state": [
      "STALE"
    ]
  },
  {
    "dst": "192.168.101.225",
    "dev": "enp0s25",
    "lladdr": "c2:cb:fa:bf:a0:35",
    "state": [
      "STALE"
    ]
  },
  {
    "dst": "192.168.101.1",
    "dev": "enp0s25",
    "lladdr": "00:98:2b:f8:3f:11",
    "state": [
      "REACHABLE"
    ]
  },
  {
    "dst": "192.168.101.181",
    "dev": "enp0s25",
    "lladdr": "d8:9b:3b:d5:88:22",
    "state": [
      "STALE"
    ]
  }
]
```

**Comment by c-po** [comment]
Throw it into Jinja2 and you are all set. There are other op-mode commands which also use Jinja2 templates.

**Comment by jack9603301** [comment]
@c-po Can you give me the location of the code that uses Jinja2's operation mode? I have a look

**Comment by jack9603301** [comment]
done

**Comment by jack9603301** [comment]
> What is the advantage over `show arp`?

In contrast to this command, it shows all the states of physical interfaces to IP addresses, such as FAILED, STALE, or REACHABLE, while the `arp` command does not print this state very well and will correspond well to similar commands in IPv6

**Comment by jack9603301** [comment]
@c-po  done
```
vyos@vyos:~$ ./test.py --family inet
IP Address                                         Device     State                LLADDR
----------                                         ------     -----                ------
192.168.0.47                                       br1        failed               
192.168.0.57                                       br1        failed               
192.168.0.186                                      br1        failed               
192.168.0.196                                      br1        failed               
192.168.0.198                                      br1        failed               
192.168.0.200                                      br1        failed               
192.168.0.87                                       br1        failed               
192.168.101.210                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.208                                      br1        failed               
192.168.0.81                                       br1        failed               
192.168.101.208                                    br1.2      failed               
192.168.101.214                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.212                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.218                                    br1.2      delay                6c:c2:17:ea:83:48
192.168.101.216                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.101                                      br1        failed               
192.168.0.103                                      br1        failed               
192.168.101.198                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.196                                    br1.2      stale                72:af:f5:b0:d5:fa
192.168.0.111                                      br1        failed               
192.168.101.202                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.232                                      br1        failed               
192.168.101.200                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.107                                      br1        failed               
192.168.101.206                                    br1.2      failed               
192.168.0.244                                      br1        failed               
192.168.101.204                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.113                                      br1        failed               
192.168.101.246                                    br1.2      failed               
192.168.0.254                                      br1        reachable            b8:27:eb:88:f3:7a
192.168.0.123                                      br1        failed               
192.168.0.133                                      br1        failed               
192.168.0.4                                        br1        delay                32:2a:41:6e:0f:47
192.168.0.6                                        br1        stale                46:cc:90:80:c4:c9
192.168.0.2                                        br1        failed               
192.168.101.228                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.8                                        br1        failed               
192.168.0.10                                       br1        stale                3a:d4:30:8a:f7:00
192.168.101.236                                    br1.2      reachable            8c:53:c3:a8:8e:b0
192.168.0.32                                       br1        failed               
192.168.0.54                                       br1        failed               
192.168.101.181                                    br1.2      reachable            d8:9b:3b:d5:88:22
192.168.101.185                                    br1.2      failed               
192.168.0.58                                       br1        failed               
192.168.101.191                                    br1.2      stale                7a:4c:0b:82:1c:b9
192.168.0.199                                      br1        failed               
192.168.0.70                                       br1        failed               
192.168.0.195                                      br1        failed               
192.168.101.211                                    br1.2      failed               
192.168.0.211                                      br1        failed               
192.168.0.82                                       br1        failed               
192.168.101.209                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.215                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.213                                    br1.2      failed               
192.168.0.90                                       br1        failed               
192.168.101.217                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.100                                      br1        failed               
192.168.0.102                                      br1        failed               
192.168.0.98                                       br1        failed               
192.168.101.199                                    br1.2      failed               
192.168.0.110                                      br1        failed               
192.168.101.197                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.104                                      br1        failed               
192.168.101.203                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.201                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.207                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.118                                      br1        failed               
192.168.101.205                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.112                                      br1        failed               
192.168.101.243                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.101.245                                    br1.2      stale                50:01:d9:8c:8e:8e
192.168.0.122                                      br1        failed               
192.168.0.5                                        br1        stale                ca:c2:a4:51:e5:3b
192.168.0.7                                        br1        failed               
192.168.101.227                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.3                                        br1        stale                90:b1:1c:0d:7e:8f
192.168.101.225                                    br1.2      stale                c2:cb:fa:bf:a0:35
192.168.0.15                                       br1        failed               
192.168.0.9                                        br1        failed               
192.168.101.235                                    br1.2      stale                6c:c2:17:ea:83:48
192.168.0.21                                       br1        failed               
192.168.0.150                                      br1        failed               
192.168.101.237                                    br1.2      failed               
192.168.0.19                                       br1        failed               
192.168.0.25                                       br1        failed               
vyos@vyos:~$ ./test.py --family inet6
IP Address                                         Device     State                LLADDR
----------                                         ------     -----                ------
fe80::c0cb:faff:febf:a035                          br1.2      stale                c2:cb:fa:bf:a0:35
fc00:470:f1cd:101:10b2:8535:7177:f052              br1.2      stale                8c:53:c3:a8:8e:b0
fc00:470:f1cd:101:23cc:3e18:871c:6c29              br1.2      failed               
fc00:470:f1cd:101:2f11:2527:42d2:5922              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e89:8171:810c:d9d5:45f5:be2c             br1.2      failed               
fc00:470:f1cd:101:a4b5:5d43:a0bf:d509              br1.2      stale                d8:9b:3b:d5:88:22
240e:3b3:4e85:20d1:a9cc:7de2:bc2b:2d1f             br1.2      stale                d8:9b:3b:d5:88:22
fc00:470:f1cd:101:b31f:46c7:b0bf:66d7              br1.2      stale                6c:c2:17:ea:83:48
fe80::accc:4cff:febb:72a3                          br1        stale                32:2a:41:6e:0f:47
fc00:470:f1cd:101:e8ed:4856:9de2:4ed0              br1.2      stale                34:46:ec:76:f8:9b
240e:3b3:4e89:8171:23fe:de5a:5794:37fc             br1.2      failed               
240e:3b3:4e86:9801:3846:d38d:963c:b027             br1.2      stale                6c:c2:17:ea:83:48
fe80::44cc:90ff:fe80:c4c9                          br1        stale                46:cc:90:80:c4:c9
fe80::c8c2:a4ff:fe51:e53b                          br1        stale                ca:c2:a4:51:e5:3b
240e:3b3:4e89:8171:a4b5:5d43:a0bf:d509             br1.2      failed               
240e:3b3:4e85:20d1:389b:2ab2:3708:ef1d             br1.2      stale                8c:53:c3:a8:8e:b0
240e:3b3:4e89:8171:e8ed:4856:9de2:4ed0             br1.2      failed               
fc00:470:f1cd:101:82e7:8e89:6030:9361              br1.2      failed               
fc00:470:f1cd:101:9f1f:ec80:6e3c:490a              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e8c:3aa1:a36a:ea3f:3125:734d             br1.2      failed               
fc00:470:f1cd::4                                   br1        delay                32:2a:41:6e:0f:47
fe80::b4ce:bbff:fef6:c193                          br1        stale                32:2a:41:6e:0f:47
fe80::ba27:ebff:fe88:f37a                          br1        reachable            b8:27:eb:88:f3:7a
240e:3b3:4e89:8172:ba27:ebff:fe88:f37a             br1        stale                b8:27:eb:88:f3:7a
240e:3b3:4e8c:3aa1:81e0:67b:29c6:a619              br1.2      stale                50:01:d9:8c:8e:8e
240e:3b3:4e86:9801:3f88:b9aa:f8fa:f44e             br1.2      stale                6c:c2:17:ea:83:48
fe80::70af:f5ff:feb0:d5fa                          br1.2      stale                72:af:f5:b0:d5:fa
fc00:470:f1cd:101:aca1:fb90:4db4:4f5e              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e85:20d1:dc62:40e5:2655:3249             br1.2      failed               
fe80::a8f1:4b42:3848:4d93                          br1.2      stale                34:46:ec:76:f8:9b
fe80::38d4:30ff:fe8a:f700                          br1        stale                3a:d4:30:8a:f7:00
240e:3b3:4e85:20d1:c0cb:faff:febf:a035             br1.2      stale                c2:cb:fa:bf:a0:35
240e:3b3:4e85:20d1:ea18:b15f:d913:c0e7             br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e89:8171:5c88:d56e:85b:186e              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e8c:3aa1:8d12:381c:ee51:e6cb             br1.2      reachable            d8:9b:3b:d5:88:22
fe80::302a:41ff:fe6e:f47                           br1        stale                32:2a:41:6e:0f:47
240e:3b3:4e8c:3aa1:6813:9a31:7d:b2eb               br1.2      failed               
fc00:470:f1cd:101:142a:8152:6ef9:999d              br1.2      stale                6c:c2:17:ea:83:48
fc00:470:f1cd:101:54be:a98b:e21c:5c20              br1.2      stale                8c:53:c3:a8:8e:b0
fc00:470:f1cd:101:10b6:b97f:68a4:f24               br1.2      stale                6c:c2:17:ea:83:48
fe80::5201:d9ff:fe8c:8e8e                          br1.2      stale                50:01:d9:8c:8e:8e
fc00:470:f1cd:101:638a:a04e:eb94:ad74              br1.2      stale                6c:c2:17:ea:83:48
fc00:470:f1cd:101:505:37af:5672:ed95               br1.2      stale                50:01:d9:8c:8e:8e
240e:3b3:4e8c:3aa1:92b1:1cff:fe0d:7e8f             br1.2      stale                90:b1:1c:0d:7e:8f
fc00:470:f1cd:101:5d96:d518:8707:2ea9              br1.2      failed               
240e:3b3:4e86:9801:65ff:4266:c7f3:9875             br1.2      failed               
240e:3b3:4e85:20d2:ba27:ebff:fe88:f37a             br1        stale                b8:27:eb:88:f3:7a
240e:3b3:4e8c:3aa1:70e2:a902:fa9e:349a             br1.2      stale                6c:c2:17:ea:83:48
fc00:470:f1cd:0:ba27:ebff:fe88:f37a                br1        reachable            b8:27:eb:88:f3:7a
240e:3b3:4e89:8171:cc4e:adf6:dbd8:e568             br1.2      stale                6c:c2:17:ea:83:48
fc00:470:f1cd:101:598c:b54c:fb30:a8d9              br1.2      stale                6c:c2:17:ea:83:48
fe80::3043:80ff:fee0:f1b4                          br1.2      stale                00:98:2b:f8:3f:11
240e:3b3:4e86:9801:92b1:1cff:fe0d:7e8f             br1.2      stale                90:b1:1c:0d:7e:8f
fe80::d0a6:4ab8:eee8:12e2                          br1.2      reachable            d8:9b:3b:d5:88:22
fc00:470:f1cd:101:5b4d:1cc1:1601:6551              br1.2      reachable            6c:c2:17:ea:83:48
fc00:470:f1cd:101:e0ec:e6e1:e65f:cbbf              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e8c:3aa1:5994:af5f:7994:5b93             br1.2      stale                8c:53:c3:a8:8e:b0
240e:3b3:4e89:8171:7011:7687:4aaf:c74              br1.2      failed               
fe80::3646:ecff:fe76:f89b                          br1.2      stale                34:46:ec:76:f8:9b
fc00:470:f1cd:101:81e0:67b:29c6:a619               br1.2      failed               
fc00:470:f1cd:101:b106:ab94:bb3f:33d               br1.2      failed               
fc00:470:f1cd:101:7aba:c56d:501e:54a9              br1.2      failed               
240e:3b3:4e8c:3aa1:50c5:2306:bc0f:f04b             br1.2      reachable            6c:c2:17:ea:83:48
fc00:470:f1cd:101:65ff:4266:c7f3:9875              br1.2      failed               
fe80::f737:d8f7:1caa:f6b0                          br1.2      stale                50:01:d9:8c:8e:8e
240e:3b3:4e89:8171:81e0:67b:29c6:a619              br1.2      stale                50:01:d9:8c:8e:8e
240e:3b3:4e85:20d1:54be:a98b:e21c:5c20             br1.2      stale                8c:53:c3:a8:8e:b0
240e:3b3:4e89:8171:7492:9ecc:958d:f487             br1.2      stale                6c:c2:17:ea:83:48
fe80::92b1:1cff:fe0d:7e8f                          br1.2      stale                90:b1:1c:0d:7e:8f
fc00:470:f1cd:101:8d12:381c:ee51:e6cb              br1.2      stale                d8:9b:3b:d5:88:22
240e:3b3:4e86:9801:4458:c6ef:8a3a:dd1              br1.2      failed               
240e:3b3:4e85:20d1:505:37af:5672:ed95              br1.2      failed               
fc00:470:f1cd:101:6813:9a31:7d:b2eb                br1.2      stale                d8:9b:3b:d5:88:22
240e:3b3:4e89:8171:eb7f:2e4f:52d1:cdbb             br1.2      stale                d8:9b:3b:d5:88:22
240e:3b3:4e89:8171:c743:7046:e99b:f323             br1.2      failed               
fc00:470:f1cd:101:5472:5f50:2ba2:d281              br1.2      failed               
fc00:470:f1cd:101:910e:3a8d:f212:871e              br1.2      stale                8c:53:c3:a8:8e:b0
240e:3b3:4e86:9801:a9cc:7de2:bc2b:2d1f             br1.2      stale                d8:9b:3b:d5:88:22
fc00:470:f1cd:101:35b6:d82b:6057:239               br1.2      failed               
240e:3b3:4e86:9801:cc0d:ac20:26d6:5ddc             br1.2      stale                50:01:d9:8c:8e:8e
240e:3b3:4e86:9801:7f76:e33:38e2:9c2e              br1.2      failed               
240e:3b3:4e86:9801:6bc4:3e31:a181:77a              br1.2      failed               
240e:3b3:4e89:8171:92b1:1cff:fe0d:7e8f             br1.2      stale                90:b1:1c:0d:7e:8f
fc00:470:f1cd:101:f6ba:19ff:6578:b320              br1.2      failed               
240e:3b3:4e89:8171:910e:3a8d:f212:871e             br1.2      failed               
240e:3b3:4e89:8171:35b6:d82b:6057:239              br1.2      stale                8c:53:c3:a8:8e:b0
240e:3b3:4e86:9801:389b:2ab2:3708:ef1d             br1.2      stale                8c:53:c3:a8:8e:b0
fe80::784c:bff:fe82:1cb9                           br1.2      stale                7a:4c:0b:82:1c:b9
fc00:470:f1cd:101:5994:af5f:7994:5b93              br1.2      reachable            8c:53:c3:a8:8e:b0
fc00:470:f1cd:101:f6b3:b0d9:d373:3822              br1.2      failed               
240e:3b3:4e85:20d1:e5f0:ea13:d8a5:8167             br1.2      failed               
fe80::5a33:2c9:b167:3f3c                           br1.2      stale                6c:c2:17:ea:83:48
fe80::e8b4:91ff:fe67:329b                          br1        stale                32:2a:41:6e:0f:47
fc00:470:f1cd::5                                   br1        stale                ca:c2:a4:51:e5:3b
240e:3b3:4e85:20d1:65ff:4266:c7f3:9875             br1.2      stale                34:46:ec:76:f8:9b
240e:3b3:4e89:8171:5994:af5f:7994:5b93             br1.2      stale                8c:53:c3:a8:8e:b0
fe80::3043:80ff:fee0:f1b4                          br1        stale                00:98:2b:f8:3f:11
240e:3b3:4e85:20d1:9959:f956:6a13:744f             br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e8c:3aa1:e8ed:4856:9de2:4ed0             br1.2      failed               
fc00:470:f1cd:101:a9cc:7de2:bc2b:2d1f              br1.2      stale                d8:9b:3b:d5:88:22
240e:3b3:4e86:9801:10b2:8535:7177:f052             br1.2      stale                8c:53:c3:a8:8e:b0
fc00:470:f1cd:101:cc0d:ac20:26d6:5ddc              br1.2      stale                50:01:d9:8c:8e:8e
fc00:470:f1cd:101:6944:376e:e1ba:3cbd              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e89:8171:b028:3adf:8fb:83a6              br1.2      failed               
240e:3b3:4e85:20d1:92b1:1cff:fe0d:7e8f             br1.2      stale                90:b1:1c:0d:7e:8f
fc00:470:f1cd:101:9056:5024:969b:1ceb              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e8c:3aa2:ba27:ebff:fe88:f37a             br1        stale                b8:27:eb:88:f3:7a
240e:3b3:4e8c:3aa1:e695:c6d7:986c:c02c             br1.2      failed               
240e:3b3:4e86:9801:ed9f:b15:6bbb:ff2c              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e89:8171:c323:c4:a5e7:1876               br1.2      failed               
240e:3b3:4e89:8171:a9cc:7de2:bc2b:2d1f             br1.2      failed               
fc00:470:f1cd:101:389b:2ab2:3708:ef1d              br1.2      failed               
240e:3b3:4e86:9801:e8ed:4856:9de2:4ed0             br1.2      failed               
240e:3b3:4e89:8171:cc0d:ac20:26d6:5ddc             br1.2      stale                50:01:d9:8c:8e:8e
fe80::3510:82eb:8d6d:6922                          br1.2      reachable            8c:53:c3:a8:8e:b0
fe80::1                                            eth5       stale                40:f4:20:98:d1:79
fc00:470:f1cd::ff00                                br1        reachable            b8:27:eb:88:f3:7a
fc00:470:f1cd:101:99ea:26e4:fe6d:e747              br1.2      stale                6c:c2:17:ea:83:48
240e:3b3:4e86:9802:ba27:ebff:fe88:f37a             br1        stale                b8:27:eb:88:f3:7a
```

**Pull request merged**
