### PR TITLE
dhcp: T3316: Adjust dhcp-run script to align with kea hooks

### PR DESCRIPTION
**Pull request by indrajitr**
## Change Summary

The hook arguments passed to `on-dhcp-event.sh` have changed in Kea.
Adjust the script to align with the new arguments.

Additionally, remove FQDN mangling from the script. No need to extract
the domain name from `LEASE4_HOSTNAME` only to append it again.

See: https://kea.readthedocs.io/en/latest/arm/hooks.html#hooks-run-script

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T3316

## Component(s) name

dhcp-server

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by sarthurdev — APPROVED** [review]

**Comment by indrajitr** [comment]
This adds entries to `/etc/hosts` file, which is good. But the format isn't what we'd expect. The entries look like so in `/etc/hosts`.

```
# From 'system static-host-mapping' and DHCP server
# dhcp-server-10.144.40.8
10.144.40.8     host-3.host-3 
# dhcp-server-10.144.40.2
10.144.40.2     host-2.host-2
```
@sarthurdev should we wait a bit to investigate the FQDN part?

**Comment by indrajitr** [comment]
_Update:_ the script doesn't duplicate the hostname anymore. 
```
# From 'system static-host-mapping' and DHCP server
# dhcp-server-10.144.42.18
10.144.42.18     host-54 
# dhcp-server-10.144.42.12
10.144.42.12     host-23
```
This can go in as-is for now. FQDN handling has to be taken up separately.

**Review by c-po — APPROVED** [review]

**Comment by 24fpsDaVinci** [comment]
getting a kea failure no start error with latest build
https://github.com/vyos/vyos-rolling-nightly-builds/releases/tag/1.5-rolling-202312171632

same as zen3515 comment in https://vyos.dev/T3316

**Comment by indrajitr** [comment]
@24fpsDaVinci, it could be due to a variety of reasons.
Would you please consider sharing the details in https://vyos.dev/T3316?

**Comment by 24fpsDaVinci** [comment]
> @24fpsDaVinci, it could be due to a variety of reasons. Would you please consider sharing the details in https://vyos.dev/T3316?

will do, waiting on mods to approve my account

**Comment by 24fpsDaVinci** [comment]
```
vyos@vyos:~$ systemctl list-units --failed
  UNIT                     LOAD   ACTIVE SUB    DESCRIPTION         
● kea-dhcp4-server.service loaded failed failed Kea IPv4 DHCP daemon
```

```
vyos@vyos:~$ journalctl -u kea-dhcp4-server.service -b
Dec 17 18:14:04 vyos systemd[1]: Started kea-dhcp4-server.service - Kea IPv4 DHCP daemon.
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.076 INFO  [kea-dhcp4.dhcp4/2734.140502928017856] DHCP4_STARTING Kea DHCPv4 server version 2.2.0 (stable) starting
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.076 INFO  [kea-dhcp4.hosts/2734.140502928017856] HOSTS_BACKENDS_REGISTERED the following host backend types are available: mysql postgresql
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.077 INFO  [kea-dhcp4.dhcpsrv/2734.140502928017856] DHCPSRV_CFGMGR_SOCKET_TYPE_SELECT using socket type raw
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.087 INFO  [kea-dhcp4.hooks/2734.140502928017856] HOOKS_LIBRARY_CLOSED hooks library /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_run_script.so successfully closed
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.111 INFO  [kea-dhcp4.hooks/2734.140502928017856] HOOKS_LIBRARY_CLOSED hooks library /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_lease_cmds.so successfully closed
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.111 INFO  [kea-dhcp4.dhcpsrv/2734.140502928017856] DHCPSRV_CFGMGR_NEW_SUBNET4 a new subnet has been added to configuration: 192.168.1.0/24 with params: valid-lifetime=86400
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.111 INFO  [kea-dhcp4.commands/2734.140502928017856] COMMAND_ACCEPTOR_START Starting to accept connections via unix domain socket bound to /run/kea/dhcp4-ctrl-socket
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.117 INFO  [kea-dhcp4.run-script-hooks/2734.140502928017856] RUN_SCRIPT_LOAD Run Script hooks library has been loaded
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.117 INFO  [kea-dhcp4.hooks/2734.140502928017856] HOOKS_LIBRARY_LOADED hooks library /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_run_script.so successfully loaded
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.lease-cmds-hooks/2734.140502928017856] LEASE_CMDS_INIT_OK loading Lease Commands hooks library successful
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.hooks/2734.140502928017856] HOOKS_LIBRARY_LOADED hooks library /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_lease_cmds.so successfully loaded
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.dhcp4/2734.140502928017856] DHCP4_CONFIG_COMPLETE DHCPv4 server has completed configuration: added IPv4 subnets: 1; DDNS: disabled
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.dhcpsrv/2734.140502928017856] DHCPSRV_MEMFILE_DB opening memory file lease database: name=/config/dhcp4.leases persist=true type=memfile universe=4
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.dhcpsrv/2734.140502928017856] DHCPSRV_MEMFILE_LEASE_FILE_LOAD loading leases from file /config/dhcp4.leases
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 ERROR [kea-dhcp4.dhcp4/2734.140502928017856] DHCP4_CONFIG_LOAD_FAIL configuration error using file: /run/kea/kea-dhcp4.conf, reason: Unable to open database: unable to open '/config/dhcp4.leases'
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 ERROR [kea-dhcp4.dhcp4/2734.140502928017856] DHCP4_INIT_FAIL failed to initialize Kea server: configuration error using file '/run/kea/kea-dhcp4.conf': Unable to open database: unable to open '/config/dhcp4.leases'
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.lease-cmds-hooks/2734.140502928017856] LEASE_CMDS_DEINIT_OK unloading Lease Commands hooks library successful
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.run-script-hooks/2734.140502928017856] RUN_SCRIPT_UNLOAD Run Script hooks library has been unloaded
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.hooks/2734.140502928017856] HOOKS_LIBRARY_CLOSED hooks library /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_lease_cmds.so successfully closed
Dec 17 18:14:05 vyos kea-dhcp4[2734]: 2023-12-17 18:14:05.118 INFO  [kea-dhcp4.hooks/2734.140502928017856] HOOKS_LIBRARY_CLOSED hooks library /usr/lib/x86_64-linux-gnu/kea/hooks/libdhcp_run_script.so successfully closed
Dec 17 18:14:05 vyos systemd[1]: kea-dhcp4-server.service: Main process exited, code=exited, status=1/FAILURE
Dec 17 18:14:05 vyos systemd[1]: kea-dhcp4-server.service: Failed with result 'exit-code'.
```
the build i'm migrating from is 1.5-rolling-202312101419:
```
1.5-rolling-202312101419
vyos@vyos:/config$ ls -l | grep dhcp4
-rwxr-xr-x 1 _kea vyattacfg 38301 Dec 17 18:26 dhcp4.leases
```
looks like in 1.5-rolling-202312171632 the owner changed to root
```
1.5-rolling-202312171632
vyos@vyos:/config$ ls -l | grep dhcp4
-rwxr-xr-x 1 root vyattacfg 38223 Dec 17 17:58 dhcp4.leases

```

**Pull request merged**
