### PR TITLE
policy: T3673: Add set large-comm-list for route-map

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add a "set large-comm-list" feature.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3673

## Component(s) name

policy, community, bgp
## How to test
VyOS configuration
```
set policy large-community-list LA rule 10 action 'permit'
set policy large-community-list LA rule 10 regex '10:30:5'
set policy route-map FOO rule 10 action permit 
set policy route-map FOO rule 10 set large-comm-list-delete LA

```
Frr:
```
!
bgp large-community-list expanded LA seq 10 permit 10:30:5
!
route-map FOO permit 10
 set large-comm-list LA delete
!

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — COMMENTED** [review]
Can we probably make this a tag node which only supports one instance (using `verify()`?):

```
set policy route-map FOO rule 20 action 'permit'
set policy route-map FOO rule 20 set large-comm-list FOOO delete
```

Or is this already available in VyOS 1.2 and 1.3?

**Comment by sever-sever** [comment]
> Can we probably make this a tag node which only supports one instance (using `verify()`?):
> 
> ```
> set policy route-map FOO rule 20 action 'permit'
> set policy route-map FOO rule 20 set large-comm-list FOOO delete
> ```
> 
> Or is this already available in VyOS 1.2 and 1.3?

It is a new feature. I don't find it in 1.2/1.3
The syntax the same as existing in "comm-list"
For example how it present in comm-list
```
set policy route-map FOO rule 10 set comm-list comm-list FOO
set policy route-map FOO rule 10 set comm-list delete 
```
So we can change it as we want :).

**Comment by c-po** [comment]
I would appreciate that change. I know there are other communities available which also use your first style of implementation but we can and should migrate them.

Can you please adjust this PR?

**Comment by sever-sever** [comment]
This feature works only with "delete"
```
route-map FOO permit 20
 set large-comm-list FOO delete


r4-1.3(config)# route-map FOO permit 20
r4-1.3(config-route-map)#  set large-comm-list FOO
% Command incomplete:  set large-comm-list FOO

```

**Comment by c-po** [comment]
FRR help text states: `large-comm-list` `set BGP large community list (for deletion)`.

@sever-sever can we use the following VyOS syntax: `set policy route-map FOO rule 20 set large-comm-list-delete FOO`? That saves us from a `tagNode` and is still almost in line with the FRR syntax?

**Comment by sever-sever** [comment]
> @sever-sever can we use the following VyOS syntax: `set policy route-map FOO rule 20 set large-comm-list-delete FOO`?

Done
```
set policy route-map FOO rule 10 action permit 
set policy route-map FOO rule 10 set large-comm-list-delete LA
```

**Pull request merged**
