### PR TITLE
conf-mode: T2103: Delete value help match en[ospx]N for eth interfaces

### PR DESCRIPTION
**Pull request by sever-sever**
Delete valueHelp "en[ospx]N" for ethernet interfaces

### CODE REVIEW

**Comment by c-po** [comment]
I agree and somehow disagre. eno,enp,ens is the new Interface naming standard for persistant ethernet interfaces by all major linux distributions. Once running on RPI is finalized we also should adopt this new scheme to get more experience.

Here you only drop the valueHelp, but not the regex for validation, thus this PR is definately incomplete.

**Comment by jack9603301** [comment]
I agree with @c-po suggestion that unless a new naming standard similar to Cisco devices is accepted by the community, we should keep pace with the latest standard interface nomenclature of Linux. We should not delete the naming of these interfaces or delete valueHelp

When we delete the naming method of the old interface, we should have the ValueHelp explanation of its naming structure. If we delete ValueHelp, then the regular expression should be deleted, otherwise it will be incomplete. This PR should be improved

https://github.com/vyos/vyos-1x/blob/749b011c2dc90650e6304c5c2deb19268ffbd89f/interface-definitions/interfaces-ethernet.xml.in#L10

@c-po In addition, I still don't understand why the regular expressions named for the interface have expressions similar to lanN? Is this linux expression? I don't seem to have seen

**Comment by sever-sever** [comment]
> Here you only drop the valueHelp, but not the regex for validation, thus this PR is definately incomplete.

Main reason it (cosmetic) hide it from menu for everyone, but user can use it if in some reason names of interfaces don’t detect correctly. If it can’t validate than users can’t to use that’s names.
So if we don’t need it in validations I can exclude it from validators.

**Comment by c-po** [comment]
I would not change that logic as I see no reason. So when building for arm64 we should use the new names, maybe somone wan't to work on migrating from eth* to predictable interface names (ens, eno, enp) so then we would definately need it.

@jack9603301 lan is a special name for e.g. lanner appliances which come with lan0 or wan0 ports ...

Taking into account of all the trouble we had with interfaces randomly renaming itself I really would like to see the persistant interfaces someday in VyOS like eno, enp, ens

**Review by dmbaturin — APPROVED** [review]
If we never use the (IMHO, nonsensical) `en[ospx]` naming, then we indeed don't need to suggest it in completeion. But, how did it came to be in the first place? Are there cases when the "predictable" naming rears its ugly head?

**Comment by c-po** [comment]
Lets drop it until we definately need it. It was added during the buster migration.

**Pull request merged**
