### PR TITLE
nat66: T2518: Modify the command line description of NAT/NAT66

### PR DESCRIPTION
**Pull request by jack9603301**
## Change Summary

Modify the command line description of NAT/NAT66

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T2518

## Component(s) name

nat66,nat

## Proposed changes

Modify the command line description of NAT/NAT66

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I see no change in error handling in this commit, so the commit message is missleading.

**Comment by jack9603301** [comment]
> I see no change in error handling in this commit, so the commit message is missleading.

done

**Comment by c-po** [comment]
The documentations commit guidelines states the format of the commit headline. Please follow the length limitation. `nat66: T2518: Modify the command line description of NAT/NAT66 to distinguish NAT from nat66` is 92 characters.

It should not exceed 72 characters for easier readability on UNIX consoles.

**Comment by jack9603301** [comment]
> The documentations commit guidelines states the format of the commit headline. Please follow the length limitation. `nat66: T2518: Modify the command line description of NAT/NAT66 to distinguish NAT from nat66` is 92 characters.
> 
> It should not exceed 72 characters for easier readability on UNIX consoles.

done

**Pull request merged**
