### PR TITLE
remote: T5773: Fix for broken config download

### PR DESCRIPTION
**Pull request by erkin**
## Change Summary

Fix for a regression that broke conf-mode `load` (and probably a few other calls to `download()` and `upload()`).

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5773
* https://vyos.dev/T5774

## Component(s) name

remote, conf-mode

## Proposed changes

The original behaviour for failed transfer operations was printing out the error (after clipping the stack trace) but that was deemed too scary for the end-user, so the current version that simply prints the transfer error and exits came to be. The addition of a new positional argument breaks calls that `download()` and `upload()` that rely on positional arguments, although they should still probably be replaced with keyword arguments for clarity and most of them are from legacy code. If there is a need for detailed error logging, that can be arranged based on a feature request.

The `@umask()` context manager would benefit from being moved to a place like `vyos.utils.io` for broader use but it would have to be rewritten in class syntax because of top-level `import contextlib`.

## How to test

`# load <remote URL>`

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Looks good
```

vyos@r4# load http://192.168.122.14:8080/config.txt
Loading configuration from 'http://192.168.122.14:8080/config.txt'
Load complete. Use 'commit' to make changes effective.
[edit]
vyos@r4# 
[edit]
vyos@r4# compare 
[interfaces]
+ dummy dum0 {
+     address "203.0.113.1/32"
+ }

[edit]
vyos@r4# 
vyos@r4# 
vyos@r4# curl -k --location --request POST 'https://localhost/config-file' \
> --form data='{"op": "load", "file": "http://192.168.122.14:8080/config.txt"}' \
> --form key='foo'

{"success": true, "data": null, "error": null}[edit]
vyos@r4# 

```

**Review by sever-sever — APPROVED** [review]

**Review by jestabro — APPROVED** [review]

**Comment by c-po** [comment]
Off topic question, can I POST an entire config as JSON to the API?

**Comment by jestabro** [comment]
> Off topic question, can I POST an entire config as JSON to the API?

Not in practice, since the argument 'path' to the config section to be replaced must be non-empty, as validated by the http-api, so one can only replace a section of the config at a specified path.

It would be simple to extend the /configure or /config-file endpoint to allow loading a config from JSON, but this raises issues with hw-id --- @sever-sever 's solution was to restrict to reasonable sub-sections of the config.

**Comment by sever-sever** [comment]
There is community member writes ansible module based on JSON load https://www.reddit.com/r/vyos/comments/152aurr/comment/jsj40ke/

**Review by c-po — APPROVED** [review]

**Comment by sever-sever** [comment]
@MergifyIo backport sagitta

**Pull request merged**
