### PR TITLE
T4839: firewall: Adding dynamic firewall groups feature

### PR DESCRIPTION
**Pull request by nicolas-fort**
## Change Summary

Add new feature: dynamic firewall groups

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4839

## Component(s) name

firewall
## Proposed changes

Add dynamic firewall groups, and rules features to dynamically add element to such groups.

## How to test

Config example
```
vyos@vyos# run show config comm | grep fire
set firewall dynamic-group address-group dynag01
set firewall dynamic-group ipv6-address-group dag6_01 address '2008:db1::55'
set firewall group port-group PG01 port '22'
set firewall group port-group PG01 port '23'
set firewall interface eth0 local name 'FOO'
set firewall interface eth0 local ipv6-name 'FOO6'
set firewall ipv6-name FOO6 rule 10 action 'drop'
set firewall ipv6-name FOO6 rule 10 description 'Drop all from attackers'
set firewall ipv6-name FOO6 rule 10 source dynamic-group address-group 'dag6_01'
set firewall ipv6-name FOO6 rule 20 action 'drop'
set firewall ipv6-name FOO6 rule 20 add-address-to-group source-address address-group 'dag6_01'
set firewall ipv6-name FOO6 rule 20 description 'Catch attackers'
set firewall ipv6-name FOO6 rule 20 destination group port-group 'PG01'
set firewall ipv6-name FOO6 rule 20 protocol 'tcp'
set firewall name FOO rule 10 action 'drop'
set firewall name FOO rule 10 description 'Drop all from attackers'
set firewall name FOO rule 10 source dynamic-group address-group 'dynag01'
set firewall name FOO rule 20 action 'drop'
set firewall name FOO rule 20 add-address-to-group source-address address-group 'dynag01'
set firewall name FOO rule 20 add-address-to-group source-address timeout-unit 'day'
set firewall name FOO rule 20 add-address-to-group source-address timeout-value '48'
set firewall name FOO rule 20 description 'Catch ssh attackers ip address'
set firewall name FOO rule 20 destination port '22'
set firewall name FOO rule 20 protocol 'tcp'
set firewall name FOO rule 30 action 'drop'

```
Relevant nft config (after one ssh attemp):
```
vyos@vyos# sudo nft -S list table ip vyos_filter
table ip vyos_filter {
        set P_PG01 {
                type inet_service
                flags interval
                auto-merge
                elements = { 22-23 }
        }

        set DA_dynag01 {
                type ipv4_addr
                size 65535
                flags dynamic,timeout
                elements = { 192.168.70.22 timeout 48d expires 47d23h59m54s996ms }
        }
        chain VYOS_FW_LOCAL {
                type filter hook input priority filter; policy accept;
                iifname "eth0" counter packets 198 bytes 28932 jump NAME_FOO
                jump VYOS_POST_FW

        chain NAME_FOO {
                ip saddr @DA_dynag01 counter packets 1 bytes 60 drop comment "FOO-10"
                tcp dport "ssh" counter packets 1 bytes 60 update @DA_dynag01 { ip saddr timeout 48d } drop comment "FOO-20"
                counter packets 196 bytes 28812 drop comment "FOO-30"
                counter packets 0 bytes 0 drop comment "FOO default-action drop"
        }
}

### And ip6 table, with no attacks yet
vyos@vyos# sudo nft -S list table ip6 vyos_filter
table ip6 vyos_filter {
        set P_PG01 {
                type inet_service
                flags interval
                auto-merge
                elements = { 22-23 }
        }

        set DA6_dag6_01 {
                type ipv6_addr
                size 65535
                flags dynamic,timeout
                elements = { 2008:db1::55 }
        }

        chain VYOS_FW6_LOCAL {
                type filter hook input priority filter; policy accept;
                iifname "eth0" counter packets 13 bytes 732 jump NAME6_FOO6
                jump VYOS_POST_FW6
        }
        chain NAME6_FOO6 {
                ip6 saddr @DA6_dag6_01 counter packets 0 bytes 0 drop comment "FOO6-10"
                tcp dport @P_PG01 counter packets 0 bytes 0 update @DA6_dag6_01 { ip6 saddr } drop comment "FOO6-20"
                counter packets 13 bytes 732 drop comment "FOO6 default-action drop"
        }
}
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by nicolas-fort** [comment]
Due to incompatibility with current implementation of firewall groups(flag interval), a new type of groups is needed, so a new node was added

**Comment by sever-sever** [comment]
@nicolas-fort close it or rebase

**Comment by sever-sever** [comment]
@nicolas-fort Are you working on it? 
We want to update all actual PRs or close if they are not actual.

**Comment by nicolas-fort** [comment]
@sever-sever I'm not working on it.
If you think this is important and that should be present in 1.4 LTS, then let me know and I'll re-work on it. Otherwise, I prefer working on more important feature/biugs, and then I'll submit new PR for this feature for 1.5

**Comment by nicolas-fort** [comment]
I'm closing this one in favor of https://github.com/vyos/vyos-1x/pull/2756

**Pull request closed without merging**
