### PR TITLE
T2486: DNS, vyos-hostsd fixes

### PR DESCRIPTION
**Pull request by jjakob**
Accompanying PR https://github.com/vyos/vyatta-cfg-system/pull/125

### CODE REVIEW

**Comment by thomas-mangin** [comment]
very nice patch, but I just notice a FIXME in the added code.

**Comment by jjakob** [comment]
Right, that was forgotten in, the code was fixed. I'll remove it and re-push.

**Comment by jjakob** [comment]
There, the FIXME is removed.

Ideally #423 will get merged too.

**Comment by c-po** [comment]
@jjakob sorry, I just pushed `src/migration-scripts/system/16-to-17`, thus you need to increaste the version to 18

**Comment by c-po** [comment]
Looks good to me! Thank you!

**Comment by jjakob** [comment]
@c-po @dmbaturin https://github.com/vyos/vyatta-cfg-system/pull/125 still hasn't been merged, it contains config version increases for the migrators included in this PR

**Pull request merged**
