### PR TITLE
mirror: T3150: When configuring QoS, the setting procedure of port mirroring is wrong

### PR DESCRIPTION
**Pull request by jack9603301**
## Change Summary

When configuring QoS, the setting procedure of port mirroring is wrong

## Types of changes

 
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

https://phabricator.vyos.net/T3150

## Component(s) name

interfaces: mirror

## Proposed changes

In e8957b57, we used json to parse the `tc qdisc` filter to determine whether it needs to be deleted (reduction of exception mechanism), but now we find that the json output by this command will output unparsed json in some cases, so We have to go back to the processing of the exception mechanism

## How to test

```
set traffic-policy shaper FQ-SHAPER default bandwidth 100%
set traffic-policy shaper MY-SHAPER class 30 match HTTP
set traffic-policy shaper MY-SHAPER class 30 match HTTPs
set interfaces ethernet eth4 traffic-policy out MY-SHAPER
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
What is the behavior using the old implementation from Perl? Did this error occur in the old implementation, too?

**Comment by jack9603301** [comment]
I haven't tested the old implementation, which seems to be similar to the current implementation, which is to force execution without parsing JSON

**Comment by jack9603301** [comment]
`tc -j qdisc show` check seems to be the most reliable in programming logic, because it does not need to throw an exception, but now it seems to be unreliable, because when it returns an error JSON, it will throw an exception to the JSON parser and have to go back to the original implementation

**Comment by jack9603301** [comment]
I think this fix is an urgent implementation, because this bug will destroy the QoS configurator

And this implementation has been verified in the actual vyos system

**Comment by jack9603301** [comment]
@c-po Can we consider reviewing the PR

**Comment by jack9603301** [comment]
@c-po Can we consider reviewing the PR

**Pull request merged**
