### PR TITLE
http-api: T6736: move REST API to a node distinct from GraphQL API

### PR DESCRIPTION
**Pull request by jestabro**
## Change Summary

The REST API was originally implemented under the node ['service', 'https', 'api'], and the GraphQL API implemented as a subnode of that path. Refactor the http-api server into distinct configuration nodes:

['service', 'https', 'api', 'rest']
['service', 'https', 'api', 'graphql']

Structures shared by the apis are simplified; distinct structures are organized more symmetrically.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes)
        --- the one functional change is that the GraphQL API may now be made available independently of the REST API.

- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related PR(s)

https://github.com/vyos/vyos-documentation/pull/1557

## Smoketest result

```
DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_service_https.py
DEBUG - test_api_add_delete (__main__.TestHTTPSService.test_api_add_delete) ... ok
DEBUG - test_api_auth (__main__.TestHTTPSService.test_api_auth) ... ok
DEBUG - test_api_config_file (__main__.TestHTTPSService.test_api_config_file) ... ok
DEBUG - test_api_config_file_load_http (__main__.TestHTTPSService.test_api_config_file_load_http) ... ok
DEBUG - test_api_configure (__main__.TestHTTPSService.test_api_configure) ... ok
DEBUG - test_api_generate (__main__.TestHTTPSService.test_api_generate) ... ok
DEBUG - test_api_image (__main__.TestHTTPSService.test_api_image) ... ok
DEBUG - test_api_incomplete_key (__main__.TestHTTPSService.test_api_incomplete_key) ... ok
DEBUG - test_api_missing_keys (__main__.TestHTTPSService.test_api_missing_keys) ... ok
DEBUG - test_api_reset (__main__.TestHTTPSService.test_api_reset) ... ok
DEBUG - test_api_show (__main__.TestHTTPSService.test_api_show) ... ok
DEBUG - test_certificate (__main__.TestHTTPSService.test_certificate) ... ok
DEBUG -
DEBUG - ----------------------------------------------------------------------
DEBUG - Ran 12 tests in 70.122s
DEBUG -
DEBUG - OK
```

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [X] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by jestabro** [comment]
The only remaining linting errors are due to an attempt to apply ruff to a now deleted file (since listed as a 'changed' file). Need to use `added|modified` in filter here:
https://github.com/vyos/.github/blob/current/.github/workflows/lint-with-ruff.yml#L28

**Comment by jestabro** [comment]
Comments as to why the CodeQL scans are now dismissed are under 'Show dismissed'/'Show more details', namely:

1. The stack trace does not expose any structure that is not already apparent by inspection of the open source code repository. 
2. The code scan is missing the fact that the return value is now sanitized by html.escape().

**Review by sever-sever — APPROVED** [review]

**Comment by jestabro** [comment]
Linting error fixed with:
https://github.com/vyos/.github/pull/49

**Review by dmbaturin — APPROVED** [review]
I have a feeling that we should avoid mixing formatting changes with logic updates in the future, since PRs can be quite hard to review if they contain a lot of non-functional code changes.

**Comment by jestabro** [comment]
Agreed, however, we need formatting updates in order to pass the linting check: the compromise here was to have all formatting changes is a single commit. Other PR's currently being prepared make the formatting update the initial commit, with logic changes following, which may be easier to read.

**Pull request merged**
