### PR TITLE
vyos.util: T3532: Replace func get_interface_config

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Replace function "**func get_interface_config**" (1.3) to function "**get_interface_config**"  which used that commit https://github.com/vyos/vyos-1x/commit/edcdea890b2eeb03d24b06fdd8ac38133e631c05
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3532

## Component(s) name

vyos.util
## Proposed changes
Before fix
```
vyos@r4-1.3:~$ show int
Traceback (most recent call last):
  File "/usr/libexec/vyos/op_mode/show_interfaces.py", line 26, in <module>
    from vyos.ifconfig import Section
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/__init__.py", line 18, in <module>
    from vyos.ifconfig.interface import Interface
  File "/usr/lib/python3/dist-packages/vyos/ifconfig/interface.py", line 39, in <module>
    from vyos.util import get_interface_config
ImportError: cannot import name 'get_interface_config' from 'vyos.util' (/usr/lib/python3/dist-packages/vyos/util.py)
vyos@r4-1.3:~$ 
```
After
```
vyos@r4-1.3:~$ show int
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface        IP Address                        S/L  Description
---------        ----------                        ---  -----------
eth0             192.168.122.14/24                 u/u  
eth1             -                                 u/u  foo
lo               127.0.0.1/8                       u/u  
                 ::1/128                                

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
It's called `get_json_iface_options` on VyOS 1.3

**Comment by sever-sever** [comment]
Just we only need to replace it to "get_json_iface_options " ?
https://github.com/vyos/vyos-1x/blob/9197a409876f9943032ac19834b5f04bdac6e00a/python/vyos/ifconfig/interface.py#L39

**Comment by c-po** [comment]
Yes, or rename all ovvurances with the old name `get_json_iface_options` with the new name from VyOS 1.4 branch `get_interface_config()`

**Comment by sever-sever** [comment]
> or rename all ovvurances with the old name `get_json_iface_options` with the new name from VyOS 1.4 branch `get_interface_config()`

Done

**Pull request merged**
