### PR TITLE
dhcp: T5948: Strip trailing dot from hostnames

### PR DESCRIPTION
**Pull request by sarthurdev**
## Change Summary

Strip trailing dot from received DHCP hostname

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5948

## Component(s) name

dhcp-server

## Proposed changes

Strips '.' from hostname variable, hostnames should only contain alphanumeric and hyphen characters.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Comment by sarthurdev** [comment]
No backport necessary here, should only be issue with Kea.

**Comment by chenxiaolong** [comment]
Thanks for the quick fix! Would it make sense to use `${!client_name_var%.}` instead? The current solution also eliminates dots in the middle.

If the client runs eg. `sudo dhcpcd -h foo.bar -F both -4B enp2s0f0np0`, then VyOS will treat it as `foobar.<domain>` instead of `foo.bar.<domain>`. (Corporate Windows machines tend to do this sort of thing in my experience.)

EDIT: That said, I have no objection at all if VyOS prefers to just keep the solution of getting rid of all dots.

**Comment by sarthurdev** [comment]
The hostname should follow the domain segment character limitations (alphanumeric/hyphen only). Though the RFC does seem to indicate the field may instead contain the whole FQDN.

I'm not sure however If Kea hooks send the FQDN or strip the suffix, I suppose if it does send a FQDN, the script would mangle the hostname (e.g. recv'd hostname = testserver.network.lan, resulting client_name = testservernetworklan.network.lan).

I'll experiment in my Kea lab.

**Pull request merged**
