### PR TITLE
T5146: Show recent login of all users

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Ability to show all recent logins.

Propose one of the following commands:
```
- show log last-login
- show login last-login
- show login recent
- show login recent-log
- show login log
- show login last-log
```
I'm not sure which option will be the best

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5146

## How to test
```
vyos@r14:~$ show login last-log 
Username         Port     From                                       Latest
root                                                                **Never logged in**
daemon                                                              **Never logged in**
bin                                                                 **Never logged in**
sys                                                                 **Never logged in**
sync                                                                **Never logged in**
games                                                               **Never logged in**
man                                                                 **Never logged in**
lp                                                                  **Never logged in**
mail                                                                **Never logged in**
news                                                                **Never logged in**
uucp                                                                **Never logged in**
proxy                                                               **Never logged in**
www-data                                                            **Never logged in**
backup                                                              **Never logged in**
list                                                                **Never logged in**
irc                                                                 **Never logged in**
_apt                                                                **Never logged in**
nobody                                                              **Never logged in**
systemd-network                                                     **Never logged in**
telegraf                                                            **Never logged in**
radvd                                                               **Never logged in**
strongswan                                                          **Never logged in**
uuidd                                                               **Never logged in**
messagebus                                                          **Never logged in**
tftp                                                                **Never logged in**
tss                                                                 **Never logged in**
stunnel4                                                            **Never logged in**
conservr                                                            **Never logged in**
arpwatch                                                            **Never logged in**
frr                                                                 **Never logged in**
ocserv                                                              **Never logged in**
pdns                                                                **Never logged in**
tcpdump                                                             **Never logged in**
iperf3                                                              **Never logged in**
_chrony                                                             **Never logged in**
haproxy                                                             **Never logged in**
smmta                                                               **Never logged in**
smmsp                                                               **Never logged in**
Debian-snmp                                                         **Never logged in**
_dnsdist                                                            **Never logged in**
_lldpd                                                              **Never logged in**
owamp                                                               **Never logged in**
sstpc                                                               **Never logged in**
avahi                                                               **Never logged in**
twamp                                                               **Never logged in**
sshd                                                                **Never logged in**
hacluster                                                           **Never logged in**
polkitd                                                             **Never logged in**
minion                                                              **Never logged in**
openvpn                                                             **Never logged in**
radius_user                                                         **Never logged in**
radius_priv_user                                                    **Never logged in**
dhcpd                                                               **Never logged in**
foo              pts/1    192.168.122.1                             Wed Apr  5 16:01:10 +0300 2023
vyos             pts/0    192.168.122.1                             Wed Apr  5 19:03:35 +0300 2023
vyos@r14:~$
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by indrajitr** [comment]
Would it make sense to apply filter and remove the [reserved uids](https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes)?

Maybe with something like `lastlog --user 1002-59999`?

**Comment by c-po** [comment]
> Would it make sense to apply filter and remove the [reserved uids](https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes)?
> 
> Maybe with something like `lastlog --user 1002-59999`?

I was about to say the same thing. We're not interested in system UIDs only the users + radius. Can you change it please @sever-sever

**Comment by sever-sever** [comment]
> > Would it make sense to apply filter and remove the [reserved uids](https://www.debian.org/doc/debian-policy/ch-opersys.html#uid-and-gid-classes)?
> > Maybe with something like `lastlog --user 1002-59999`?
> 
> I was about to say the same thing. We're not interested in system UIDs only the users + radius. Can you change it please @sever-sever

@c-po @indrajitr  It is useful if the system was hacked and someone log in with a system user, we should/must show it. It was the goal due to the security audit.
And it doesn't make any sense in this command if we show only some users.

**Comment by indrajitr** [comment]
Sure! So isn't this getting too similar to what is already there currently?

```
tempuser@vyos-temp:~$ show system login users 
Possible completions:
  <Enter>               Execute the current command
  all                   Show information about all accounts
  locked                Show information about locked accounts
  other                 Show information about non VyOS user accounts
  vyos                  Show information about VyOS user accounts
```

**Comment by sever-sever** [comment]
> Sure! So isn't this getting too similar to what is already there currently?

Thanks

**Pull request closed without merging**
