### PR TITLE
tunnel: T2028: move interface tunnel to XML/Python

### PR DESCRIPTION
**Pull request by thomas-mangin**
This patch migrates the "interface tunnel" section to xml/python

### CODE REVIEW

**Comment by c-po** [comment]
Thanks for this huge PR. Infact I do not like the part where you alter existing behavior in `vyos.ifconfig` and just place it in the very same commit. Usually such changes - even when they are required for future changes - should be placed in an individual commit. This makes tracking changes and the evolution of code much easier.

Can I ask you to place that modification in an individual commit?

**Comment by thomas-mangin** [comment]
@c-po no issues at all. I perfectly agree that this should be moved out. I was just unsure if you would have wanted to see some of the other creation logic moved into "Interface". I have created https://github.com/vyos/vyos-1x/pull/223 as requested.

**Comment by thomas-mangin** [comment]
for clarity, I am not asking for this PR to be merged at this point. I just wanted to check if there was an issue with the approach if the use of `ConfigurationState` as it is was fine. I am still to write the unit testing and related show commands.

**Comment by c-po** [comment]
Please follow the commit rules where each commit must be prefixed with a topic and a task id.

**Pull request merged**
