### PR TITLE
T5770 Enable MACsec encryption stanza

### PR DESCRIPTION
**Pull request by giga1699**
## Change Summary

Enables encryption mode when using MACsec

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5770

## Component(s) name

MACSEC

## Proposed changes

Enable encryption when creating MACsec interface using "ip link" command

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
It's odd that we did have a node in the CLI definition but not this...

**Comment by giga1699** [comment]
I did check to make sure I didn't accidentally delete some config from my previous PR. I swear I remember it encrypting in 1.4 when I was testing the previous change. Not sure how it ended up not setting that value now.

**Comment by c-po** [comment]
Extended the commit and added the appropriate smoketests


```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_interfaces_macsec.py
test_add_multiple_ip_addresses (__main__.MACsecInterfaceTest.test_add_multiple_ip_addresses) ... ok
test_add_single_ip_address (__main__.MACsecInterfaceTest.test_add_single_ip_address) ... ok
test_dhcp_client_options (__main__.MACsecInterfaceTest.test_dhcp_client_options) ... ok
test_dhcp_disable_interface (__main__.MACsecInterfaceTest.test_dhcp_disable_interface) ... ok
test_dhcp_vrf (__main__.MACsecInterfaceTest.test_dhcp_vrf) ... ok
test_dhcpv6_client_options (__main__.MACsecInterfaceTest.test_dhcpv6_client_options) ... ok
test_dhcpv6_vrf (__main__.MACsecInterfaceTest.test_dhcpv6_vrf) ... ok
test_dhcpv6pd_auto_sla_id (__main__.MACsecInterfaceTest.test_dhcpv6pd_auto_sla_id) ... ok
test_dhcpv6pd_manual_sla_id (__main__.MACsecInterfaceTest.test_dhcpv6pd_manual_sla_id) ... ok
test_interface_description (__main__.MACsecInterfaceTest.test_interface_description) ... ok
test_interface_disable (__main__.MACsecInterfaceTest.test_interface_disable) ... ok
test_interface_ip_options (__main__.MACsecInterfaceTest.test_interface_ip_options) ... ok
test_interface_ipv6_options (__main__.MACsecInterfaceTest.test_interface_ipv6_options) ... ok
test_interface_mtu (__main__.MACsecInterfaceTest.test_interface_mtu) ... ok
test_ipv6_link_local_address (__main__.MACsecInterfaceTest.test_ipv6_link_local_address) ... ok
test_macsec_encryption (__main__.MACsecInterfaceTest.test_macsec_encryption) ... ok
test_macsec_gcm_aes_128 (__main__.MACsecInterfaceTest.test_macsec_gcm_aes_128) ... ok
test_macsec_gcm_aes_256 (__main__.MACsecInterfaceTest.test_macsec_gcm_aes_256) ... ok
test_macsec_source_interface (__main__.MACsecInterfaceTest.test_macsec_source_interface) ... ok
test_macsec_static_keys (__main__.MACsecInterfaceTest.test_macsec_static_keys) ... ok
test_mtu_1200_no_ipv6_interface (__main__.MACsecInterfaceTest.test_mtu_1200_no_ipv6_interface) ... ok
test_span_mirror (__main__.MACsecInterfaceTest.test_span_mirror) ... skipped 'not supported'
test_vif_8021q_interfaces (__main__.MACsecInterfaceTest.test_vif_8021q_interfaces) ... skipped 'not supported'
test_vif_8021q_lower_up_down (__main__.MACsecInterfaceTest.test_vif_8021q_lower_up_down) ... skipped 'not supported'
test_vif_8021q_mtu_limits (__main__.MACsecInterfaceTest.test_vif_8021q_mtu_limits) ... skipped 'not supported'
test_vif_8021q_qos_change (__main__.MACsecInterfaceTest.test_vif_8021q_qos_change) ... skipped 'not supported'
test_vif_s_8021ad_vlan_interfaces (__main__.MACsecInterfaceTest.test_vif_s_8021ad_vlan_interfaces) ... skipped 'not supported'
test_vif_s_protocol_change (__main__.MACsecInterfaceTest.test_vif_s_protocol_change) ... skipped 'not supported'

----------------------------------------------------------------------
Ran 28 tests in 125.372s

OK (skipped=7)

```

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
