### PR TITLE
@1vivy dhcpv6-pd: T5387: add support for no-release flag

### PR DESCRIPTION
**Pull request by 1vivy**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5387

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I think you forgot to `git add` the `dhcp-client/dhcp6c_daemon-options.j2` file

**Comment by 1vivy** [comment]
I have questions about this repo and it's dev env. I'm not sure if the template is supposed to be made by `make` or I can do it by hand in this case. I think I have to have a VyOS instance for development. Stuff to ask on slack

**Comment by c-po** [comment]
You need to create the template on your own - as its new code. 

It will be packages during package build using make deb

**Comment by 1vivy** [comment]
> You need to create the template on your own - as its new code.
> 
> It will be packages during package build using make deb

I was overthinking the Jinja2 template, I thought the `Autogenerated by...` might have meant I should let something compile to make a boilerplate yadayada derp. Thanks

**Review by c-po — APPROVED** [review]

**Pull request merged**
