### PR TITLE
T5935: config: Ensure ethernet VIFs exist before configuring ddclient

### PR DESCRIPTION
**Pull request by MattKobayashi**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5935

## Component(s) name

`config`

## Proposed changes

This PR adds a configuration dependency for `service dns dynamic` on `interfaces ethernet`, to ensure that `ddclient` isn't configured before VIF interfaces are created.

## How to test

Apply the following configuration:

```
set interfaces ethernet eth0 vif 101 address 'dhcp'
set service dns dynamic name ddns address 'eth0.101'
set service dns dynamic name ddns host-name 'example.duckdns.org'
set service dns dynamic name ddns ip-version 'both'
set service dns dynamic name ddns password <REDACTED>
set service dns dynamic name ddns protocol 'duckdns'
```

Reboot VyOS, it should apply the configuration successfully on boot, but without the fix it does not work, and leaves the router in a broken state.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
It looks strange as based on priority, it should work without any change.

```
vyos@r4:~$ /opt/vyatta/sbin/priority.pl | match "dynamic|ethern"

318 interfaces/ethernet
...
990 service/dns/dynamic
vyos@r4:~$ 

```

**Comment by c-po** [comment]
Please note that its not sufficient just to add the dependency here, it must be called, too.

Given the priorities mentioned by @sever-sever  this should not be needed at all - do you experience a bug?

**Comment by MattKobayashi** [comment]
Hi @c-po, yes, there appears to be a bug in the boot process whereby if `ddclient` is configured to bind to an Ethernet VIF interface, it tries to do so before the interface exists, causing the configuration load on boot to fail. The failure occurs before any interfaces are configured, leaving the router inaccessible except via console.

I added the following to the Phabricator bug report:

> On boot, the configuration is attempted to be applied by the `service_dns_dynamic.py` script, which uses the `verify_interface_exists` function from `vyos.configverify` to verify if the interface to be bound exists: https://github.com/vyos/vyos-1x/blob/current/src/conf_mode/service_dns_dynamic.py#L101
>
> The issue seems to be that this function throws a `ConfigError` exception if the interface doesn't exist, which I believe causes the boot time configuration load to be aborted before it has finished, leaving the router in a broken state: https://github.com/vyos/vyos-1x/blob/current/python/vyos/configverify.py#L279

**Comment by c-po** [comment]
I‘m unable to reproduce the bug (see phabricator). Can you share your full config?

**Comment by MattKobayashi** [comment]
Upon further investigation, it appears that I was incorrect. The issue was caused by a USB device that creates an Ethernet interface, and I suspect that this USB device wasn't ready when ddclient was trying to bind to it, causing the failure. I'm closing out this PR as it's not necessary.

**Comment by c-po** [comment]
Thanks for sharing the original issue

**Pull request closed without merging**
