### PR TITLE
container: T5401: only migrate non-overlay images

### PR DESCRIPTION
**Pull request by yzguy**
## Change Summary
This PR refactors the container 0-to-1 migration script to only migrate containers that have non-overlay filesystem images instead of all images.

Previously the migration script does this for all containers regardless of type which means each container was stopped, exported, imported, started every time the configuration was changed which is impactful to applications running in the containers (and potentially traffic)

```
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
3f0e2eea05aa  docker.io/cloudflare/gortr:latest  -cache https://dn...  57 minutes ago  Up 57 minutes ago              gortr
[edit]
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
6a729c2e5ed8  docker.io/cloudflare/gortr:latest  -cache https://dn...  16 seconds ago  Up 16 seconds ago              gortr
[edit]
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
f887a92801ee  docker.io/cloudflare/gortr:latest  -cache https://dn...  14 seconds ago  Up 14 seconds ago              gortr
[edit]
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5401

## Component(s) name
container

## Proposed changes
Update container migration script to grab the filesystem type for each image a container uses and only perform the migration when it's not overlay.

## How to test

1. Save current configuration (from configure) - `show > /var/tmp/config.txt`
2. Add container to container section if one does not exist

```
container {
    name gortr {
        allow-host-networks { }
        arguments "-cache https://dn42.burble.com/roa/dn42_roa_46.json -verify=false -checktime=false -bind :8082"
        image "cloudflare/gortr"
        port http {
            destination "8082"
            source "8082"
        }
    }
} 
```

3. Load configuration - `load /var/tmp/config.txt`
4. Apply configuration - `commit`
5. View uptime of container(s) - `sudo podman ps`
6. Apply migration script changes
7. Load configuration again `load /var/tmp/config.txt`
8. Verify container uptime has not reset - `sudo podman ps`

```
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
[edit]
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
Load complete. Use 'commit' to make changes effective.
[edit]
yzguy@test-R1# compare
[]
+ container {
+     name gortr {
+         allow-host-networks { }
+         arguments "-cache https://dn42.burble.com/roa/dn42_roa_46.json -verify=false -checktime=false -bind :8082"
+         image "cloudflare/gortr"
+         port http {
+             destination "8082"
+             source "8082"
+         }
+     }
+ }

[edit]
yzguy@test-R1# commit
[edit]
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED             STATUS                 PORTS       NAMES
a171a51fca1e  docker.io/cloudflare/gortr:latest  -cache https://dn...  About a minute ago  Up About a minute ago              gortr
[edit]
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
5b42500785bc  docker.io/cloudflare/gortr:latest  -cache https://dn...  25 seconds ago  Up 25 seconds ago              gortr
[edit]
yzguy@test-R1# sudo nvim /opt/vyatta/etc/config-migrate/migrate/container/0-to-1
[edit]
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED             STATUS                 PORTS       NAMES
5b42500785bc  docker.io/cloudflare/gortr:latest  -cache https://dn...  About a minute ago  Up About a minute ago              gortr
[edit]
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED             STATUS                 PORTS       NAMES
5b42500785bc  docker.io/cloudflare/gortr:latest  -cache https://dn...  About a minute ago  Up About a minute ago              gortr
[edit]
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
> started every time the configuration was changed

Can you elaborate a bit more on the every time part? Migration script is only run once during image upgrade if required.

**Comment by yzguy** [comment]
> > started every time the configuration was changed
> 
> Can you elaborate a bit more on the every time part? Migration script is only run once during image upgrade if required.

The script gets run every time you do a “load” command to load the whole configuration from a file, http, scp, etc endpoint. In my use case we render out the entire device configuration, copy it to the device, run `load /var/tmp/candidate_running.conf` to load it as the candidate configuration. This is a declarative approach to managing the devices through automation.

What we see is that when we do the load, the migration script is run, which stops the container, saves the image to disk, imports it, then starts it again. You can see that in the output above, the uptime of the container goes down after a `load` command is run every time because it’s stopped/started again due to the migration script.

https://vyos.dev/T5365 is related in that every time we did `load` it ran systemctl stop without sudo, which caused the authentication prompt every time.

**Comment by c-po** [comment]
Ah, okay! If you always load the configuration migrators get executed depending on the CLI version. Check the last line of your file you load, it contains all the versions.

If no version information is found, default versions are used and every migrator is executed.

**Comment by yzguy** [comment]
> Ah, okay! If you always load the configuration migrators get executed depending on the CLI version. Check the last line of your file you load, it contains all the versions.
> 
> If no version information is found, default versions are used and every migrator is executed.

Ah, well guess what I didn't have at the bottom of the template and completely ignored the warning

```
// Warning: Do not remove the following line.
```

Just confirmed that it doesn't restart the containers when it's there

```
yzguy@test-R1# cp /config/config.boot /var/tmp/config.txt
[edit]

# Remove bottom lines
yzguy@test-R1# nvim /var/tmp/config.txt 
[edit]

# Load config without lines
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]

# Container restarts
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
fb5e59e59adb  docker.io/cloudflare/gortr:latest  -cache https://dn...  16 seconds ago  Up 16 seconds ago              gortr
[edit]

# Add Back the Bottom Lines
yzguy@test-R1# nvim /var/tmp/config.txt
[edit]

# Load config with lines
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]

# Container doesn't restart
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
fb5e59e59adb  docker.io/cloudflare/gortr:latest  -cache https://dn...  29 seconds ago  Up 30 seconds ago              gortr
[edit]

# Load config with lines again
yzguy@test-R1# load /var/tmp/config.txt
Loading configuration from '/var/tmp/config.txt'
No configuration changes to commit.
[edit]

# Container doesn't restart
yzguy@test-R1# sudo podman ps
CONTAINER ID  IMAGE                              COMMAND               CREATED         STATUS             PORTS       NAMES
fb5e59e59adb  docker.io/cloudflare/gortr:latest  -cache https://dn...  39 seconds ago  Up 39 seconds ago              gortr
[edit]
```

@c-po Thanks for taking a look, so while this wasn't needed. The same conditions existed (no lines at the bottom) when I made https://vyos.dev/T5365 so do you believe those code changes for that are still needed? I suspect yes because if the migration had to run legitimately, it would need sudo to do those things anyway.

**Comment by c-po** [comment]
> @c-po Thanks for taking a look, so while this wasn't needed. The same conditions existed (no lines at the bottom) when I made https://vyos.dev/T5365 so do you believe those code changes for that are still needed? I suspect yes because if the migration had to run legitimately, it would need sudo to do those things anyway.

That's a legitimate change as we have multiple `sudo` calls in the migration scripts. Usually it's only about mangling CLI node but sometimes heavy plumbing is required on the OS.

Closing this

**Pull request closed without merging**
