### PR TITLE
T5909: Use warning for attempt to connect to containers registry

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

This fixes the issue when system does not have the Internet connection while attempting to use container registry with login and password. It causes after rebooting we do not have section `container` at all.

The container priority 450
The protocols static priority 480

The best way to fix is using `Warning` insted of `raise ConfigError`
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5909

## Component(s) name

container
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I wonder if there is not a better solution. Why not call podman login inside the add container image call?

Do we need to login at all while processing the CLI? Why not make it a key value store only, Use ConfigTreeQuery in op-mode and login where it‘s really needed?

**Comment by sever-sever** [comment]
It should be reimplemented as in comment above 
Close it 
For now it will be a know issue until someone rewrite it

**Comment by sever-sever** [comment]
Until we have the registry and authentication in configuration, we should fix it as proposed in this commit way.
You should optionally set authentication during the load image.
It is not loading configuration; instead, it is just a warning message.
Deleting authentication from the configuration should be done by a separate task if required.

**Comment by adestis-mb** [comment]
The problem for us and probably others is that when authentication is set that the config fails to load at boot because routing is not available when the container part is initialized.
This means for us always patch vyos files on the Disk for each installation, really a pity.

**Comment by c-po** [comment]
@adestis-mb this is actually what we wanted to have with the current implementation. Please provide set commands how to replicate the issue so we can fix it.

**Comment by adestis-mb** [comment]
https://vyos.dev/T5909

**Comment by adestis-mb** [comment]
I have to add that you have a default route to the internet

**Pull request closed without merging**
