### PR TITLE
T427, T773 adding wirguard support

### PR DESCRIPTION
**Pull request by hagbard-01**
Since I had the routing and keying part added to the conf mode script. I've tested the package via manual install, when I build the iso it downloads from dev.packages.vyos.net, so I just did an install image and a dpkg -i to check that there are no issues. Once I have the conf mode script cleaned up, I do another pull request for it.

### CODE REVIEW

**Comment by dmbaturin** [comment]
Wait, but where is the conf mode definitions and scripts for it now?

**Comment by hagbard-01** [comment]
conf mode and the conf script comes shortly. I have to remove the key generation and routing options like you suggested and do a few tests with it. I just pushed the stuff which can be released already. I'm currently finishing up the vyos-build (automatic module loading), after that I can remove the loader from the scripts (they don't hurt, but it's the later on cleaner). The conf script and interface is then just the last piece, I have it already in my own branch, but as mentioned needs some cleanup, since I had everything in one script.

**Comment by hagbard-01** [comment]
Is still anything holding a merge up?

**Comment by dmbaturin** [comment]
I see you've added the conf mode. Is it complete now?

**Comment by hagbard-01** [comment]
Yes it is. It is a working version, but I plan to add a few things in the next couple of weeks, like show status and the such. I was 't able to reproduce Kim's comment, I downloaded the latest rolling, installed the wireguard packages and my version of vyos-1x, rebooted and didn't see that kernel module was loaded. I have a few code lines in both scripts which check if the module is loaded and if not it does it automatically and drops a message to syslog. I was playing around with it, it works pretty stable, I didn't come over any issues so far, but I also tested everything in a local network (checked with tcpdump the traffic). For the future, we need some type of standardized procedure to have kmods automatically loaded, in my opinion they should be in the package if the pkg is provided by vyos, if it comes via debian it should be in vyos-build.

**Comment by dmbaturin** [comment]
Ok, let's merge it then. Please make new PRs when you add more features!

**Pull request merged**
