### PR TITLE
ddclient: T5144,T5791: Fix migration to avoid config name conflict

### PR DESCRIPTION
**Pull request by indrajitr**
## Change Summary

This PR has fix for two potential issues:

* As part of T5144, we merged all services that used web-based address lookup under `service dns dynamic address web ...`. When migrating from `service dns dynamic interface <interface> ...` to `service dns dynamic address <address> ...`, the config name can potentially have a conflict when `address == 'web'`. Although the `/run/ddclient/ddclient.conf` that was generated earlier was incorrect, one could still potentially have misconfigured VyOS config without realizing it.
We now append the old <interface> name to the config name to avoid conflict.

* As part of T5791, since `service dns dynamic address <address> service <service> ...` changed to `service dns dynamic name <service> address <address> ...`, the resulting service and address config flip can result in conflicting `service` name.
We now migrate the service name to `<service>-<address>` to avoid the conflict.
So `service dns dynamic address <address> service <service> ...` is migrated to `service dns dynamic name <service>-<address> address <address> ...`

* Additionally, based on the recommendation in the PR review, service names now conform to alphanumeric constraints. The migration script normalizes the old names to conform to the constraints.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5144
* https://vyos.dev/T5791
* https://vyos.dev/T5721

## Component(s) name

dns dynamic

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — CHANGES_REQUESTED** [review]
Can dou please use zyphens in the tag Node service-address representation? Then its identical to the IPSec migrator and we can have a proper constraint on the tagNode

**Comment by indrajitr** [comment]
> Can dou please use zyphens in the tag Node service-address representation? Then its identical to the IPSec migrator and we can have a proper constraint on the tagNode

`service dns dynamic address <address> service <service> ...` is now migrated to `service dns dynamic name <service>-<address> address <address> ...`.

**Comment by c-po** [comment]
Oh, sorry - this is not what I ment. The service name should be (after migration) `dyndns-172-16-1-1` instead of `dyndns-172.16.1.1`

**Comment by c-po** [comment]
Please add a contraint here https://github.com/vyos/vyos-1x/blob/current/interface-definitions/dns-dynamic.xml.in#L15-L22 so only valid names can be used and not something like `set service dns dynamic name fooÄÖÜBARß?=/(` 

You are most likely well suited using this statement:
```xml
<constraint>
  #include <include/constraint/alpha-numeric-hyphen-underscore.xml.i>
</constraint>
```

**Comment by indrajitr** [comment]
My apologies too, I didn't catch what you meant. PR is now updated based on your recommendation.

**Review by c-po — APPROVED** [review]

**Pull request merged**
