### PR TITLE
vyos.template: T5869: first_host_address() does not honor RFC4291 section 2.6.1

### PR DESCRIPTION
**Pull request by c-po**
## Change Summary

The subnet router anycast address is predefined. Its format is as follows:
```
|                         n bits                 |   128-n bits   |
+------------------------------------------------+----------------+
|                   subnet prefix                | 00000000000000 |
+------------------------------------------------+----------------+
```

The "subnet prefix" in an anycast address is the prefix that identifies a specific link. This anycast address is syntactically the same as a unicast address for an interface on the link with the interface identifier set to zero.

Packets sent to the Subnet-Router anycast address will be delivered to one router on the subnet. All routers are required to support the Subnet-Router anycast addresses for the subnets to which they have interfaces.

The Subnet-Router anycast address is intended to be used for applications where a node needs to communicate with any one of the set of routers.

Our code as of now returns the subnet router anycast address as the `first_host_address()`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5869

## Component(s) name

Jinja2 templates

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Not sure if it works fine
```
>>> first_host_address('192.0.2.1/30')
'192.0.2.2'
>>> 
>>> 
>>> first_host_address('192.0.2.0/30')
'192.0.2.1'
>>> 
>>> 
>>> 
>>> first_host_address('192.0.2.1/30')
'192.0.2.2'
>>> 
>>> first_host_address('192.0.2.2/30')
'192.0.2.3'
>>> 
>>> first_host_address('192.0.2.3/30')
'192.0.2.4'
>>> 
>>> first_host_address('192.0.2.0/31')
'192.0.2.1'
>>> 

```

**Comment by c-po** [comment]
Another bug. Let me fix it in this PR, too

**Comment by c-po** [comment]
Fixed

**Review by dmbaturin — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
