### PR TITLE
T754: add DNSSEC to DNS forwarder

### PR DESCRIPTION
**Pull request by mb300sd**
Add dnssec support to forwarder. Keeps existing default from powerdns

### CODE REVIEW

**Comment by dmbaturin** [comment]
Looks good? Do we have a task about it in https://phabricator.vyos.net ?
Our standard procedure it to create a task and reference it in commits (e.g. "T42: Add DNSSEC support to DNS forwarder"), so that they are automatically linked with commits, and it's easy to build a changelog from all VyOS packages.

**Comment by c-po** [comment]
Phybricator task is at https://phabricator.vyos.net/T754:

@mb300sd please adjust your commit headline (prefix with task id) to: `T754: add DNSSEC to DNS forwarder` thus the commit will be automatically referenced in the phabricator task. 

Thanks for the contribution, much appreciated!

**Comment by dmbaturin** [comment]
Yes, it seems like a formality, but if you have more than one package, tracking changes and making changelog can become a real nightmare if conventions are not followed!

**Comment by mb300sd** [comment]
All done. Sorry, new to this and the phabricator is kinda confusing.

**Comment by dmbaturin** [comment]
We usually prepend tasks to all commits, but this is sufficient I believe.

**Pull request merged**
