### PR TITLE
 ndptool: T2706: Support NDP protocol monitoring

### PR DESCRIPTION
**Pull request by jack9603301**

### CODE REVIEW

**Comment by c-po** [comment]
Would it be possible to also have a `show` command just giving a snapshot of the current ndp table?

In addition it would be nice to have a command below `monitor ndp` to only show certain messages like rs, ra, ns, na.

**Comment by jack9603301** [comment]
I will implement your second proposal first. As for the first one, I still need to study it.

**Comment by jack9603301** [comment]
I will start to study how to improve it in a few hours. It's evening in China, and the current network is slow

**Comment by jack9603301** [comment]
@c-po 
As far as I know, vyos has the following command to view the network neighbors, which seems to be the NDP table
```
show ipv6 neighbors
```

**Comment by c-po** [comment]
Ah, thanks!

**Comment by jack9603301** [comment]
In the document development section, I suggest that the XML framework formats of operation mode and configuration mode should be explained separately. I have to say that this makes me a little confused

**Comment by c-po** [comment]
Can you please squash your commits into a single one with a proper commit message, see https://chris.beams.io/posts/git-commit/ for additional info. There are a lot of whitespaces - also a lot of commits for some lines of XML. Actually everything can be squashed into one commit and force-pushed to your branch.

Besides those cosmetic changes the commit works as expected.

**Comment by jack9603301** [comment]
@c-po It has been compressed into a commit

**Pull request merged**
