### PR TITLE
T5743: HTTPS API ability to import PKI certificates

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add HTTPS API call to import PKI certificaties
```
https://vyos/import-pki
```
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5743

## How to test
There is issue for now
```
vyos@r4:~$ curl -k --location --request POST 'https://192.168.122.14/import-pki' \
>   --form data='{"op": "import-pki", "path": ["pki", "ca", "myca", "file", "/config/auth/ca_ansible.crt"]}' \
>   --form key='foo'

{"success": true, "data": "1 value(s) installed. Use \"compare\" to see the pending changes, and \"commit\" to apply.\n", "error": null}vyos@r4:~$ 
vyos@r4:~$ 

```

## Checklist:

- [ ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [ ] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
I see no issues with it.
But on a side node, I wonder if after the old image tools are gone, it will be a good time to replace script calls with function imports.

**Comment by sever-sever** [comment]
> I see no issues with it. But on a side node, I wonder if after the old image tools are gone, it will be a good time to replace script calls with function imports.

@dmbaturin  The issue is that the certificate is not imported yet and waiting for `commit`
Like we have in op-mode (the same message we see in the API via curl):
```
vyos@r4# run import pki ca myca file /config/auth/ca_ansible.crt
1 value(s) installed. Use "compare" to see the pending changes, and "commit" to apply.
[edit]
vyos@r4# compare 
+ pki {
+     ca myca {
+         certificate "xxxxQ=="
+     }
+ }

[edit]
vyos@r4#
```

**Comment by sarthurdev** [comment]
I think this might be best implemented in code for the API.

You can then allow either the cert/key data directly (stripping header/footer, single-line base64 string) in the http payload, or a path and also commit directly.

**Comment by sever-sever** [comment]
Not sure that can implement it now
As I understand it should be like this
```
https://localhost/import-pki
  file: /tmp.ca.crt
  type: ca|certificate|crl|dh|key_pair|openvpn

```
Close the task

**Pull request closed without merging**
