### PR TITLE
IPSec: T3643: Fix path for swanctl.conf file

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Fix path for swanctl configuration file.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3643

## Component(s) name

ipsec, swanctl

## Proposed changes

File path
```
vyos@r1-roll:~$ file /etc/swanctl.conf 
/etc/swanctl.conf: cannot open `/etc/swanctl.conf' (No such file or directory)
vyos@r1-roll:~$ 
vyos@r1-roll:~$ file /etc/swanctl/swanctl.conf 
/etc/swanctl/swanctl.conf: ASCII text
vyos@r1-roll:~$
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — CHANGES_REQUESTED** [review]
Can we move the file path to /run/swanctl?

**Comment by sever-sever** [comment]
> Can we move the file path to /run/swanctl?

It will be better to ask @zdc and @sarthurdev 
I don't have much experience with these configs.

**Comment by zdc** [comment]
From the first view, there should be no problems with this. It seems that the best way for this is setting the `SWANCTL_DIR` environment variable with the wanted path for CLI and using the `--file` argument inside our scripts.

**Comment by c-po** [comment]
Thanks @zdc for the clarification.
As 1.4 is currently not build every night I'm going to merge this and refactor later on

**Pull request merged**
