### PR TITLE
bridge: op-mode: T3667: Fix displaying members of a specific bridge interface

### PR DESCRIPTION
**Pull request by jack9603301**
## Change Summary

Fix displaying members of a specific bridge interface

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3667

## Component(s) name

bridge, op-mode

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Both commands yield the exact same output - why is this change needed?

```bash
cpo@leaf-12:~$ bridge -c link show | grep "master br100"
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
9: vxlan100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
```
```bash
cpo@leaf-12:~$ bridge -c link show br br100
5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
9: vxlan100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
```

The latter (currently present) command uses a better ABI

**Comment by jack9603301** [comment]
> Both commands yield the exact same output - why is this change needed?
> 
> ```shell
> cpo@leaf-12:~$ bridge -c link show | grep "master br100"
> 5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
> 9: vxlan100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
> ```
> 
> ```shell
> cpo@leaf-12:~$ bridge -c link show br br100
> 5: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
> 9: vxlan100: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 master br100 state forwarding priority 32 cost 100 
> ```
> 
> The latter (currently present) command uses a better ABI

In fact, the latter is a wrong command. It actually does not complete the scheduled function (this is my fault. When copying, I mistook them for the same command format)
The latter command seems to print only members with all bridges

图片


图片


Sorry

**Comment by c-po** [comment]
The help string says it explicitly `bridge link show [dev DEV]`

**Comment by jack9603301** [comment]
The `dev` parameter represents not the bridge itself, but the member interface itself

**Pull request merged**
