### PR TITLE
wireguard: T5409: Added 'set interfaces wireguard wgX threaded'

### PR DESCRIPTION
**Pull request by aapostoliuk**
## Change Summary

Added 'set interfaces wireguard wgX threaded' command. 
Process traffic from each peer in a dedicated thread.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5409

## Component(s) name

wireguard
## Proposed changes

Added 'set interfaces wireguard wgX threaded' command. 
Process traffic from each peer in a dedicated thread.
This command is allowed only if one enabled peer exists

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Any reason to not enable this by default?

**Comment by zdc** [comment]
> Any reason to not enable this by default?

Zero, if not negative, benefit for p2p interfaces. Also, bigger overall CPU usage (but distributed between cores).

**Review by sever-sever — APPROVED** [review]

**Review by c-po — CHANGES_REQUESTED** [review]
IMHO this should be enabled by default as it should improve overall system responsiveness if load is distributed among multiple cores.

**Review by dmbaturin — APPROVED** [review]
I think if WireGuard has it off by default, we should probably follow the same approach.

**Comment by c-po** [comment]
> I think if WireGuard has it off by default, we should probably follow the same approach.

If it will be a config option, can we then try to streamline it, as it‘s kind of an offload option? As we use offloading for other interface types ethernet, openvpn, too?

`set interfaces wireguard wgN offload multicore`

**Comment by c-po** [comment]
As discussed in todays maintainer meeting we agreed on:
`set interfaces wireguard wgN per-client-thread`

And also implement this for the WIFI subsystem

**Review by c-po — APPROVED** [review]

**Pull request merged**
