### PR TITLE
firewall: T4502: Update to flowtable CLI

### PR DESCRIPTION
**Pull request by sarthurdev**
## Change Summary

- Changes flowtable CLI to be consistent with firewall refactor and design in https://github.com/vyos/vyos-community-process/pull/3
- Add required interface offload option and verify interface supports hardware offloading
- Prevent error with firewall bridge config

```
set firewall flowtable <name> description <text>
set firewall flowtable <name> interface <ifname>
set firewall flowtable <name> offload [software|hardware]

set firewall [ipv4|ipv6] forward filter rule N action offload
set firewall [ipv4|ipv6] forward filter rule N offload-target <name>
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T4502
* https://vyos.dev/T4072

## Component(s) name

firewall

## Proposed changes

A global option was kindly provided by @vfreex in PR https://github.com/vyos/vyos-1x/pull/2062. This extends on that PR to bring the CLI inline with the refactor and allows for explicit (and multiple) flowtable definitions and rules.

## Smoketest result

```
DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_firewall.py
DEBUG - test_bridge_basic_rules (__main__.TestFirewall.test_bridge_basic_rules) ... ok
DEBUG - test_flow_offload (__main__.TestFirewall.test_flow_offload) ... ok
DEBUG - test_geoip (__main__.TestFirewall.test_geoip) ... ok
DEBUG - test_groups (__main__.TestFirewall.test_groups) ... ok
DEBUG - test_ipv4_advanced (__main__.TestFirewall.test_ipv4_advanced) ... ok
DEBUG - test_ipv4_basic_rules (__main__.TestFirewall.test_ipv4_basic_rules) ... ok
DEBUG - test_ipv4_mask (__main__.TestFirewall.test_ipv4_mask) ... ok
DEBUG - test_ipv4_state_and_status_rules (__main__.TestFirewall.test_ipv4_state_and_status_rules) ... ok
DEBUG - test_ipv6_advanced (__main__.TestFirewall.test_ipv6_advanced) ... ok
DEBUG - test_ipv6_basic_rules (__main__.TestFirewall.test_ipv6_basic_rules) ... ok
DEBUG - test_ipv6_mask (__main__.TestFirewall.test_ipv6_mask) ... ok
DEBUG - test_nested_groups (__main__.TestFirewall.test_nested_groups) ... ok
DEBUG - test_source_validation (__main__.TestFirewall.test_source_validation) ... ok
DEBUG - test_sysfs (__main__.TestFirewall.test_sysfs) ... ok
DEBUG -
DEBUG - ----------------------------------------------------------------------
DEBUG - Ran 14 tests in 58.245s
DEBUG -
DEBUG - OK
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by sever-sever — APPROVED** [review]

**Comment by nicolas-fort** [comment]
:+1: for this PR.
Although I wonder if migration script are needed

**Comment by sever-sever** [comment]
> 👍 for this PR. Although I wonder if migration script are needed

I guess the migration script is not required in this case. Offload was added recently.

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
> > 👍 for this PR. Although I wonder if migration script are needed
> 
> I guess the migration script is not required in this case. Offload was added recently.

Correct - just a small timewindow in a development release

**Comment by Apachez-** [comment]
Shouldnt software flowtable be enabled at all times by default (since software flowtable is supported by all nics) thus making only hardware flowtable needed to be set through config?

**Comment by fett0** [comment]
@c-po  @sarthurdev @sever-sever  Could we backport this feature 1.4 ? some customer asked for this capability, it would be nice if we can backport it.

**Pull request merged**
