### PR TITLE
openvpn: T4402: Update openvpn server.conf.j2

### PR DESCRIPTION
**Pull request by nagua**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T4402

## Component(s) name

- OpenVPN

## Proposed changes

- The ifconfig-pool command requires the arguments separated by a space. Hence the space was added before the subnetmask.

## How to test

Configure OpenVPN like this and make sure that the server is able to start.

```
    openvpn vtun0 {
        device-type tap
        local-port 1194
        mode server
        persistent-tunnel
        protocol udp
        server {
            client-ip-pool {
                start 10.0.0.0
                stop 10.0.0.255
                subnet-mask 255.255.255.0
            }
            topology subnet
        }
        tls {
            ca-certificate XXX
            certificate XXX
            tls-version-min 1.3
        }
    }

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — CHANGES_REQUESTED** [review]
The fix seems good, but please *do* read CONTRIBUTING.md and adjust the commit message and PR description accordingly. ;)

When commits are not linked to tasks in https://vyos.dev , it becomes really hard to track them and write release notes.

**Comment by nagua** [comment]
Hello @dmbaturin,

I search Phabricator and found an already open issue, that I used to link against that describes the error.
I tried to check if all bugs described in the ticket are fixed now but at least I could not find more.

I also amended my commit message. I hope that I have done everything correctly now. If there still is
something missing, please advice me.

Have a great day!

**Comment by nagua** [comment]
Looking at this again it would probably be better to upport (? opposite of backport) this PR to current #1309. Can you do that?

**Review by sever-sever — APPROVED** [review]

**Review by dmbaturin — APPROVED** [review]
Thanks, everything is in order now!

**Pull request merged**
