### PR TITLE
openvpn: T56: fix username/password authentication

### PR DESCRIPTION
**Pull request by yunzheng**
## Change Summary

Fixed bug where 'tls auth_file' was checked but this should be 'authentication' for username/password authentication.

If someone configured an openvpn client with username/password only it would not work as it will still check if 'tls cert-file' and 'tls key-file' are specified.

This change matches the older Perl script here: https://github.com/vyos/vyatta-openvpn/blob/current/lib/Vyatta/OpenVPN/Config.pm#L768

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T56

## Component(s) name

openvpn

## Proposed changes

Fix the check so openvpn username/password authentication only works again

## How to test

This was not allowed (but should):
```
set interfaces openvpn vtun1 mode client
set interfaces openvpn vtun1 remote-host 127.0.0.1
set interfaces openvpn vtun1 remote-port 1234
set interfaces openvpn vtun1 tls ca-cert-file /config/auth/vpn/ca.crt
set interfaces openvpn vtun1 authentication password 'y'
set interfaces openvpn vtun1 authentication username 'x'
```

After this patch it works.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Did you try running the smoketests lokally?

**Comment by yunzheng** [comment]
> Did you try running the smoketests lokally?

Had to figure out how to run them. Didn't know I could just check out the vyos-1x repo and run the tests locally from the smoketest dir. Will run the smoketests next time for my PRs now.

I'm not sure how to run the full suite but here is the output for `test_interfaces_openvpn.py`:

```
vyos@vyos# python3 test_interfaces_openvpn.py 
test_openvpn_client_interfaces (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_client_verify (__main__.TestInterfacesOpenVPN) ... 
Cannot specify "local-port" in client mode


Cannot specify "local-host" in client mode


Must specify "remote-host" in client mode


Must specify "remote-host" in client mode


Cannot specify "tls dh-file" in client mode


Must specify one of "shared-secret-key-file" and "tls"


Must specify "tls" for server and client mode


Password for authentication is missing

ok
test_openvpn_server_net30_topology (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_server_subnet_topology (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_server_verify (__main__.TestInterfacesOpenVPN) ... 
Must specify OpenVPN operation mode!


Protocol "tcp-active" is not valid in server mode


Cannot specify "remote-port" in server mode


Cannot specify "remote-host" in server mode


Must specify "server subnet" or add interface to bridge in server mode


Must specify "server subnet" or add interface to bridge in server mode


Must specify "tls ca-cert-file"


Cannot specify more than 1 IPv4 server subnet


Must specify "tls ca-cert-file"


Missing "tls cert-file"


Missing "tls key-file"


Cannot specify "tls role" in client-server mode


Cannot specify "tls dh-file" when "tls role" is "active"


Cannot specify "tcp-passive" when "tls role" is "active"


Cannot specify "tls dh-file" when "tls role" is "active"


Protocol "tcp-active" is not valid in server mode


Must specify "tls dh-file" when not using EC keys in server mode

ok
test_openvpn_site2site_interfaces_tun (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_site2site_verify (__main__.TestInterfacesOpenVPN) ... 
Must specify "local-address" or add interface to bridge


Must specify "local-address" or add interface to bridge


Only one IPv4 local-address can be specified


Only one IPv6 local-address can be specified


Must specify "remote-address"


Only one IPv4 remote-address can be specified


Only one IPv6 remote-address can be specified


Must specify one of "shared-secret-key-file" and "tls"

ok

----------------------------------------------------------------------
Ran 7 tests in 45.845s

OK
```

**Comment by c-po** [comment]
Please re-test with the latest changes in OpenVPN and PKI handling

**Comment by yunzheng** [comment]
is this change also for 1.3 branch or only 1.4?

**Comment by c-po** [comment]
1.4 only - please submit a dedicated PR for 1.3

**Pull request closed without merging**
