### PR TITLE
bonding: T2515: call 'interfaces-ethernet.py' for each interface that…

### PR DESCRIPTION
**Pull request by L6NqLW**
… leaves bond

### CODE REVIEW

**Comment by c-po** [comment]
Until today we lived with the design principle of not mixing Python scripts together and not calling them from each other - at least I'm not aware of any. We should keep this principle as there must be another way to fix this issue.

In my opinion the code for setting up interfaces is too fragmented at all as there is a lot of duplication here, too. We probably should once and for all migrate this to the object oriented pattern and handle everything - including setting the parameters on interfaces into the `ifconfig` package. Thus there is only one implementation dealing with all the interface stuff.

**Comment by jjakob** [comment]
@c-po is it decided who will do the migration? I imagine it'll be a lot of work. bridge member interfaces have the same problem.

**Comment by c-po** [comment]
Whoever signs up for it - I still have some tasks in the pipeline as of now - I can assist with concepts and ideas if you want.

**Comment by c-po** [comment]
As intermediate workaround until there is this new shiny implementation (again 😄) why not do the following:
- On bond deletion (check previous assigned members by calling `conf.return_effective_value()`
- Ask config backend about desired interface state (enabled/disabled)
- Get handle to interface (`EthernetIf()`) and set interface to up/down?

**Comment by jjakob** [comment]
The issue is other interface settings were also purged from it, not just state, that's why I suggested calling the whole interface script as a hacky workaround

**Comment by c-po** [comment]
This problem which comes and goes should be resolved once and forever with the implementation following on https://phabricator.vyos.net/T2653

**Comment by c-po** [comment]
Work on https://phabricator.vyos.net/T2653 is almost complete - closing this

**Pull request closed without merging**
