### PR TITLE
T5513: firewall: update op-mode command show firewall.

### PR DESCRIPTION
**Pull request by nicolas-fort**
## Change Summary

Update op-mode command show firewall

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5513
* https://vyos.dev/T5564
* https://vyos.dev/T5681

## Component(s) name

firewall, nat, nat66

## Proposed changes

Update op-mode command show firewall. Improvements:
 - Counters available for default actions
 - Group references now include search in nat and policy route|route6
 - Fix error for printing nat66 rules (error permisson)

 
## How to test

Config:
```
vyos@vyos:~$ show config comm | grep "firewall\|nat\|policy"
set firewall group address-group AG01 address '198.51.100.5'
set firewall group address-group AG01 address '192.0.2.66'
set firewall group interface-group IF01 interface 'bond99'
set firewall group port-group PG01 port '21'
set firewall group port-group PG01 port '23'
set firewall group port-group PG01 port '28'
set firewall ipv4 forward filter default-action 'drop'
set firewall ipv4 forward filter rule 10 action 'accept'
set firewall ipv4 forward filter rule 10 inbound-interface name 'eth3'
set firewall ipv4 forward filter rule 10 outbound-interface group 'IF01'
set firewall ipv4 forward filter rule 10 source group address-group 'AG01'
set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 10 action 'accept'
set firewall ipv4 input filter rule 10 inbound-interface name 'eth3'
set firewall ipv4 input filter rule 11 action 'accept'
set firewall ipv4 input filter rule 11 destination address '192.168.0.131'
set firewall ipv4 name BAR rule 77 action 'reject'
set firewall ipv4 name BAR rule 77 destination address '198.51.100.99'
set firewall ipv4 name BAR rule 77 inbound-interface group 'IF01'
set firewall ipv4 name BAR rule 88 action 'drop'
set firewall ipv4 name BAR rule 88 destination address '198.51.100.5'
set firewall ipv4 output filter rule 10 action 'accept'
set firewall ipv4 output filter rule 10 destination address '1.1.1.1'
set firewall ipv4 output filter rule 10 outbound-interface name 'eth0'
set firewall ipv4 output filter rule 12 action 'drop'
set firewall ipv4 output filter rule 12 destination address '8.8.8.8'
set firewall ipv4 output filter rule 15 action 'jump'
set firewall ipv4 output filter rule 15 destination address '198.51.100.0/24'
set firewall ipv4 output filter rule 15 jump-target 'BAR'
set firewall ipv4 output filter rule 15 protocol 'icmp'
set firewall ipv6 name FOO6 default-action 'accept'
set firewall ipv6 name FOO6 rule 199 action 'reject'
set firewall ipv6 name FOO6 rule 199 inbound-interface name '!vtun11'
set firewall ipv6 name FOO6 rule 199 outbound-interface group 'IF01'
set nat destination rule 10 inbound-interface name 'eth3'
set nat destination rule 10 source group address-group 'AG01'
set nat destination rule 10 translation address '198.51.100.1'
set nat destination rule 22 disable
set nat destination rule 22 inbound-interface group '!IF01'
set nat destination rule 22 translation address '203.0.113.113'
set nat source rule 20 destination group address-group '!AG01'
set nat source rule 20 outbound-interface group 'IF01'
set nat source rule 20 translation address '192.0.2.2'
set nat66 destination rule 10 inbound-interface name 'eth2'
set nat66 destination rule 10 translation address '2001:db8::1'
set nat66 source rule 10 outbound-interface name 'eth3'
set nat66 source rule 10 translation address '2001:db8::22'
set policy route FOO rule 101 action 'drop'
set policy route FOO rule 101 source group address-group 'AG01'
set policy route FOO rule 102 action 'accept'
set policy route FOO rule 102 destination group address-group '!AG01'
set policy route6 FOO6 rule 777 action 'accept'
set policy route6 FOO6 rule 777 destination group port-group 'PG01'
set policy route6 FOO6 rule 777 protocol 'tcp'
vyos@vyos:~$ 
```
op mode commands:
```
yos@vyos:~$ show firewall 
Rulesets Information

---------------------------------
ipv4 Firewall "forward filter"

Rule     Action    Protocol      Packets    Bytes  Conditions
-------  --------  ----------  ---------  -------  -------------------------------------------------------
10       accept    all                 0        0  ip saddr @A_AG01 iifname "eth3" oifname @I_IF01  accept
default  drop      all                 0        0

---------------------------------
ipv4 Firewall "input filter"

Rule     Action    Protocol      Packets    Bytes  Conditions
-------  --------  ----------  ---------  -------  ------------------------------
10       accept    all                 0        0  iifname "eth3"  accept
11       accept    all                 0        0  ip daddr 192.168.0.131  accept
default  accept    all               655   119249

---------------------------------
ipv4 Firewall "name BAR"

  Rule  Action    Protocol      Packets    Bytes  Conditions
------  --------  ----------  ---------  -------  --------------------------------------
    77  reject    all                 0        0  ip daddr 198.51.100.99 iifname @I_IF01
    88  drop      all                 3      252  ip daddr 198.51.100.5

---------------------------------
ipv4 Firewall "output filter"

Rule     Action    Protocol      Packets    Bytes  Conditions
-------  --------  ----------  ---------  -------  ---------------------------------------------------------
10       accept    all                 2      168  ip daddr 1.1.1.1 oifname "eth0"  accept
12       drop      all                 7      588  ip daddr 8.8.8.8
15       jump      icmp                8      672  meta l4proto icmp ip daddr 198.51.100.0/24  jump NAME_BAR
default  accept    all               391    66208

---------------------------------
ipv6 Firewall "name FOO6"

Rule     Action    Protocol      Packets    Bytes  Conditions
-------  --------  ----------  ---------  -------  -----------------------------------
199      reject    all                 0        0  iifname != "vtun11" oifname @I_IF01
default  accept    all                 0        0

vyos@vyos:~$ 
vyos@vyos:~$ show firewall statistics 
Rulesets Statistics

---------------------------------
ipv4 Firewall "forward filter"

Rule       Packets    Bytes  Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
10               0        0  accept    AG01      any            eth3                 IF01
default          0        0  drop      any       any            any                  any

---------------------------------
ipv4 Firewall "input filter"

Rule       Packets    Bytes  Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
10               0        0  accept    any       any            eth3                 any
11               0        0  accept    any       192.168.0.131  any                  any
default        672   120457  accept    any       any            any                  any

---------------------------------
ipv4 Firewall "name BAR"

  Rule    Packets    Bytes  Action    Source    Destination    Inbound-Interface    Outbound-interface
------  ---------  -------  --------  --------  -------------  -------------------  --------------------
    77          0        0  reject    any       198.51.100.99  IF01                 any
    88          3      252  drop      any       198.51.100.5   any                  any

---------------------------------
ipv4 Firewall "output filter"

Rule       Packets    Bytes  Action    Source    Destination      Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  ---------------  -------------------  --------------------
10               2      168  accept    any       1.1.1.1          any                  eth0
12               7      588  drop      any       8.8.8.8          any                  any
15               8      672  jump      any       198.51.100.0/24  any                  any
default        401    69536  accept    any       any              any                  any

---------------------------------
ipv6 Firewall "name FOO6"

Rule       Packets    Bytes  Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
199              0        0  reject    any       any            !vtun11              IF01
default          0        0  accept    any       any            any                  any

vyos@vyos:~$ 
vyos@vyos:~$ show firewall group 
Firewall Groups

Name    Type             References              Members
------  ---------------  ----------------------  ------------
AG01    address_group    ipv4-forward-filter-10  192.0.2.66
                         route-FOO-101           198.51.100.5
                         route-FOO-102
                         nat-source-20
                         nat-destination-10
IF01    interface_group  ipv4-name-BAR-77        bond99
                         ipv4-forward-filter-10
                         ipv6-name-FOO6-199
                         nat-source-20
                         nat-destination-22
PG01    port_group       route6-FOO6-777         21
                                                 23
                                                 28
vyos@vyos:~$ 
```
And nat66, with no error while printing rules:
```
vyos@vyos:~$ show nat66 destination  rules 
Rule    Source     Destination    Proto    In-Int    Translation
------  ---------  -------------  -------  --------  -------------
10      ::/0       ::/0           any      eth2      2001:db8::1
        sport any  dport any
vyos@vyos:~$ show nat66 source  rules 
Rule    Source     Destination    Proto    Out-Int    Translation
------  ---------  -------------  -------  ---------  -------------
10      ::/0       ::/0           any      eth3       2001:db8::22
        sport any  dport any
vyos@vyos:~$ 
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@nicolas-fort should this be backported to `sagitta` afterwards?

**Review by sarthurdev — APPROVED** [review]

**Comment by nicolas-fort** [comment]
> @nicolas-fort should this be backported to `sagitta` afterwards?

I guess this one https://github.com/vyos/vyos-1x/pull/2406 should be backported first

**Comment by nicolas-fort** [comment]
Now seems it's appropiate to backport this one

**Comment by sever-sever** [comment]
@Mergifyio backport sagitta

**Pull request merged**
