### PR TITLE
arping: T2715: Duplicate address detection option supporting ARP

### PR DESCRIPTION
**Pull request by jack9603301**

### CODE REVIEW

**Comment by jack9603301** [comment]
@c-po Request merge

**Comment by jack9603301** [comment]
Replace `send` with `discovery` because these tools are host information that can obtain MAC data by sending data, which can be regarded as an automatic discovery tool of host topology

**Comment by jack9603301** [comment]
@c-po I have changed the top-level command, maybe it's better, can you help me see it, if possible, request a merge, otherwise, please reply?

**Comment by c-po** [comment]
VyOS already supports a partial implementation for `arping` under the `force arp` command tree.

Please reuse the tree and add the missing features there. No need to introduce a new tree here. In addition our XML files use indent = 2 spaces.

**Comment by c-po** [comment]
Why is the `duplicate` node explicitly required? Couldn't this be mangled together with the interface? You also always state "gratuitous ARP" but your nodes are for DAD.

Please also avoid the reverse merge in your PR, please rebase to latest `current` which has the exact same outcome but drops the reverse merge.

**Comment by jack9603301** [comment]
@c-po 
> Couldn't this be mangled together with the interface?

I don't understand the meaning of this sentence

**Comment by jack9603301** [comment]
@c-po I don't understand the meaning of this sentence

> Couldn't this be mangled together with the interface?

**Pull request merged**
