### PR TITLE
igmp: T2156:[op-mode] Add clear for igmp/multicast

### PR DESCRIPTION
**Pull request by sever-sever**
Add commands for op-mode
```
clear ip igmp interfaces
clear ip multicast route
```

### CODE REVIEW

**Comment by elbandi** [comment]
there is a command naming convention mismatch: there are a "reset ip arp ..." and "reset ip route..." for clearing arp/route items. so this sould be like "reset ip igmp ..", . Or the arp/router sould be renamed to "clear ip ..." commands :/

**Comment by sever-sever** [comment]
@c-po  What would be the best solution?

**Comment by c-po** [comment]
+1 on @Elbandi, please rename to reset so it is consistent.

**Comment by sever-sever** [comment]
@Elbandi @c-po fixed. Thank's.

**Pull request merged**
