### PR TITLE
accel-ppp: T2917: Add Preallocate NAS-port-id

### PR DESCRIPTION
**Pull request by sever-sever**
Add attribute NAS-Port-Id in Access-Request

### CODE REVIEW

**Comment by c-po** [comment]
Hi @sever-sever,

`interface-definitions/include/radius-server.xml.i` is the wrong place as this include is used for every RADIUS implementation incl. `system login`

```
(12:40) cpo lnx01:~/vyos-1x [current] # git grep "include/radius-server.xml.i"
interface-definitions/interfaces-wireless.xml.in:                  #include <include/radius-server.xml.i>
interface-definitions/service_ipoe-server.xml.in:              #include <include/radius-server.xml.i>
interface-definitions/service_pppoe-server.xml.in:              #include <include/radius-server.xml.i>
interface-definitions/system-login.xml.in:          #include <include/radius-server.xml.i>
interface-definitions/vpn_l2tp.xml.in:                  #include <include/radius-server.xml.i>
interface-definitions/vpn_openconnect.xml.in:              #include <include/radius-server.xml.i>
interface-definitions/vpn_pptp.xml.in:                  #include <include/radius-server.xml.i>
interface-definitions/vpn_sstp.xml.in:              #include <include/radius-server.xml.i>
```

Please use `accel-radius-additions.xml.i`

**Comment by sever-sever** [comment]
@c-po done. But I see "conficting files"

**Comment by c-po** [comment]
Use git rebase

**Comment by c-po** [comment]
I have renamed some files in the include directory due to weo g file extension.

**Comment by c-po** [comment]
There is no need in closing a PR, you can always git push —force

**Comment by sever-sever** [comment]
I can't find what was wrong

```
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git status
On branch T2917
nothing to commit, working tree clean
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git rebase T2917
Current branch T2917 is up to date.
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git status
On branch T2917
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git rebase current
Current branch T2917 is up to date.
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git status
On branch T2917
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git commit --amend
[T2917 4dd1fa34] accel-ppp: T2917: Add Preallocate NAS-port-id
 Date: Sat Sep 26 09:09:19 2020 +0000
 3 files changed, 15 insertions(+)
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$
vyos_bld@36121ef1e379:/vyos/work/T2917/vyos-1x$ git push origin T2917 --force

```

After that the conflict still present in pr.
I add new PR for it https://github.com/vyos/vyos-1x/pull/553

**Comment by c-po** [comment]
I see no update of current branch to the github repo

**Pull request closed without merging**
