### PR TITLE
T626 Add tests for vyos-update-crontab and initial setup for sonarcloud

### PR DESCRIPTION
**Pull request by higebu**
Add unit tests for vyos-update-crontab.py.

### CODE REVIEW

**Comment by dmbaturin** [comment]
Good idea! One thing though: did you not use the testsuite and test runner APIs from the unitttest module on purpose?

**Comment by higebu** [comment]
@dmbaturin I added it, but it needs renaming the script.

BTW, why does `generate` function in vyos-update-crontab.py write actual crontab file rather than `apply` function?

**Comment by higebu** [comment]
@dmbaturin I understand about the `generate` function by reading the article you wrote. https://blog.vyos.net/vyos-development-digest-number-10

**Comment by higebu** [comment]
@dmbaturin I marged `conf_mode` and `validators` packages into `vyos` package for support sonar-scanner. What do you think about this? We can separate these packages to other directory, but directory path needs to be same as package path for mapping the coverage report to SonarCloud.

**Comment by higebu** [comment]
@dmbaturin Finally, I can support both testsuite ant unitttest.main. We can see the coverage on https://sonarcloud.io/component_measures?id=vyos%3Avyos-1x&metric=coverage

**Pull request merged**
