### PR TITLE
T3508, T3356: remote: Friendly download procedure for user-facing scripts

### PR DESCRIPTION
**Pull request by erkin**
## Change Summary

This commit introduces a `friendly_download()` to be used in interactive scripts (mainly `install-image`). See: vyos/vyatta-cfg-system#146.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3356
* https://phabricator.vyos.net/T3508

## Component(s) name

remote

## Proposed changes

`friendly_download()` checks the file size in advance before downloading and compares it against the available storage and prints errors without the lengthy stack trace.

## How to test

Mostly intended to be called from scripts but it can be used directly like
```
> vyos.remote.friendly_download('/tmp/foobar', 'ftp://ftp.example.net/foobar', authentication=('username', 'password'))
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — COMMENTED** [review]
As I mentioned in the other PR, I'm concerned about passing plaintext passwords as process arguments since it may end up visible in `ps`. The AWS SDK and similar projects usually pass sensitive data in environment variables.

**Comment by erkin** [comment]
That's a good point, especially considering the process runs for a nontrivial time. Converted to draft for the time being.

**Comment by erkin** [comment]
It's also trivial to get environment variables out of a running process.
```
% PASSWORD=swordfish sleep 500 &
% strings /proc/$(pgrep sleep)/environ | grep PASSWORD
PASSWORD=swordfish
```
Better than passing it directly though.

Edit: Ah, wait, default user has no permissions for that. All right, it is decided then.

**Comment by c-po** [comment]
When uploading/downloading data, can't the Python3 requests library be used to setup a session which hold credentials?

**Comment by dmbaturin** [comment]
@c-po Since the code supports multiple protocols and thus uses multiple unrelated libraries apart from `requests`, a mechanism unique to `requests` is of little help in the big picture.

**Comment by erkin** [comment]
`requests` would be helpful with authentication (which we handle by installing a password manager each time we do HTTP authentication, which is only somewhat better than manually adding the HTTP header) and would give us a non-painful way to do HTTP uploading (which is a would-be-nice feature). I opted to rely on `urllib.request` alone for the time being to avoid adding another dependency. (Speaking of which, `urllib.request` has a superficial FTP support so it might be a good idea to migrate the FTP implementation from `ftplib` to `urllib.request` for the sake of uniformity.)

The current pain point with what we have so far is the lack of a progress bar to replace `curl`'s, which is rather painful to do manually across different protocols. The user installing a new image has no feedback from the system about the progress of the download.

**Comment by c-po** [comment]
As https://github.com/vyos/vyatta-cfg-system/pull/146 was merged early we also need to merge this. Any changes to authentication should be added in a subsequent PR. Sorry for the trouble

**Pull request merged**
