### PR TITLE
T5497: op-mode: Add generate firewall rule-resequence

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add op-mode command `generate firewall rule-resequence` 
Generates output with new sequences for firewall rules
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5497
* https://vyos.dev/T4624

## Component(s) name

firewall, op--mode
## How to test
VyOS configuration:
```
set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 1 action 'accept'
set firewall ipv4 input filter rule 1 description 'Allow loopback'
set firewall ipv4 input filter rule 1 inbound-interface interface-name 'lo'
set firewall ipv4 input filter rule 1 source address '127.0.0.0/8'
set firewall ipv4 input filter rule 2 action 'accept'
set firewall ipv4 input filter rule 2 description 'Allow established/related'
set firewall ipv4 input filter rule 2 state established 'enable'
set firewall ipv4 input filter rule 2 state related 'enable'
set firewall ipv4 input filter rule 60 action 'accept'
set firewall ipv4 input filter rule 60 description 'Allow SSH from trusted networks'
set firewall ipv4 input filter rule 60 destination port '22'
set firewall ipv4 input filter rule 60 protocol 'tcp'
set firewall ipv4 input filter rule 10000 action 'drop'
set firewall ipv4 input filter rule 10000 description 'Drop everything else'

```
Produce op-mode commands (just output  with first sequence 10 and step between rules 10
```
vyos@r4:~$ generate firewall rule-resequence start 10 step 10

set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 10 action 'accept'
set firewall ipv4 input filter rule 10 description 'Allow loopback'
set firewall ipv4 input filter rule 10 inbound-interface interface-name 'lo'
set firewall ipv4 input filter rule 10 source address '127.0.0.0/8'
set firewall ipv4 input filter rule 20 action 'accept'
set firewall ipv4 input filter rule 20 description 'Allow established/related'
set firewall ipv4 input filter rule 20 state established 'enable'
set firewall ipv4 input filter rule 20 state related 'enable'
set firewall ipv4 input filter rule 30 action 'accept'
set firewall ipv4 input filter rule 30 description 'Allow SSH from trusted networks'
set firewall ipv4 input filter rule 30 destination port '22'
set firewall ipv4 input filter rule 30 protocol 'tcp'
set firewall ipv4 input filter rule 40 action 'drop'
set firewall ipv4 input filter rule 40 description 'Drop everything else'



vyos@r4:~$ 

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
`produce` would be a new top level tree in the op-mode CLI.

Any reason to not move this under `generate`?

**Comment by sever-sever** [comment]
> `produce` would be a new top level tree in the op-mode CLI.
> 
> Any reason to not move this under `generate`?

Regarding this task https://vyos.dev/T4624 it should be produce

**Review by c-po — APPROVED** [review]

**Comment by sever-sever** [comment]
@c-po rewritten to `generate`

**Comment by sarthurdev** [comment]
Wonder if this could be extended to work like the `generate pki ... install` functions? Output command strings when called directly from op-mode, but when called in conf mode it will perform operations in the session. (See https://github.com/vyos/vyos-1x/blob/current/python/vyos/utils/misc.py#L30)

In this context, the conf mode call could replace the specified section, awaiting the user to verify the new syntax using `compare` and committing if they're happy with it.

**Comment by sever-sever** [comment]
> Wonder if this could be extended to work like the `generate pki ... install` functions? Output command strings when called directly from op-mode, but when called in conf mode it will perform operations in the session. (See https://github.com/vyos/vyos-1x/blob/current/python/vyos/utils/misc.py#L30)
> 
> In this context, the conf mode call could replace the specified section, awaiting the user to verify the new syntax using `compare` and committing if they're happy with it.

In this case, we should delete the old firewall rules and add new, or we'll get mixed sequences (1 and 10, 2 and 20, etc).
I'd prefer only to generate and paste it manually, at least as a first step. I didn't test complex configurations, so there could be something wrong ;)

**Review by dmbaturin — APPROVED** [review]
The lines between `produce` and `generate` are so blurry now that I'm inclined to say we should just use `generate` now for every command that generates anything.

**Comment by sever-sever** [comment]
@Mergifyio backport sagitta

**Pull request merged**
