### PR TITLE
T574: Add new style scripts and definitions for system host-name

### PR DESCRIPTION
**Pull request by jbrodriguez**
A first attempt at an interface definition.

A couple of questions.

I guess the node name must be 'host-name' (instead of hostname) for backwards compatibility, right ?

What is the convention for the script filenames:

- vyos-config-host-name.py
- vyos-config-hostname.py
- vyos-hostname.py

?

Who is writing the python script ?

### CODE REVIEW

**Comment by dmbaturin** [comment]
Hi Juan, thanks for your interest in the new style rewrites! Generally, the person who writes the definitions also writes the scripts.
Our development process is to first create a task in phabricator. Else, with this number of submodules we have, we'll be having very hard time producing release notes. I've created the task for you since you are new here, let's continue the discussion there: https://phabricator.vyos.net/T574
You can either register an account or login with github oauth.

**Comment by dmbaturin** [comment]
I'm going to change some things, but the foundation is good I think, let's merge this and work from there.

**Comment by dmbaturin** [comment]
Ok, I've paid my price for the sloppy code review, but next time please try to actually run your code before submitting pull requests. ;)

**Comment by jbrodriguez** [comment]
Yeah, guilty as charged.

I didn't test it, since I didn't figure out how.

But I now see some tests were added, that definitely helps.

**Comment by dmbaturin** [comment]
You can build the package (debuild -us -uc), install it on a live system with dpkg -i and try it out. Before the recent development that allowed us to start adding tests, it was the only way to test anything. :)

**Pull request merged**
