### PR TITLE
T4997: add dhcp client user hooks

### PR DESCRIPTION
**Pull request by b-**
## Change Summary
add dhcp client user hooks

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T4997

## Component(s) name

dhcp

## Proposed changes

add `/config/scripts/dhcp-client/post-hooks.d/` that runs scripts upon renewing a DHCP lease a la `/config/scripts/commit/post-hooks.d/`

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [ ] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by b-** [comment]
Okay, I tested it on my router and it works

**Comment by c-po** [comment]
HI @b-,

thanks for the contribution. Looks like you fast-forwarded through the [CONTRIBUTING](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) section. The commit should get a proper commit message/headline as explained there.

I think the feature addresses a corner-case and thus should be merged. Can you please also provide [DOCUMENTATION](https://github.com/vyos/vyos-documentation) for it?

**Comment by b-** [comment]
> HI @b-,
> 
> thanks for the contribution. Looks like you fast-forwarded through the [CONTRIBUTING](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) section. The commit should get a proper commit message/headline as explained there.
> 
> I think the feature addresses a corner-case and thus should be merged. Can you please also provide [DOCUMENTATION](https://github.com/vyos/vyos-documentation) for it?

Absolutely! How is my updated commit message?

I'm having trouble figuring out where in the docs I'd put this. I couldn't find any general "DHCP client" documentation, but on the other hand it might fit better in https://docs.vyos.io/en/equuleus/automation/command-scripting.html#executing-pre-hooks-post-hooks-scripts especially since I based this off that feature. What do you think? Maybe I should just add a section in that document?

**Comment by b-** [comment]
By the way, I'm not sure what, if anything, I should do about the "Check pull request message format…" check. I read https://github.com/vyos/vyos-1x/blob/current/scripts/check-pr-title-and-commit-messages.py and I think I formatted my commit message the way it would like now, but it seems that it doesn't see the updated commit message when I run it locally. 

(I don't see the "re-run all checks" button, so I assume my Github account doesn't have access to it, but running the script locally gives the same output as above anyway before I updated the commit message)

**Comment by sever-sever** [comment]
Check commit
Your commit [message](https://github.com/vyos/vyos-1x/pull/1810/commits) `add dhcp client user hooks` but expected `T4997: add dhcp client user hooks`
```
To make this approach work, every change must be associated with a task number (prefixed with T) and a component.
```

**Comment by b-** [comment]
> Check commit Your commit [message](https://github.com/vyos/vyos-1x/pull/1810/commits) `add dhcp client user hooks` but expected `T4997: add dhcp client user hooks`
> 
> ```
> To make this approach work, every change must be associated with a task number (prefixed with T) and a component.
> ```

Cool, got it! I thought that `git push --force` an amended commit would update the PR and github web UI, but it turns out that's not enough. The command to properly force push such an update is `git push --force-with-lease origin branch-name`(https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message)

**Comment by c-po** [comment]
> I'm having [trouble](https://vyos.dev/Trouble) figuring out where in [the](https://vyos.dev/The) docs I'd put [this](https://vyos.dev/This). I couldn't find any general "DHCP client" documentation, but on [the](https://vyos.dev/The) other hand it might fit better in https://docs.vyos.io/en/equuleus/automation/command-scripting.html#executing-pre-hooks-post-hooks-scripts especially since I based [this](https://vyos.dev/This) off [that](https://vyos.dev/That) feature. What do you [think](https://vyos.dev/Think)? Maybe I should just add a section in [that](https://vyos.dev/That) document?

I'd add it to every instance of a DHCP address on an interface - thus it's included in all appropriate places.
https://github.com/vyos/vyos-documentation/blob/master/docs/_include/interface-address-with-dhcp.txt

**Comment by meestark** [comment]
Could this also get paired with pre-hooks as well?  I think of it as an enter and exit hook for dhcpcd

**Comment by c-po** [comment]
> Could this also get paired with pre-hooks as well? I think of it as an enter and exit hook for dhcpcd

@b- what you think?

**Comment by b-** [comment]
Sorry, I've been busy! I also had a little trouble spinning the docs repo up and kind of dropped that…

But I just now copied the file from this PR to make a pre-hooks file. I didn't test this part at all, but I'll be really surprised if it _doesn't_ work because I'm following the manual at https://www.daemon-systems.org/man/dhcpcd-run-hooks.8.html

**Comment by b-** [comment]
I feel really silly asking, but if there's any way someone could help me write the documentation I'd really appreciate it. It's honestly a little intimidating :(

But the gist of how this works is the same as (and modeled after) https://docs.vyos.io/en/equuleus/automation/command-scripting.html#executing-pre-hooks-post-hooks-scripts. That is, put a script in /config/scripts/dhcp/pre-hooks.d or /config/scripts/dhcp/post-hooks.d with the same filename constraints as mentioned in the docs for commit hooks 

> Scripts are run in alphabetical order. Their names must consist entirely of ASCII upper- and lower-case letters,ASCII digits, ASCII underscores, and ASCII minus-hyphens.No other characters are allowed.

The canonical manual for writing these scripts lives in https://kb.isc.org/docs/isc-dhcp-41-manual-pages-dhclient-script and there's an example installed by the isc-dhcp-client package in in /etc/dhcp/dhclient-exit-hooks.d/debug (this is a copy of the file found from google, since it's not in this vyos-1x repo and I'm not sure where the vyos package lives or if it just uses the debian one: https://www.apt-browse.org/browse/ubuntu/trusty/main/amd64/isc-dhcp-client/4.2.4-7ubuntu12/file/etc/dhcp/dhclient-exit-hooks.d/debug)

**Review by c-po — APPROVED** [review]

**Pull request merged**
