### PR TITLE
op-mode: T2791: Add monitor traceroute explicit for ipv4-ipv6 and vrf

### PR DESCRIPTION
**Pull request by sever-sever**
Add trace feature for ipv4 ipv6 vrf
```
vyos@r4-roll:~$ monitor traceroute 
Possible completions:
  <hostname>    Monitor path to destination in realtime
  <x.x.x.x>
  <h:h:h:h:h:h:h:h>
  ipv4          IPv4 fully qualified domain name (FQDN)
  ipv6          IPv6 fully qualified domain name (FQDN)
  vrf           Monitor path to destination in realtime via given VRF

```

### CODE REVIEW

**Comment by jack9603301** [comment]
https://github.com/vyos/vyos-1x/blob/57aad3a59f9f50d44702cca96a8b6069256caf5e/op-mode-definitions/traceroute.xml#L155-L192

I feel that your implementation is duplicated with the following code

**Comment by jack9603301** [comment]
If possible, code should be added to the above file

**Comment by c-po** [comment]
@sever-sever please merge your changes into `op-mode-definitions/traceroute.xml`

**Comment by sever-sever** [comment]
> @sever-sever please merge your changes into `op-mode-definitions/traceroute.xml`

@c-po Done.

**Pull request merged**
