### PR TITLE
graphql: T4640: add schema defs and resolver support for op-mode errors

### PR DESCRIPTION
**Pull request by jestabro**
## Change Summary

Updated based on comments below and discussion in dev meeting:

This PR integrates the op-mode script exception hierarchy into the GraphQL API. Op-mode errors are reported to the client in the form:

```
"op_mode_error": {
    "name": str
    "message": str
    "vyos_code": int
}
```

The error codes are from the document:
https://docs.google.com/document/d/1XPMCbid3O_R-6ITi4NpiWFoo2QqHMXYnCSeUzvOgOtA

The schema entity OpModeError is of interface type, with the specific errors implementing the type; consequently, queries need only a simple addition to return error information, yet it is possible to include extra error-specific fields should that be needed in the future. Example below.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4640

## Component(s) name

http-api

## How to test

One can test this using the file 'dummy.py', a mock standardized op-mode script that will raise an error given a non-zero int argument 1--3:
https://github.com/jestabro/vyos-1x/blob/gql-op-mode-errors-single-type/src/op_mode/dummy.py

If one adds that to the 'op-mode-standardized.json' file and restarts vyos-http-api, a query such as:

```
query {ShowDummy (data: {key:"qwerty", trigger: 1}) {
  success
  errors
  op_mode_error {
    name
    message
    vyos_code
  }
  data {
    result
  }
}}
```
will return:

```
{
  "data": {
    "ShowDummy": {
      "success": false,
      "errors": [
        "op_mode_error"
      ],
      "op_mode_error": {
        "name": "UnconfiguredSubsystem",
        "message": "subsystem is not configured or not running",
        "vyos_code": 2000
      },
      "data": null
    }
  }
}
```

The equivalent curl command is, for example,

`curl -k --raw 'https://192.168.122.188/graphql' -H 'Content-Type: application/json' -d '{"query":" {\n ShowDummy (data: {key: \"qwerty\", trigger: 1}) {\n success\n errors\n op_mode_error {name, message, vyos_code}\n data {\n result\n }\n}\n}\n"}' | jq
`

The OpModeError implementation has been included in the script that generates schema definitions, such that, upon adding new errors, one will only need to update the dicts containing the field information, {message, codes}, or default to placeholder values.

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [X] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
```
 
      "success": false,
      "errors": null,

```      
Is it a real example? Success false shouldn’t shows the error?

**Comment by jestabro** [comment]
There are two diffierent notion of error: general errors, and op_mode_errors --- on 'success: false', one or the other will be non-null.

**Comment by jestabro** [comment]
For example, use an incorrect key in the above example; then:
```
{
  "data": {
    "ShowDummy": {
      "success": false,
      "errors": [
        "invalid API key"
      ],
      "opmode_error": null,
      "data": null
    }
  }
}
```

**Comment by jestabro** [comment]
We can consider changing the field name to make this clear; I would prefer that to be a separate commit, however.

**Comment by jestabro** [comment]
One reasonable approach is to leave the field 'errors' as the site of general errors, as they are not necessarily categorized as server/request/client, and simply list the type, resulting in:
```
{
  "data": {
    "ShowDummy": {
      "success": false,
      "errors": [
        "opmode_error"
      ],
      "opmode_error": {
        "name": "UnconfiguredSubsystem",
        "message": "subsystem is not configured or not running",
        "status_code": 422,
        "vyos_code": 2000
      },
      "data": null
    }
  }
}
```

**Review by dmbaturin — APPROVED** [review]

**Review by sever-sever — APPROVED** [review]

**Pull request merged**
