### PR TITLE
ddclient: T4743: Add option for IPv6 Dynamic DNS

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Allow to use IPv6 for service Dynamic DNS

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4743

## Component(s) name

ddclient
## How to test
```
set service dns dynamic interface eth2 ipv6-enable
set service dns dynamic interface eth2 service dynv6 host-name 'xxx.dynv6.net'
set service dns dynamic interface eth2 service dynv6 login 'none'
set service dns dynamic interface eth2 service dynv6 password 'passWorD'
set service dns dynamic interface eth2 service dynv6 protocol 'dyndns2'
set service dns dynamic interface eth2 service dynv6 server 'dynv6.com'

```

Check
Expected `usev6`
```
vyos@r1:~$ sudo cat /run/ddclient/ddclient.conf | grep usev6
usev6=if, if=eth2
```
Start ddclient:
```
vyos@r1:~$ sudo /usr/sbin/ddclient  -pid /run/ddclient/ddclient.pid -file /run/ddclient/ddclient.conf --foreground
SUCCESS:  updating xxx.dynv6.net: good: IP address set to xx:xxx:xx:4xx::11e
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Review by jestabro — APPROVED** [review]

**Comment by loafbread** [comment]
It seems that this feature replaces the 'use=if' with 'usev6=if' in the /run/ddclient/ddclient.conf file.  I hoped to set an IPv4 and an IPv6 dynamic DNS name on the same interface.  This feature appears to prevent setting an IPv4 address because it replaces the 'use=if' setting.

Testing on: 1.4-rolling-202211110728

**Comment by sever-sever** [comment]
> It seems that this feature replaces the 'use=if' with 'usev6=if' in the /run/ddclient/ddclient.conf file. I hoped to set an IPv4 and an IPv6 dynamic DNS name on the same interface. This feature appears to prevent setting an IPv4 address because it replaces the 'use=if' setting.
> 
> Testing on: 1.4-rolling-202211110728

let  us know if you know the configuration of how to get them working together

**Comment by loafbread** [comment]
I have not been able to get both  'use=if' with 'usev6=if' to work in the same ddclient.conf file.  My work around is to run another instance of ddclient for IPv6.

**Comment by c-po** [comment]
Maybe we can detect that and spawn two instances

**Pull request merged**
