### PR TITLE
snmp: T1881: Change permission for script files

### PR DESCRIPTION
**Pull request by sever-sever**
Change chmod permissions for function verify(snmp) in file  src/conf_mode/snmp.py

### CODE REVIEW

**Review by c-po — CHANGES_REQUESTED** [review]
Please follow the precious pattern and use S_IROTH only

**Comment by ghost** [comment]
> Please follow the precious pattern and use S_IROTH only

Why not add S_IRGRP too?

**Comment by c-po** [comment]
Why close this? Just use git push —force

**Comment by sever-sever** [comment]
> Why close this? Just use git push —force

I'm just starting out with "git". I don’t know much.

**Pull request closed without merging**
