### PR TITLE
dns: T5959: Streamline dns forwarding service

### PR DESCRIPTION
**Pull request by indrajitr**
## Change Summary

Streamline configuration and operation of dns forwarding service in following ways:
 
- Rename `dns.py` to `dns_forwarding.py` to better align with the operation mode path for the service
- Remove `dns_forwarding_reset.py` as its functionality is now covered by `dns_forwarding.py`
- Remove `dns_forwarding_restart.sh` as its functionality is inlined in
  `dns-forwarding.xml`
- Templatize systemd override for `pdns-recursor.service` and move the generated override files in /run. This ensures that the override files are always generated afresh after boot
- Simplify the systemd override file by removing the redundant overrides
- Relocate configuration path for pdns-recursor to `/run/pdns-recursor` and utilize the `RuntimeDirectory` default that pdns-recursor expects
- We do not need to use custom `--socket-dir` path anymore, the default path (viz., `/run/pdns-recursor` is fine)
- Remove unnecessary dns forwarding statistics script (leftover from #1446)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5959
* https://vyos.dev/T4578

## Component(s) name

dns forwarding

## Smoketest result

```
vyos@v15-0119:~$ /usr/libexec/vyos/tests/smoke/cli/test_service_dns_forwarding.py 
test_basic_forwarding (__main__.TestServicePowerDNS.test_basic_forwarding) ... 
DNS forwarding requires a listen-address


DNS forwarding requires a listen-address

ok
test_dns64 (__main__.TestServicePowerDNS.test_dns64) ... 
DNS 6to4 prefix must be of length /96

ok
test_dnssec (__main__.TestServicePowerDNS.test_dnssec) ... ok
test_domain_forwarding (__main__.TestServicePowerDNS.test_domain_forwarding) ... ok
test_exclude_throttle_adress (__main__.TestServicePowerDNS.test_exclude_throttle_adress) ... ok
test_external_nameserver (__main__.TestServicePowerDNS.test_external_nameserver) ... ok
test_listening_port (__main__.TestServicePowerDNS.test_listening_port) ... ok
test_no_rfc1918_forwarding (__main__.TestServicePowerDNS.test_no_rfc1918_forwarding) ... ok
test_serve_stale_extension (__main__.TestServicePowerDNS.test_serve_stale_extension) ... ok

----------------------------------------------------------------------
Ran 9 tests in 254.394s

OK

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Do not rename op-mode script from dns.py to dns_forwarding.py as it used for Graphql queries 
As you can see there are shot names for those scripts without any dashes/underscores

**Comment by indrajitr** [comment]
> Do not rename op-mode script from dns.py to dns_forwarding.py as it used for Graphql queries As you can see there are shot names for those scripts without any dashes/underscores

I see! In that case, what would be the recommended approach for op-mode script for `dns dynamic`? Should that also go under `dns.py`?

Edit: Also, I can see `config_mgmt.py` referred in `op-mode-standardized.json`. I guess that's special in some way.

**Comment by c-po** [comment]
Please keep `dns.py` as with the API there is some sort of "magic" like: `show dns` means, use `dns.py` script and pass the arguments verbatim to it. @jestabro can help with the details e.g. about `config_mgmt.py`.

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
