### PR TITLE
validators: T2578: Valdiation for prefix 31

### PR DESCRIPTION
**Pull request by sever-sever**
192.0.2.8/31 its "network" and "address" at the same time
```
Network:   192.0.2.8/31         11000000.00000000.00000010.0000100 0
HostMin:   192.0.2.8            11000000.00000000.00000010.0000100 0
HostMax:   192.0.2.9            11000000.00000000.00000010.0000100 1

```
That fix allow set IP address with prefix /31 to interfaces

### CODE REVIEW

**Comment by c-po** [comment]
The `ip-host` validator is used for both IPv4 and IPv6 checks. Your PR now mixes IPv4 and IPv6 checks. `ipv4-host` is the validator which should be workarounded until there is a solution in `ipaddrcheck` or `libcidr` - whoever is the root-cause of this problem.

**Comment by dmbaturin** [comment]
I'm going to add a special case to ipaddrcheck.

**Comment by pimvanpelt** [comment]
Stumbled across this as I had intended to make wireguard and ethernet transit networks that are /31 in size.

I had updated `/usr/libexec/vyos/validators/ip-host` to simply call `ipaddrcheck --is-valid`. Any reason why you'd choose this special case ?

I'm unfamiliar with vyos rolling releases and how they rollup from github. Can you let me know if this will show up in a rolling daily or if I should keep a patchset for myself ?

**Comment by c-po** [comment]
@pimvanpelt it is already part of the latest rolling releases. We build an ISO at least once a day from the latest binary packages. On ever push to one of the repos the binary package is build automatically.

The issue was fixed directly in ipaddrcheck instead of having a workaround.

**Comment by pimvanpelt** [comment]
Gotcha, I didn't see that fix in ipaddrcheck, and was looking for the PR @sever-sever had submitted.

But thanks to your hint, I can confirm I'm in a good shape:

```
pim@vyos-test0:/usr/lib/live/mount/rootfs/1.3-rolling-202006120643.squashfs$ cat usr/libexec/vyos/validators/ip-host 
#!/bin/sh

ipaddrcheck --is-any-host $1
pim@vyos-test0:/usr/lib/live/mount/rootfs/1.3-rolling-202006120643.squashfs$ ipaddrcheck --is-any-host 10.0.0.1/31 && echo "valid"
valid
pim@vyos-test0:/usr/lib/live/mount/rootfs/1.3-rolling-202006120643.squashfs$ ipaddrcheck --is-any-host 10.0.0.0/31 && echo "valid"
valid
```

Thanks! IPv4 preservationists around the world are grateful =)

**Pull request closed without merging**
