### PR TITLE
smoketest: T3526: Add seq x for policy tests

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add 'seq x' for smoketest policy
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3526

## Component(s) name

smoketest, policy
## Proposed changes

It tried to find 
```
bgp community-list 100 permit .*
```
In config
```
'bgp community-list 100 seq 5 permit .*\nbgp community-list 200 seq 5 deny ^1:201$\nbgp community-list 200 seq 10 deny 1:101$\nbgp community-list 200 seq 15 deny ^1:100$\n!'
```
And get fail.
```
07:19:12  DEBUG - test_community_list (__main__.TestPolicy) ... FAIL
07:19:19  DEBUG - test_extended_community_list (__main__.TestPolicy) ... FAIL
07:19:27  DEBUG - test_large_community_list (__main__.TestPolicy) ... FAIL
07:19:32  DEBUG - test_prefix_list (__main__.TestPolicy) ... ok
07:19:39  DEBUG - test_prefix_list6 (__main__.TestPolicy) ... ok
07:19:39  DEBUG - 
07:19:39  DEBUG - ======================================================================
07:19:39  DEBUG - FAIL: test_community_list (__main__.TestPolicy)
07:19:39  DEBUG - ----------------------------------------------------------------------
07:19:39  DEBUG - Traceback (most recent call last):
07:19:39  DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_policy.py", line 382, in test_community_list
07:19:39  DEBUG -     self.assertIn(tmp, config)
07:19:39  DEBUG - AssertionError: 'bgp community-list 100 permit .*' not found in 'bgp community-list 100 seq 5 permit .*\nbgp community-list 200 seq 5 deny ^1:201$\nbgp community-list 200 seq 10 deny 1:101$\nbgp community-list 200 seq 15 deny ^1:100$\n!'
```

Set  'seq x'
## How to test
```
vyos@r4-1.3:~$ /usr/libexec/vyos/tests/smoke/cli/test_policy.py
test_access_list (__main__.TestPolicy) ... ok
test_access_list6 (__main__.TestPolicy) ... ok
test_as_path_list (__main__.TestPolicy) ... ok
test_community_list (__main__.TestPolicy) ... ok
test_extended_community_list (__main__.TestPolicy) ... ok
test_large_community_list (__main__.TestPolicy) ... ok
test_prefix_list (__main__.TestPolicy) ... ok
test_prefix_list6 (__main__.TestPolicy) ... ok

----------------------------------------------------------------------
Ran 8 tests in 23.244s

OK

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — CHANGES_REQUESTED** [review]
VyOS 1.3 uses a "fixed" sequence scheme with a fixed increment.

The increment should be honored in the testcase. Starting with VyOS 1.4 the sequence number will match the rule-set number specified on VyOS CLI.

**Comment by sever-sever** [comment]
> VyOS 1.3 uses a "fixed" sequence scheme with a fixed increment.

Frr 7.3.1 don't use any seq by default in its own configuration
```
!
bgp community-list 100 permit 11:121
bgp community-list 100 permit 22:222
bgp community-list 100 permit 33:323
bgp community-list 100 deny .*
!
```
FRR 7.5.1. use seq by default even if you send the values without any "seq"
```
!
bgp community-list 100 seq 1 permit 11:121
bgp community-list 100 seq 2 permit 22:222
bgp community-list 100 seq 3 permit 33:323
bgp community-list 100 seq 4 deny .*
bgp extcommunity-list expanded FFF seq 2 permit 44:22:22
bgp extcommunity-list expanded FFF seq 10 permit 44:55:33
!
```

The main problem in this test it is not mismatched 'rules' and 'seq'.
The main problem that is trying to find pattern without seq in values with 'seq'
```
07:19:39  DEBUG - AssertionError: 'bgp community-list 100 permit .*' not found in 'bgp community-list 100 seq 5 permit .*\nbgp community-list 200 seq 5 deny ^1:201$\nbgp community-list 200 seq 10 deny 1:101$\nbgp community-list 200 seq 15 deny ^1:100$\n!'
```

**Comment by c-po** [comment]
Do we still need this PR after your change to vyatta-cfg-quagga?

**Comment by sever-sever** [comment]
> Do we still need this PR after your change to vyatta-cfg-quagga?

In Build (May 9, 2021) the problem still present

```
16:10:47  DEBUG - AssertionError: 'bgp community-list 100 permit .*' not found in 'bgp community-list 100 seq 4 permit .*\nbgp community-list 200 seq 1 deny ^1:201$\nbgp community-list 200 seq 2 deny 1:101$\nbgp community-list 200 seq 3 deny ^1:100$\n!'
```

**Pull request merged**
