### PR TITLE
T6056: Change static-host-mapping should not restart snmpd

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

We have several config XML definitions that use the same python3 script `system_host-name.py`

https://github.com/vyos/vyos-1x/blob/current/interface-definitions/system_name-server.xml.in
https://github.com/vyos/vyos-1x/blob/current/interface-definitions/system_host-name.xml.in 
https://github.com/vyos/vyos-1x/blob/current/interface-definitions/system_static-host-mapping.xml.in
https://github.com/vyos/vyos-1x/blob/current/interface-definitions/system_domain-name.xml.in 
https://github.com/vyos/vyos-1x/blob/current/interface-definitions/system_domain-search.xml.in

Any change in these scripts calls to restart the `service snmpd`.
The service `snmpd` should be restarted only if `host-name` or `domain-name` was changed.

It is a good idea to rewrite it to `get_config_dict` in the future.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

 * https://vyos.dev/T6056

## Component(s) name

system
## How to test
Add static-host-mapping:
```
set system static-host-mapping host-name foo.local inet '192.0.2.1'
```
It leads to unexpected restarting service snmpd:
```
May 01 15:00:50 r4 vyos-hostsd[748]: Success
May 01 15:00:50 r4 vyos-hostsd[748]: Saving state to /run/vyos-hostsd/vyos-hostsd.state
May 01 15:00:50 r4 vyos-hostsd[748]: Sent response: {'data': {'message': 'Applied 7 changes'}}
May 01 15:00:50 foo systemd-hostnamed[88276]: Hostname set to <foo> (static)
May 01 15:00:50 foo systemd[1]: Stopping rsyslog.service - System Logging Service...
May 01 15:00:50 foo rsyslogd[88284]: [origin software="rsyslogd" swVersion="8.2302.0" x-pid="88284" x-info="https://www.rsyslog.com"] exiting on signal 15.
May 01 15:00:50 foo systemd[1]: rsyslog.service: Deactivated successfully.
May 01 15:00:50 foo systemd[1]: Stopped rsyslog.service - System Logging Service.
May 01 15:00:50 foo systemd[1]: Starting rsyslog.service - System Logging Service...
May 01 15:00:50 foo rsyslogd[88366]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.2302.0]
May 01 15:00:50 foo systemd[1]: Started rsyslog.service - System Logging Service.
May 01 15:00:50 foo rsyslogd[88366]: [origin software="rsyslogd" swVersion="8.2302.0" x-pid="88366" x-info="https://www.rsyslog.com"] start
May 01 15:00:50 foo systemd[1]: Stopping snmpd.service - Simple Network Management Protocol (SNMP) Daemon....
May 01 15:00:50 foo systemd[1]: snmpd.service: Deactivated successfully.
May 01 15:00:50 foo systemd[1]: Stopped snmpd.service - Simple Network Management Protocol (SNMP) Daemon..
May 01 15:00:50 foo systemd[1]: Starting snmpd.service - Simple Network Management Protocol (SNMP) Daemon....
```
After the fix, the service `snmpd` is not restart (should be restart only if you change `host-name` or `domain-name`)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by dmbaturin** [comment]
I'm not a big fan of special cases inside config scripts, but I don't see a better solution right now.

@mergifyio backport sagitta

**Comment by c-po** [comment]
Please note that you should only use `leaf_node_changed()` if you care about what changed. It's always better (due to less code paths) to use `is_node_changed()` if you only care if something changed.

**Comment by sever-sever** [comment]
@MergifyIo backport sagitta

**Comment by sever-sever** [comment]
@MergifyIo backport equuleus

**Pull request merged**
