### PR TITLE
ifconfig: T2057: generalised Interface configuration

### PR DESCRIPTION
**Pull request by thomas-mangin**
Provides a consistent way to pass options to sub-classes of Interface. Using python **kwargs, parameters, options can be passed one by one or using a dict.

MACVLANIf("name0", option1=value1, option2=value2)

or 

options = { 'option1': value1, 'option2': value2, }
MAVLANIf("name0", **options)

The interface creation/deletion code was moved into a sub-function which was redefined by sub-classes, tidying the code.

### CODE REVIEW

**Comment by dmbaturin** [comment]
Are there places where this can cause incompatibilities?

**Comment by thomas-mangin** [comment]
The ** is a python feature. 

You can not have something like Interface('name',option-with-minus=10) but you can have Interface('name',**{'option-with-minus:10}) is it what you are asking ?

**Comment by c-po** [comment]
going to validate this the next couple hours

**Comment by thomas-mangin** [comment]
@dmbaturin no it does not cause any incompatibilities.

**Comment by c-po** [comment]
I took the latest commits here and build myself an ISO. It turned out to be not bootable as in the configuration was not properly applied leading to no network connectivity.

Please test by building yourself a dedicated ISO image.

**Comment by thomas-mangin** [comment]
Thank you @c-po sorry for this. I will do this and look at why it works when updating the dpkg but not building the iso.

**Pull request merged**
