### PR TITLE
squid: T3299: Add listen address 0.0.0.0

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add listen address 0.0.0.0 for service squid.
## Types of changes

 
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

T3299
## Component(s) name

squid, webproxy
## How to test

```
set service webproxy default-port '3128'
set service webproxy listen-address 0.0.0.0 disable-transparent
set service webproxy url-filtering squidguard default-action 'block'
set service webproxy url-filtering squidguard local-ok 'vyos.io'
set service webproxy url-filtering squidguard local-ok 'forum.vyos.io'
commit

```
Check connections
```
vyos@r2-roll:~$ show system connections | match 3128
tcp        0      0 0.0.0.0:3128            0.0.0.0:*               LISTEN  

```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — CHANGES_REQUESTED** [review]
I wonder if a better approach would be to make the `listen-address` parameter optional and make it listen on all addresses by default. That's what we do for most services that aren't interface-bound, like SSH or SNMP.

The only justification for requiring it in web proxy is the `disable-transparent` option. I always hated it and I believe we may want to get rid of it before 1.3 is finalized. Make the `transparent` option explicit, like `set service webproxy transparent`, and make it off by default because transparent proxies are evil and rude, and the proper way to force a proxy is to firewall external connections and distribute a wpad.dat file via DHCP (we already have an option for it).

**Comment by jack9603301** [comment]
Regarding the transparent proxy, I don't think it should be restricted to its patent implementation for a particular WebProxy, and if possible, whether a separate CLI can be used to set the TPROXY transparent forwarding

**Comment by jack9603301** [comment]
Transparent proxies may need to rely on iptables and require special Settings for the bridge so that the iptables policy can be enforced

Add the `bridge-nf` kernel module

**Comment by dmbaturin** [comment]
@jack9603301 I agree, we should also add a generic redirect target to NAT. Whether we should remove the magical transparent proxy setting is an interesting question. It may be better left to 1.4 because it would be a very big change.

**Comment by jack9603301** [comment]
@dmbaturin This is not a normal redirect strategy, we should consider integrating support for the TProxy protocol (this is based on the iptables module)

**Comment by c-po** [comment]
Instead of any workaround I go with @dmbaturin opinion about removing this madness and making the listen-address part entirely optional like we have on other services (ssh, ntp, dns)

**Comment by sever-sever** [comment]
I don't have any idea how to do it the right way, I close pr.

**Comment by c-po** [comment]
removing the listen addr check and Jinja template would have been sufficient for 1.4 until the transparent stuff is also migrated.

**Comment by sever-sever** [comment]
> removing the listen addr check

Done

**Pull request merged**
