### PR TITLE
ssh: T2651: use Debian style include directve for ssh_config.d

### PR DESCRIPTION
**Pull request by c-po**
## Change Summary

Commit 846e306700a ("ssh: T2651: add cli options for source address") added support for a basic SSH client option, but it grabbed the entire /etc/ssh/ssh_config file without the ability to make custom user adjustments via the /etc/ssh/ssh_config.d/ folder.

This commit places the VyOS SSH options under /etc/ssh/ssh_config.d/ leaving the common override system alive.

(cherry picked from commit 7763de6c4b93d3372ab3f4572d9fa6b7536102b3)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T2651

## Component(s) name

SSH client

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by b-** [comment]
Thank you!

**Comment by c-po** [comment]
Somehow it feels unsupported on Debian Buster

**Comment by b-** [comment]
> Somehow it feels unsupported on Debian Buster

What do you mean by unsupported? I don't see `/etc/ssh/ssh_config.d` explicitly mentioned in the Debian documentation, but the Include directive is part of OpenSSH and is documented in the upstream [OpenSSH manual](https://man.openbsd.org/ssh_config#Include). (The [stock OpenSSH /etc/ssh/ssh_config](https://github.com/openssh/openssh-portable/blob/master/ssh_config) is effectively blank, though)

**Comment by c-po** [comment]
Superseeded by https://github.com/vyos/vyos-1x/pull/1743

**Pull request closed without merging**
