### PR TITLE
T5169: nat: add option to map network and ports. 

### PR DESCRIPTION
**Pull request by nicolas-fort**
## Change Summary

Add option to map network and ports. Feature used for large deployments in cgnat.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5169

## Component(s) name

nat

## How to test

```
vyos@CGNAT:~$ show config comm | grep nat
set nat source rule 10 protocol 'tcp_udp'
set nat source rule 10 source address '100.64.0.0/27'
set nat source rule 10 translation address '198.51.100.0/27'
set nat source rule 10 translation port '1025-2048'
set nat source rule 20 protocol 'tcp_udp'
set nat source rule 20 source address '100.64.0.32/27'
set nat source rule 20 translation address '198.51.100.0/27'
set nat source rule 20 translation port '2049-3072'
vyos@CGNAT:~$ sudo nft list chain ip vyos_nat POSTROUTING
table ip vyos_nat {
        chain POSTROUTING {
                type nat hook postrouting priority srcnat; policy accept;
                counter packets 29 bytes 1964 jump VYOS_PRE_SNAT_HOOK
                meta l4proto { tcp, udp } counter packets 29 bytes 1964 snat ip prefix to ip saddr map { 100.64.0.0/27 : 198.51.100.0/27 . 1025-2048 } comment "SRC-NAT-10"
                meta l4proto { tcp, udp } counter packets 22 bytes 1528 snat ip prefix to ip saddr map { 100.64.0.32/27 : 198.51.100.0/27 . 2049-3072 } comment "SRC-NAT-20"
        }
}

vyos@CGNAT:~$ sudo conntrack -L | grep 198
conntrack v1.4.6 (conntrack-tools): 15 flow entries have been shown.
tcp      6 109 TIME_WAIT src=100.64.0.5 dst=142.250.79.132 sport=60834 dport=80 src=142.250.79.132 dst=198.51.100.5 sport=80 dport=1384 [ASSURED] mark=0 use=1
tcp      6 27 TIME_WAIT src=100.64.0.5 dst=142.251.134.68 sport=48626 dport=80 src=142.251.134.68 dst=198.51.100.5 sport=80 dport=1348 [ASSURED] mark=0 use=1
tcp      6 107 TIME_WAIT src=100.64.0.38 dst=142.251.134.36 sport=43312 dport=80 src=142.251.134.36 dst=198.51.100.6 sport=80 dport=2437 [ASSURED] mark=0 use=1
udp      17 17 src=100.64.0.38 dst=1.1.1.1 sport=47356 dport=53 src=1.1.1.1 dst=198.51.100.6 sport=53 dport=2895 mark=0 use=1
tcp      6 28 TIME_WAIT src=100.64.0.5 dst=142.251.134.36 sport=43302 dport=80 src=142.251.134.36 dst=198.51.100.5 sport=80 dport=1865 [ASSURED] mark=0 use=1
tcp      6 31 TIME_WAIT src=100.64.0.38 dst=216.58.202.100 sport=45192 dport=80 src=216.58.202.100 dst=198.51.100.6 sport=80 dport=2226 [ASSURED] mark=0 use=1
udp      17 19 src=100.64.0.5 dst=8.8.8.8 sport=56218 dport=53 src=8.8.8.8 dst=198.51.100.5 sport=53 dport=1192 mark=0 use=1
tcp      6 103 TIME_WAIT src=100.64.0.5 dst=142.251.134.36 sport=44062 dport=80 src=142.251.134.36 dst=198.51.100.5 sport=80 dport=2015 [ASSURED] mark=0 use=1
udp      17 13 src=100.64.0.5 dst=8.8.8.8 sport=57447 dport=53 src=8.8.8.8 dst=198.51.100.5 sport=53 dport=1829 mark=0 use=1
tcp      6 30 TIME_WAIT src=100.64.0.38 dst=216.58.202.100 sport=45182 dport=80 src=216.58.202.100 dst=198.51.100.6 sport=80 dport=2985 [ASSURED] mark=0 use=1
tcp      6 106 TIME_WAIT src=100.64.0.38 dst=142.251.134.36 sport=43298 dport=80 src=142.251.134.36 dst=198.51.100.6 sport=80 dport=2659 [ASSURED] mark=0 use=1
udp      17 16 src=100.64.0.38 dst=1.1.1.1 sport=42926 dport=53 src=1.1.1.1 dst=198.51.100.6 sport=53 dport=2728 mark=0 use=1
vyos@CGNAT:~$ 
```

## Smoketest result

```
root@CGNAT:/usr/libexec/vyos/tests/smoke/cli# ./test_nat.py 
test_dnat (__main__.TestNAT.test_dnat) ... ok
test_dnat_negated_addresses (__main__.TestNAT.test_dnat_negated_addresses) ... ok
test_dnat_redirect (__main__.TestNAT.test_dnat_redirect) ... ok
test_dnat_without_translation_address (__main__.TestNAT.test_dnat_without_translation_address) ... ok
test_nat_balance (__main__.TestNAT.test_nat_balance) ... ok
test_nat_no_rules (__main__.TestNAT.test_nat_no_rules) ... ok
test_snat (__main__.TestNAT.test_snat) ... ok
test_snat_groups (__main__.TestNAT.test_snat_groups) ... ok
test_snat_net_port_map (__main__.TestNAT.test_snat_net_port_map) ... ok
test_snat_required_translation_address (__main__.TestNAT.test_snat_required_translation_address) ... 
Source NAT configuration error in rule 5: translation requires address
and/or port

ok
test_static_nat (__main__.TestNAT.test_static_nat) ... ok

----------------------------------------------------------------------
Ran 11 tests in 22.074s

OK
root@CGNAT:/usr/libexec/vyos/tests/smoke/cli# 2

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
For CGNAT you don't need to add a group of ports to the network to the same group prefix of external addresses; it is useless. But you need to add a range of ports to binds per an external address/network.
For example:
```
For example:
hots 100.64.0.1 ports 1024-3039
host 100.64.0.2 ports 3040-5055
```
And so on...

Let's say you have /24 for the internal network (100.64.0.0/24) and /29 (203.0.113.0/29) for the external network. Will it work with persistent port maps?

I'm expecting:
```
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.0 counter snat to 203.0.113.0:1024-3039
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.0 counter snat to 203.0.113.0:1024-3039
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.1 counter snat to 203.0.113.0:3040-5055
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.1 counter snat to 203.0.113.0:3040-5055
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.2 counter snat to 203.0.113.0:5056-7071
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.2 counter snat to 203.0.113.0:5056-7071
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.3 counter snat to 203.0.113.0:7072-9087
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.3 counter snat to 203.0.113.0:7072-9087
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.4 counter snat to 203.0.113.0:9088-11103
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.4 counter snat to 203.0.113.0:9088-11103
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.5 counter snat to 203.0.113.0:11104-13119
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.5 counter snat to 203.0.113.0:11104-13119
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.6 counter snat to 203.0.113.0:13120-15135
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.6 counter snat to 203.0.113.0:13120-15135
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.7 counter snat to 203.0.113.0:15136-17151
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.7 counter snat to 203.0.113.0:15136-17151
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.8 counter snat to 203.0.113.0:17152-19167
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.8 counter snat to 203.0.113.0:17152-19167
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.9 counter snat to 203.0.113.0:19168-21183
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.9 counter snat to 203.0.113.0:19168-21183
add rule ip nat CGNATOUT_0 ip protocol tcp ip saddr 100.64.0.10 counter snat to 203.0.113.0:21184-23199
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.10 counter snat to 203.0.113.0:21184-23199
...
add rule ip nat CGNATOUT_0 ip protocol udp ip saddr 100.64.0.31 counter snat to 203.0.113.0:63520-65535
...

add rule ip nat CGNATOUT_7 ip protocol tcp ip saddr 100.64.0.254 counter snat to 203.0.113.7:61504-63519
add rule ip nat CGNATOUT_7 ip protocol udp ip saddr 100.64.0.254 counter snat to 203.0.113.7:61504-63519
add rule ip nat CGNATOUT_7 ip protocol tcp ip saddr 100.64.0.255 counter snat to 203.0.113.7:63520-65535
add rule ip nat CGNATOUT_7 ip protocol udp ip saddr 100.64.0.255 counter snat to 203.0.113.7:63520-65535

```
i.e. 32 internal addresses per external IP address

Is it possible to archive it with this PR?

**Comment by nicolas-fort** [comment]
But these 2 rules, for example:
```
	meta l4proto { tcp, udp } counter snat ip prefix to ip saddr map { 100.64.0.0/27 : 198.51.100.0/27 . 1025-2048 } comment "SRC-NAT-10"
	meta l4proto { tcp, udp } counter snat ip prefix to ip saddr map { 100.64.0.32/27 : 198.51.100.0/27 . 2049-3072 } comment "SRC-NAT-20"
```
Would be the same as to have tons of entries like:
```
	# Split rule 10 intro 32 rules:
	meta l4proto { tcp, udp } ip saddr 100.64.0.0 counter snat to 198.51.100.0:1025-2048 comment "SRC-NAT-100"
	meta l4proto { tcp, udp } ip saddr 100.64.0.1 counter snat to 198.51.100.1:1025-2048 comment "SRC-NAT-101"
	...
	meta l4proto { tcp, udp } ip saddr 100.64.0.31 counter snat to 198.51.100.31:1025-2048 comment "SRC-NAT-131"
	.
	.
	# Split rule 20 into next 32 rules:
	meta l4proto { tcp, udp } ip saddr 100.64.0.32 counter snat to 198.51.100.0:2049-3072 comment "SRC-NAT-200"
	meta l4proto { tcp, udp } ip saddr 100.64.0.33 counter snat to 198.51.100.1:2049-3072 comment "SRC-NAT-201"
	...
	meta l4proto { tcp, udp } ip saddr 100.64.0.63 counter snat to 198.51.100.31:2049-3072 comment "SRC-NAT-231"
```

Or I'm missing something?

**Comment by sever-sever** [comment]
> But these 2 rules, for example:
> 
> ```
> 	meta l4proto { tcp, udp } counter snat ip prefix to ip saddr map { 100.64.0.0/27 : 198.51.100.0/27 . 1025-2048 } comment "SRC-NAT-10"
> 	meta l4proto { tcp, udp } counter snat ip prefix to ip saddr map { 100.64.0.32/27 : 198.51.100.0/27 . 2049-3072 } comment "SRC-NAT-20"
> ```
> 
> Would be the same as to have tons of entries like:
> 
> ```
> 	# Split rule 10 intro 32 rules:
> 	meta l4proto { tcp, udp } ip saddr 100.64.0.0 counter snat to 198.51.100.0:1025-2048 comment "SRC-NAT-100"
> 	meta l4proto { tcp, udp } ip saddr 100.64.0.1 counter snat to 198.51.100.1:1025-2048 comment "SRC-NAT-101"
> 	...
> 	meta l4proto { tcp, udp } ip saddr 100.64.0.31 counter snat to 198.51.100.31:1025-2048 comment "SRC-NAT-131"
> 	.
> 	.
> 	# Split rule 20 into next 32 rules:
> 	meta l4proto { tcp, udp } ip saddr 100.64.0.32 counter snat to 198.51.100.0:2049-3072 comment "SRC-NAT-200"
> 	meta l4proto { tcp, udp } ip saddr 100.64.0.33 counter snat to 198.51.100.1:2049-3072 comment "SRC-NAT-201"
> 	...
> 	meta l4proto { tcp, udp } ip saddr 100.64.0.63 counter snat to 198.51.100.31:2049-3072 comment "SRC-NAT-231"
> ```
> 
> Or I'm missing something?

The goal of CGNAT is to set the persistent ports ranges for translations. This way, you can identify the subscriber as he will use the same (unique) port ranges for translations.

Lets say the simplest example, I have one external IP and 4 internal clients and want to set persistent ports translations.
How does it look like?
In your example, you set internal/27 to external/27 that completely useless.

**Review by sever-sever — APPROVED** [review]
Approve this option as extended NAT, but it is not CGNAT.

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
