### PR TITLE
op-mode: T621: Allow image pruning by list index

### PR DESCRIPTION
**Pull request by natali-rs1985**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

 * https://vyos.dev/T621
## Component(s) name

op-mode
## Proposed changes

Allow `delete system image` deletion of images by list index
```
delete system image name <name>
delete system image index <index>
```
## How to test

```
vyos@vyos:~$ del system image
Possible completions:
  <Enter>               Execute the current command
  index                 Image index
  name                  Image name


vyos@vyos:~$ del system image index
Possible completions:
  1:__1.5-rolling-202409160007
                        Image index
  2:__1.5-rolling-202408280022
  3:__1.5-rolling-202402050024


vyos@vyos:~$ del system image index  2
Do you really want to delete the image 1.5-rolling-202408280022? [y/N] n
```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Do we really need it?
We can type “delete system image” and press enter and select the number of the image 
I don’t like this idea, at least without usecase

**Comment by c-po** [comment]
I tend to agree with @sever-sever.

There is `delete system image <name>` where `<name>` support TAB completion. I see no need for an index based delete, as `delete system image` asks via stdin for the index.

**Comment by natali-rs1985** [comment]
Okay. Then I'll just close it and the ticket too.

**Comment by dmbaturin** [comment]
I'm inclined to agree. It looked like a good idea at the time, but now completion solves the underlying problem (I seem to recall when the task was created, there was no proper completion for image names), and it can be dangerous because it's much easier to type, say, `3` instead of `4` without realizing what image it refers to than to type the image name.

But thanks for the effort!

**Comment by dmbaturin** [comment]
Sorry for the wasted effort! The implementation is good but we cannot merge it as the idea in the community member's task was misguided.

**Pull request closed without merging**
