### PR TITLE
utils: T6530: add a helper for easily calling iproute2 commands

### PR DESCRIPTION
**Pull request by dmbaturin**
## Change Summary

The helper calls iproute2 and returns a dict produced from its JSON output by default, but also offers an option to get a raw output instead.

```
from vyos.utils.process import ip_cmd

ip_cmd("link list")
# [{'ifindex': 1, 'ifname': 'lo', 'flags': ['LOOPBACK', 'UP', 'LOWER_UP'], 'mtu': 65536, 'qdisc': 'noqueue', 'operstate': 'UNKNOWN', 'linkmode': 'DEFAULT', 'group': 'default', 'txqlen': 1000, 'link_type': 'loopback', 'address': '00:00:00:00:00:00', 'broadcast': '00:00:00:00:00:00'},

ip_cmd("link list", json=False) # returns raw output
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Component(s) name

`vyos.utils`

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Can you refactor the occurrances with the new code?

```bash
(12:45) vyos_bld 9da83ff9b5e9:/vyos/vyos-1x [current] # git grep "ip --json"
python/vyos/utils/network.py:    tmp = loads(cmd('ip --json netns ls'))
python/vyos/utils/network.py:        output = cmd(f'ip --json --brief link show vrf {vrf}')
python/vyos/utils/network.py:    tmp = cmd(f'ip --json netns ls')
python/vyos/utils/network.py:        data = loads(cmd(f'ip netns exec {netns} ip --json link show'))
python/vyos/utils/network.py:    tmp = loads(cmd('ip --json vrf list'))
python/vyos/utils/network.py:    rc, out = rc_cmd(f'{netns_cmd} ip --json address show dev {ifname}')
src/conf_mode/vrf.py:    $ ip --json -4 rule show
src/etc/opennhrp/opennhrp-script.py:    route_get_cmd: str = f'sudo ip --json route get {nbma_dst} from {nbma_src}'
src/helpers/vyos-failover.py:    rc, data = rc_cmd(f'ip --json route show protocol failover {route} '
src/op_mode/neighbor.py:# Sample output of `ip --json neigh list`:
src/op_mode/openvpn.py:    rc, out = rc_cmd(f'ip --json link show dev {iface}')
src/op_mode/openvpn.py:    rc, out = rc_cmd(f'ip --json link show dev {iface}')
src/op_mode/vrf.py:    output = cmd('ip --json --brief link show type vrf')
src/op_mode/vrf.py:            output = cmd(f'ip --json --brief link show dev {name}')
```

**Comment by dmbaturin** [comment]
@c-po I was thinking of making it a separate PR if no one objects to the function name and arguments I used. I'm happy to do it, let's see if anyone want any changes in the function — if not, I'll refactor in this PR.

**Review by sever-sever — APPROVED** [review]

**Review by c-po — APPROVED** [review]
The overall signature looks good. We have one line of code calling `ip --json --brief?` which should be revised if `--brief` is really required.

**Comment by dmbaturin** [comment]
I think I'll better merge this and make a new one, because this change by itself doesn't break anything, but refactoring may take more testing.

**Pull request merged**
