### PR TITLE
bgp: ospf: T3434: op-mode refactoring for support vrf

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add support op-mode for BGP/OSPF in vrf. Op-mode BGP/OSPF refactoring
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3434
* https://phabricator.vyos.net/T3436

## Component(s) name

op-mode, bgp
## How to test
VyOS config
```
set protocols bgp 65002 neighbor 100.64.0.5 remote-as '65003'
set vrf name foo protocols bgp 65111 neighbor 203.0.113.5 remote-as '65222'
```
Op-mode
```
vyos@r5:~$ show ip bgp sum

IPv4 Unicast Summary:
BGP router identifier 192.168.122.15, local AS number 65002 vrf-id 0

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt
100.64.0.5      4      65003         0         0        0    0    0    never       Active        0

Total number of neighbors 1
vyos@r5:~$ 
vyos@r5:~$ show ip bgp vrf foo summary 

IPv4 Unicast Summary:
BGP router identifier 192.168.101.144, local AS number 65111 vrf-id 4

Neighbor        V         AS   MsgRcvd   MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd   PfxSnt
203.0.113.5     4      65222         0         0        0    0    0    never       Active        0

Total number of neighbors 1
vyos@r5:~$ 

```
OSPF
```
vyos@r5:~$ show ip ospf vrf foo route 
VRF Name: foo
============ OSPF network routing table ============
N    192.168.101.0/24      [1] area: 0.0.0.0
                           directly attached to eth1
N    192.168.122.0/24      [2] area: 0.0.0.0
                           via 192.168.101.145, eth1

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — CHANGES_REQUESTED** [review]
I feel rather uneasy about passing commands implicitly with `$@`, for two reasons:
1. It's harder to see what command it will run (you need to look up the XML nodes).
2. It's also harder to grep for specific commands.
3. One to one mapping isn't always optimal, and this makes it harder to inject additional arguments, adjust for changes in FRR if something changes upstream etc.

I think it would be better to write out full commands right away.

**Comment by c-po** [comment]
@dmbaturin I initially had the idea to add a <frrcommand> XML node but in a discussion we agreed on using a shell script instead as you did not like the idea of an "external program" bound XML node.

This is what we have in the "old" Vyatta codebase as it is the easiest and most refactorable way in interacting to vtysh/FRR, as you can simply grep this string in the repository.

**Comment by dmbaturin** [comment]
@c-po Maybe my wording was confusing. To clarify, I mean I think `${vyos_op_scripts_dir}/vtysh_wrapper.sh show ip bgp ...` is better than implicit `${vyos_op_scripts_dir}/vtysh_wrapper.sh $@` because the command is a) decoupled from the CLI so we can keep the same CLI even if FRR makes incompatible changes b) easily grepable.

**Comment by sever-sever** [comment]
One of the advantages to use **${vyos_op_scripts_dir}/vtysh_wrapper.sh $@**  it's we can declare commands only one time and include it to global and vrf mode.
With explicit CLI we should declare it separately for global and for vrf.
For example:
```
set protocols bgp 65001 neighbor 192.168.122.12 remote-as '65002'
set vrf name foo protocols bgp 65001 neighbor 192.168.101.145 address-family ipv4-unicast soft-reconfiguration inbound
set vrf name foo protocols bgp 65001 neighbor 192.168.101.145 remote-as '65002'
```
Implicit mode ($@)
```
vyos@r5:~$ show ip bgp neighbors 192.168.122.12 routes
BGP table version is 4, local router ID is 192.168.122.15, vrf id 0

   Network          Next Hop            Metric LocPrf Weight Path
*> 100.64.0.0/24    192.168.122.12           0             0 65002 i

vyos@r5:~$ show ip bgp vrf foo ipv4 unicast neighbors 192.168.101.145 routes 
BGP table version is 4, local router ID is 192.168.101.144, vrf id 4

   Network          Next Hop            Metric LocPrf Weight Path
*> 100.64.0.0/24    192.168.101.145          0             0 65002 i

```
Explicit mode
```
vyos@r5:~$ show ip bgp neighbors 192.168.122.12 routes
BGP table version is 4, local router ID is 192.168.122.15, vrf id 0

   Network          Next Hop            Metric LocPrf Weight Path
*> 100.64.0.0/24    192.168.122.12           0             0 65002 i

vyos@r5:~$ show ip bgp vrf foo ipv4 unicast neighbors 192.168.101.145 routes 
% Malformed address or name: unicast
```

**Comment by dmbaturin** [comment]
@sever-sever Oh... you are right, this is the point I missed completely. Indeed, written-out commands won't work with include, and I see no easy way to make it work.

**Review by dmbaturin — APPROVED** [review]

**Comment by c-po** [comment]
There would be one option to make this work. Introduce a new XML node which, when set, will write the explicit command into the generated `node.def` file.

**Pull request merged**
