### PR TITLE
openvpn: T3214: fix server-ipv6 and nopool handling

### PR DESCRIPTION
**Pull request by ordex**
## Change Summary
This PR implements the following changes:
1. allows again specifying an IPv6 subnet on an OpenVPN server interface;
1. gets rid of code handling client-ipv6-pool as it is currently not used at all when configuring the interface;
1. allow configuring a server with a v6 only subnet (possible since openvpn v2.5.0)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)
* https://phabricator.vyos.net/T3214

## Component(s) name
openvpn

## Proposed changes
1. instead of unconditionally specifying the 'nopool' keyword on the --server directive, do so only if a client-ip-pool was specified. Also, since nopool is incompatible with --server-ipv6, throw an error at commit time if a client-ip-pool is specified and a v6 subnet is configured as well;
2. client-ipv6-pool is not used at all, therefore code handling it can simply be removed. Once upstream fixes a bit the way an ipv6 pool can be specified, this code can then be reintroduced again (with some actual user);
3. since opnvpn 2.5.0 it is possible to have a tunnel with v6 only configured. For this reason this change drops the check allowing the existence of an ipv6 subnet only if an ipv4 one was specified too.

## How to test
1. simply specify a v6 subnet and commit. Add a client-ip-pool and check that now the config is rejected;
2. nothing to test;
3. specify only an ipv6 subnet and commit.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
It seems to require a [migration-script](https://github.com/vyos/vyos-1x/tree/current/src/migration-scripts/interfaces)

**Review by dmbaturin — CHANGES_REQUESTED** [review]
There are two opinions on removing the IPv6 pool command:

>client-ipv6-pool is not used at all, therefore code handling it can simply be removed. Once upstream fixes a bit the way an ipv6 pool can be specified, this code can then be reintroduced again (with some actual user) (@ordex)

>It seems to require a [migration-script](https://github.com/vyos/vyos-1x/tree/current/src/migration-scripts/interfaces) (@sever-sever).

And I disagree with both. ;)

Removing commands should be the absolute last resort when there's no hope to ever get them to work as they are. Removing them to re-introduce them later is a horrible practice and it always drives me mad when people do it to software I'm using.

An upstream bug is not a reason to remove commands until it's fixed. We can add a warning to notify users that what they want to use doesn't work as expected right now, but as long as there's hope that we can generate working OpenVPN options from the pool command as it is, it must remain in place.

**Comment by ordex** [comment]
Hi @dmbaturin and thanks for your feedback! I totally agree with you - this is my first PR/change to VyOS, therefore I am not familiar with policies and habits. But what you say makes sense (obviously!).

At this point I will remove the patch wiping the client-ipv6-pool and will simply leave it alone. At the moment that option does *nothing* because it is not rendered in the template at all.

Later, it can be fixed in a separate PR.

**Comment by sever-sever** [comment]
Smoketest fail
```
vyos@vyos:~$ /usr/libexec/vyos/tests/smoke/cli/test_interfaces_openvpn.py
test_openvpn_client_interfaces (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_client_verify (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_options (__main__.TestInterfacesOpenVPN) ... ok
test_openvpn_server_net30_topology (__main__.TestInterfacesOpenVPN) ... FAIL
test_openvpn_server_subnet_topology (__main__.TestInterfacesOpenVPN) ... FAIL
test_openvpn_server_verify (__main__.TestInterfacesOpenVPN) ...
```

**Comment by dmbaturin** [comment]
Let's re-evaluate when 1.4 is branched off.

**Comment by Apachez-** [comment]
Smoketests seems to get upset:

```
DEBUG - ======================================================================
DEBUG - FAIL: test_openvpn_server_net30_topology (__main__.TestInterfacesOpenVPN.test_openvpn_server_net30_topology)
DEBUG - ----------------------------------------------------------------------
DEBUG - Traceback (most recent call last):
DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_interfaces_openvpn.py", line 504, in test_openvpn_server_net30_topology
DEBUG -     self.assertIn(f'server {network} {netmask} nopool', config)
DEBUG - AssertionError: 'server 192.0.20.0 255.255.255.0 nopool' not found in '### Autogenerated by interfaces-openvpn.py ###\n#\n# See [https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage\n#](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage/n#) for individual keyword definition\n#\n# \n#\n\nverb 3\ndev-type tun\ndev vtun20\npersist-key\nproto udp\nmultihome\nlport 2020\npush "redirect-gateway def1"\ndisable-dco\n\n#\n# OpenVPN Server mode\n#\nmode server\ntls-server\ntopology net30\nserver 192.0.20.0 255.255.255.0 \n\nkeepalive 5 50\nmanagement /run/openvpn/openvpn-mgmt-intf unix\n\n\n# TLS options\nca /run/openvpn/vtun20_ca.pem\ncert /run/openvpn/vtun20_cert.pem\nkey /run/openvpn/vtun20_cert.key\ndh /run/openvpn/vtun20_dh.pem\n\n\n# Encryption options\ncipher AES-192-CBC\n# [https://vyos.dev/T5027\n#](https://vyos.dev/T5027/n#) Required to support BF-CBC (default ciphername when none given)\nproviders legacy default\n\nauth sha256'
DEBUG - 
DEBUG - ======================================================================
DEBUG - FAIL: test_openvpn_server_subnet_topology (__main__.TestInterfacesOpenVPN.test_openvpn_server_subnet_topology)
DEBUG - ----------------------------------------------------------------------
DEBUG - Traceback (most recent call last):
DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_interfaces_openvpn.py", line 424, in test_openvpn_server_subnet_topology
DEBUG -     self.assertIn(f'server {network} {netmask} nopool', config)
DEBUG - AssertionError: 'server 192.0.20.0 255.255.255.0 nopool' not found in '### Autogenerated by interfaces-openvpn.py ###\n#\n# See [https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage\n#](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage/n#) for individual keyword definition\n#\n# \n#\n\nverb 3\ndev-type tun\ndev vtun20\npersist-key\nproto udp\nmultihome\nlport 2020\npush "redirect-gateway def1"\ndisable-dco\n\n#\n# OpenVPN Server mode\n#\nmode server\ntls-server\ntopology subnet\nserver 192.0.20.0 255.255.255.0 \n\nclient-config-dir /run/openvpn/ccd/vtun20\nkeepalive 5 25\nmanagement /run/openvpn/openvpn-mgmt-intf unix\n\nplugin "/usr/lib/openvpn/openvpn-otp.so" "otp_secrets=/config/auth/openvpn/vtun20-otp-secrets otp_slop=180 totp_t0=0 totp_step=30 totp_digits=6 password_is_cr=1"\n\n# TLS options\nca /run/openvpn/vtun20_ca.pem\ncert /run/openvpn/vtun20_cert.pem\nkey /run/openvpn/vtun20_cert.key\ndh /run/openvpn/vtun20_dh.pem\n\n\n# Encryption options\ncipher AES-192-CBC\n# [https://vyos.dev/T5027\n#](https://vyos.dev/T5027/n#) Required to support BF-CBC (default ciphername when none given)\nproviders legacy default\n\nauth sha256'
```

**Comment by c-po** [comment]
Yes, it was a discussion during the maintainer meeting to first merge this and the fix the smoketests which is done in 455943cd7f759a5a3fc53d421b479044730d1f08

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
