### PR TITLE
T5944: Fix reboot in arg

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Fix the arg for the `reboot in x` command
The actual arg is `--reboot_in [Minutes ...]`
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5944

## Component(s) name

reboot, power
## How to test
Before the fix:
```
vyos@r4:~$ reboot in 1
usage: powerctrl.py [-h] [--yes] (--reboot [HH:MM ...] | --reboot_in [Minutes ...] | --poweroff [Minutes|HH:MM ...] | --cancel | --check)
powerctrl.py: error: one of the arguments --reboot/-r --reboot_in/-i --poweroff/-p --cancel/-c --check is required
vyos@r4:~$ 

```
After the fix:
```vyos@r4:~$ reboot in 1
Warning: there are unsaved configuration changes!
Run 'save' command if you do not want to lose those changes after reboot/shutdown.

Broadcast message from root@debian on pts/3 (Sun 2024-01-14 22:49:19 EET):

The system will reboot at Sun 2024-01-14 22:50:19 EET!

                                                                               
Broadcast message from root@r4 (somewhere) (Sun Jan 14 22:49:19 2024):         
                                                                               
System reboot is scheduled 1
                                                                               
                                                                               
Broadcast message from root@r4 (somewhere) (Sun Jan 14 22:49:19 2024):         
                                                                               
System reboot is scheduled 1
                                                                               
Reboot is scheduled 2024-01-14 22:50:19
vyos@r4:~$ 
vyos@r4:~$ 
vyos@r4:~$ show reboot 
Reboot is scheduled 2024-01-14 22:50:19
vyos@r4:~$ 
Broadcast message from root@debian on pts/3 (Sun 2024-01-14 22:50:19 EET):

The system will reboot now!

Connection to 192.168.122.14 closed by remote host.
Connection to 192.168.122.14 closed.

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Backport required

**Review by jestabro — COMMENTED** [review]
It is probably better to change the command line argument in the script to
`--reboot-in`
since argparse will correctly read this as `args.reboot_in`, and this is the normalized form when this script is moved to use opmode.py.

**Comment by sever-sever** [comment]
> It is probably better to change the command line argument in the script to `--reboot-in` since argparse will correctly read this as `args.reboot_in`, and this is the normalized form when this script is moved to use opmode.py.

@jestabro Done!

**Review by jestabro — APPROVED** [review]

**Comment by sever-sever** [comment]
@MergifyIo backport sagitta

**Pull request merged**
