### PR TITLE
http-api: T6069: fix concurrent configure requests

### PR DESCRIPTION
**Pull request by thomasfinstad**
## Change Summary

fix concurrent configure requests via api

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6069
* https://vyos.dev/T5006
* https://vyos.dev/T5305

## Related PR(s)

* https://github.com/vyos/vyos-1x/pull/1823

## Component(s) name

* http-api

## Proposed changes

Defining configure endpoint as async stops api server from segfaulting during multiple concurrent requests. This is a more conservative than previous attempts to fix this issue and only targets the configure  endpoint.

## How to test

```bash
#!/bin/bash

[ "$VYOS_HOST" == "" ] && echo "VYOS_HOST must be set to the dns or ip of your box"
[ "$VYOS_KEY" == "" ] && echo "VYOS_KEY must be set to your api key"

for i in {0..200}; do
    echo -n "$i/200 ";

    curl -k --fail --location --request POST "https://$VYOS_HOST/configure" --form key="$VYOS_KEY" --form data='[
        {"op":"delete","path":["firewall","ipv4","name","example1","default-action","accept"]},
        {"op":"set","path":["firewall","ipv4","name","example1","default-action","accept"]}
    ]' &
    pid1=$!

    curl -k --fail --location --request POST "https://$VYOS_HOST/configure" --form key="$VYOS_KEY" --form data='[
        {"op":"delete","path":["firewall","ipv4","name","example2","default-action","accept"]},
        {"op":"set","path":["firewall","ipv4","name","example2","default-action","accept"]}
    ]' &
    pid2=$!

    echo -n "Result: "

    wait $pid1
    ret1=$?
    wait $pid2
    ret2=$?

    echo

    [ $(($ret1 + $ret2)) != 0 ] && exit $(($ret1 + $ret2))
done
```

## Smoketest result

Unable to find documentation on how to run it.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
It was `async` in the previous version and changed in https://github.com/vyos/vyos-1x/commit/33016220be8e156720a3692ca309753c4e84cd2a
https://vyos.dev/T5305

**Comment by thomasfinstad** [comment]
I noticed that but the reversion did not explain which parts were affected very well so there was no way for me to do a better job testing it.
Currently this bug causes issues with any tooling that is async / concurrent when sending requests to the API

**Comment by jestabro** [comment]
I've added a link to the original problem in the task. I will take a look at the reproducer and compare.

**Comment by dmbaturin** [comment]
@thomasfinstad Could you put the task number in the "related tasks" section of the PR message please?

**Review by dmbaturin — COMMENTED** [review]
I'm a bit confused, to be fair. We declare it `async` here, but does it make FastAPI automatically `await` on it?

**Comment by jestabro** [comment]
Yes, FastAPI 'automatically' adjusts for the async keyword, where the definition of 'automatic' is summarized in https://vyos.dev/T5305

**Comment by thomasfinstad** [comment]
> @thomasfinstad Could you put the task number in the "related tasks" section of the PR message please?

@dmbaturin  Sorry, intended to include that from the start. Added now.

**Comment by jestabro** [comment]
Note that re-introducing async config operations will break the config-section call between two servers, as called remotely, which was the motivation to distinguish the cases (internal locking vs. add to event-loop), as summarized in T5305.

I would like to firstly investigate the race condition, thanks to the provided reproducer, so that we have a better understanding before just avoiding it by adding to the async event-loop.

**Comment by thomasfinstad** [comment]
@jestabro
Do you have some thoughts on if this will be changed to be compatible with multiple concurrent configure requests in the rolling + LTS releases?
And if you think so, any inkling of the time frame?
If not I just need a heads up as that means I will need to re-plumb the tooling I am working on and be a bit clever to make it work, but I just need to know so I can pick a direction and continue developing.

**Comment by jestabro** [comment]
@thomasfinstad my intention is to resolve this as soon as possible: I began investigating but have not discovered the root cause yet; I will post an update here and in the task by the end of the week.

**Comment by thomasfinstad** [comment]
@jestabro thank you very much, I understand I am being a bit rude asking about a timeline here and appreciate your help very much

**Comment by jestabro** [comment]
Not at all --- it is a reasonable question given your project timeline; secondly, it is an unexpected issue, raising questions that need a resolution.

**Comment by jestabro** [comment]
As discussed, this PR is on hold (thanks @sever-sever)  pending determination of root cause; update coming @thomasfinstad, but still in process ...

**Comment by jestabro** [comment]
A proposed fix is in:
https://github.com/vyos/vyos-1x/pull/3089
It is in draft while I run smoketests and other checks, but the reproducer shows no errors in my tests. When that PR is confirmed as the solution, we can close this one. @thomasfinstad, many thanks for catching this, and for the provided test and details !

**Comment by jestabro** [comment]
@thomasfinstad the above was merged and the change is one line if you are able to test. If that suffices, we will close this PR. Thanks, again.

**Pull request closed without merging**
