### PR TITLE
[OpenVPN] T1670: Added OpenVPN options: tls-auth, tun-mtu, ncp-ciphers, minimum tls ve…

### PR DESCRIPTION
**Pull request by vindenesen**
…rsion and added keepalive option to client section.

Also added checks to see if certificate files exists before trying to check the content of them.

Btw, this is my first ever pull request on Github, so please bear with me if I'm not following proper procedure.

### CODE REVIEW

**Comment by c-po** [comment]
Thanks for the contribution. I have some question abot commit fdf5479128087902ef93a958eb6a0192db2f495f b/c this one should be split into 4 individual commits each adding one enhancement.

In addition your MTU values confuse me. Why is the lower end 1000 bytes? Is it a limit of OpenVPN? Why is the upper limit > 1500 bytes? Using a tunnel MTU >= 1500 bytes on a UDP connection will render the tunnel useless is 90% of the cases b/c encapsulating traffic (1500 bytes) and adding the overhead for IP, UDP and ethernet will easily exceed the 1500 bytes MTU in most of the provider networks.

**Comment by vindenesen** [comment]
Thanks for the feedback! I will try to create four different commits/pull requests for this instead.

Regarding MTU, I have no idea what the lower and upper limits should be, so I just used 1000 - 2000. But from what I understand from your comment, the upper limit should probably be no more than 1500. I can't find any lower limit in the OpenVPN documentation, but an MTU of 1 would probably not be very useful either. I see that the MTU lower end on ethernet interface is set to 68, so I will use that instead, unless you have any other suggestions.

**Comment by c-po** [comment]
There was no need to close this pull request. YOu could have splitted the commit and then force push to your fork.

**Comment by c-po** [comment]
MTU has a lower limit of 68 bytes. For further information conduct RFC791.

**Comment by vindenesen** [comment]
I'm a complete noob with Github. Nice to know when it becomes necessary
again.
Thanks, will read up on it.

**Pull request closed without merging**
