### PR TITLE
Fix `NameError: name 'config' is not defined` on commit

### PR DESCRIPTION
**Pull request by petoem**
Fixes `commit failed` on vyos-1.3-rolling-202003150217 for vxlan interface.

### CODE REVIEW

**Review by dmbaturin — CHANGES_REQUESTED** [review]
Is there a compelling reason why copying the config hash and reformatting the values to include iproute2 keywords is better than just using different iproute2 command templates for the unicast and multicast cases?

I don't think that would be a bad kind of code duplication since it makes the code easier to read, and it's also faster than copying (even though for a small dict copy isn't expensive).

```
if unicast:
  cmd = 'ip link add ... remote {remote}'
else:
  cmd = 'ip link add ... group {group}'
```

**Comment by c-po** [comment]
@thomas-mangin

**Comment by thomas-mangin** [comment]
@dmbaturin your suggestion makes sense and is clearer: reading the code I had not understood it was what was happening.

**Comment by petoem** [comment]
@dmbaturin I am not a python dev and I made this on a vyos installation I use. When dealing with an unknown code base, I usually try to keep the changes minimal and try not to change values that could be used elsewhere. That's why I copied the dict. 

Anyway, your suggestion does make sense and I'll try to fix it.

**Comment by c-po** [comment]
@petoem thnks for beeing so kind and just sending a PR to use. I have merged it and adopted to our development guidelines @ https://docs.vyos.io/en/latest/contributing/development.html#submit-a-patch

**Pull request merged**
