### PR TITLE
vrrp: T4583: Rewrite show vrrp in the new op-mode format

### PR DESCRIPTION
**Pull request by erkin**
## Change Summary

A simple rewrite of `show vrrp` in the new op-mode format. Leaving this as a draft so that we can discuss whether to keep the old behaviour as it is or take a scalpel at the way we interface with keepalived and do a fresh rewrite.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4583

## Component(s) name

op-mode, vrrp

## Proposed changes

The behaviour is otherwise identical besides the format change. There's now a separate routine (not accessible through op-mode) to get the raw JSON dump. None of the other routines support raw output.

## How to test

```
$ show vrrp
$ show vrrp statistics
$ show vrrp detail
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by sever-sever** [comment]
@erkin Update or close it.

**Comment by sever-sever** [comment]
@erkin, let us know if the task is in progress or if you need to close it.

**Comment by erkin** [comment]
I couldn't figure out what's wrong with it. I tested every call on the latest nightly after a minor change and it didn't cause any problems. I just renamed `vrrp.py` to `show_vrrp.py` and made unconfigured/disabled errors to throw `UnconfiguredSubsystem` instead of exiting for consistency. Let me know if you see something I'm missing.

**Comment by sever-sever** [comment]
Do not rename if it is going to be using with GraphQL
The “vrrp.py” is a good name as example of other scripts defined in 
https://github.com/vyos/vyos-1x/blob/current/data/op-mode-standardized.json

**Comment by sever-sever** [comment]
We agree to use “tabulate” for all op-mode commands. Do not delete it.
Also each component has to be in “formatted” and “raw” format.

**Comment by sever-sever** [comment]
There are no requested changes for this PR
Closet it
Could you please re-open if you are still working on this PR or create a new one? I don't want to keep dead pull requests.

**Pull request closed without merging**
