### PR TITLE
configd: T6504: send sudo_user on session init and set env variable

### PR DESCRIPTION
**Pull request by jestabro**
## Change Summary

The environment variable SUDO_USER is checked by system_login.py so as to prevent deleting the current user. Provide from config session and set within configd environment.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6504

## Related PR(s)

* https://github.com/vyos/vyos-1x/pull/3652

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
The fix unfortunately does not work.

`vyos.utils.auth.get_current_user()` returns `nobody` when beeing executed under vyos-configd

See environment of vyos-configd below
```
foo@LR2.wue3# commit
nobody
environ({'LANG': 'en_US.UTF-8', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'HOME': '/root', 'LOGNAME': 'root', 'USER': 'root', 'SHELL': '/bin/bash', 'INVOCATION_ID': '4042c3114d34401f80de31fb3baaca7f', 'JOURNAL_STREAM': '7:20361', 'SYSTEMD_EXEC_PID': '4522'})
foo is logged in, forcing logout!
```

**Comment by jestabro** [comment]
Move to draft to revise ...

**Comment by jestabro** [comment]
@c-po revised with proper solution.

**Review by c-po — APPROVED** [review]
Tests work as exepcted, thanks!



```
cpo@LR2.wue3# delete system login user cpo
[edit]
cpo@LR2.wue3# commit

Attempting to delete current user: cpo

[[system login]] failed
Commit failed
```

**Comment by c-po** [comment]
This should be considered a backport to `circinus` and `sagitta` in the future to fix this behavior.

**Comment by c-po** [comment]
## Without vyos-configd
```console
$ /usr/libexec/vyos/tests/smoke/cli/test_system_login.py
test_add_linux_system_user (__main__.TestSystemLogin.test_add_linux_system_user) ... ok
test_delete_current_user (__main__.TestSystemLogin.test_delete_current_user) ... ok
test_radius_kernel_features (__main__.TestSystemLogin.test_radius_kernel_features) ... ok
test_system_login_max_login_session (__main__.TestSystemLogin.test_system_login_max_login_session) ... ok
test_system_login_otp (__main__.TestSystemLogin.test_system_login_otp) ... ok
test_system_login_radius_ipv4 (__main__.TestSystemLogin.test_system_login_radius_ipv4) ... ok
test_system_login_radius_ipv6 (__main__.TestSystemLogin.test_system_login_radius_ipv6) ... ok
test_system_login_tacacs (__main__.TestSystemLogin.test_system_login_tacacs) ... ok
test_system_login_user (__main__.TestSystemLogin.test_system_login_user) ... ok
test_system_user_ssh_key (__main__.TestSystemLogin.test_system_user_ssh_key) ... ok

----------------------------------------------------------------------
Ran 10 tests in 176.126s

OK
```

## With vyos-configd
```console
$ /usr/libexec/vyos/tests/smoke/cli/test_system_login.py
test_add_linux_system_user (__main__.TestSystemLogin.test_add_linux_system_user) ...
User "backup" can not be created, conflict with local system account!

ok
test_delete_current_user (__main__.TestSystemLogin.test_delete_current_user) ...
Attempting to delete current user: cpo

ok
test_radius_kernel_features (__main__.TestSystemLogin.test_radius_kernel_features) ... ok
test_system_login_max_login_session (__main__.TestSystemLogin.test_system_login_max_login_session) ...
"login timeout" must be configured!

ok
test_system_login_otp (__main__.TestSystemLogin.test_system_login_otp) ... ok
test_system_login_radius_ipv4 (__main__.TestSystemLogin.test_system_login_radius_ipv4) ...
Only one IPv4 source-address can be set!

ok
test_system_login_radius_ipv6 (__main__.TestSystemLogin.test_system_login_radius_ipv6) ...
Only one IPv6 source-address can be set!

ok
test_system_login_tacacs (__main__.TestSystemLogin.test_system_login_tacacs) ... ok
test_system_login_user (__main__.TestSystemLogin.test_system_login_user) ... ok
test_system_user_ssh_key (__main__.TestSystemLogin.test_system_user_ssh_key) ...
Missing type for public-key "vyos_test@domain-foo.com"!

ok

----------------------------------------------------------------------
Ran 10 tests in 171.783s

OK
```

**Review by sever-sever — APPROVED** [review]

**Comment by jestabro** [comment]
@Mergifyio backport circinus

**Pull request merged**
