### PR TITLE
T6589: Return a dict when querying information about a single interface

### PR DESCRIPTION
**Pull request by HollyGurza**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6589
* https://vyos.dev/T6587

## How to test

```
vyos@vyos:~$ sudo /usr/libexec/vyos/op_mode/interfaces.py show_summary --raw --intf-name eth0
{
    "ifname": "eth0",
    "oper_state": "up",
    "admin_state": "up",
    "addr": [
        "192.168.122.166/24"
    ],
    "description": "OUT",
    "mtu": 1500,
    "mac": "0c:89:0a:2e:00:00",
    "vrf": null
}
vyos@vyos:~$ sudo /usr/libexec/vyos/op_mode/interfaces.py show_summary --raw
[
    {
        "ifname": "eth0",
        "oper_state": "up",
        "admin_state": "up",
        "addr": [
            "192.168.122.166/24"
        ],
        "description": "OUT",
        "mtu": 1500,
        "mac": "0c:89:0a:2e:00:00",
        "vrf": null
    },
    {
        "ifname": "eth1",
        "oper_state": "up",
        "admin_state": "up",
        "addr": [
            "10.0.0.1/24"
        ],
        "description": "INSIDE",
        "mtu": 1500,
        "mac": "0c:89:0a:2e:00:01",
        "vrf": null
    },
    {
        "ifname": "eth2",
        "oper_state": "down",
        "admin_state": "up",
        "addr": [],
        "description": "",
        "mtu": 1500,
        "mac": "0c:89:0a:2e:00:02",
        "vrf": null
    },
    {
        "ifname": "eth3",
        "oper_state": "down",
        "admin_state": "up",
        "addr": [],
        "description": "",
        "mtu": 1500,
        "mac": "0c:89:0a:2e:00:03",
        "vrf": null
    },
    {
        "ifname": "lo",
        "oper_state": "unknown",
        "admin_state": "up",
        "addr": [
            "127.0.0.1/8",
            "::1/128"
        ],
        "description": "",
        "mtu": 65536,
        "mac": "00:00:00:00:00:00",
        "vrf": null
    }
]
vyos@vyos# sudo /usr/libexec/vyos/op_mode/interfaces.py show_summary --raw --intf-name eth11
Interface eth11 does not exist
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
As we return a list of dicts for multiple interfaces, shouldn't we also return an empty list for no interface and also a list for even only one interface?

**Comment by HollyGurza** [comment]
> As we return a list of dicts for multiple interfaces, shouldn't we also return an empty list for no interface and also a list for even only one interface?

I think it depends on what we are doing, searching for an object or getting information about a specific object. When we try to get information about a single object return dict looks ok, but when we try to find an object then a better return list with elements even only one or an empty list.
As I understand in this task we try to get information about a specific object, but maybe there will be better to raise an exception instead of return an empty dict when the object non exists

**Review by sever-sever — APPROVED** [review]

**Review by dmbaturin — APPROVED** [review]
@c-po I'm not sure if I understand the point abaout "no interface". When the user queries data about a single named interface and that interface is not found, we raise an exception — trying to retrieve data that doesn't exist should not return an empty list for sure, it should result in an error.

**Comment by HollyGurza** [comment]
for more convenience now i use a similar format for 
`/usr/libexec/vyos/op_mode/interfaces.py show --raw`
`/usr/libexec/vyos/op_mode/interfaces.py show_summary --raw`
`/usr/libexec/vyos/op_mode/interfaces.py show_summary_extended --raw`
`/usr/libexec/vyos/op_mode/interfaces.py show_counters --raw`

return list when we get info for many interfaces
return dict when we get info for specifies interface
raise vyos.opmode.UnconfiguredObject when specified interface don't exist

**Review by c-po — APPROVED** [review]

**Pull request merged**
