### PR TITLE
T5336: Add Swedish keyboard-layout

### PR DESCRIPTION
**Pull request by Apachez-**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5336

## Component(s) name

set system option keyboard-layout

## Proposed changes

Adding swedish keymap as system option keyboard-layout

## How to test

Switched between keymaps using "set system option keyboard-layout" and verified through console that se-latin1 is fully functional using a swedish keyboard.

Note that this is only valid when connected through local console. Connecting through SSH is usually a workaround for this issue.

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [X] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
This works, but I wonder: can we list all layouts available in the system programmatically somehow? Are there reasons not to expose them all, or it hard to do?

**Review by sever-sever — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
> This works, but I wonder: can we list all layouts available in the system programmatically somehow? Are there reasons not to expose them all, or it hard to do?

I think that is a much better approach then we currently have

**Comment by Apachez-** [comment]
> This works, but I wonder: can we list all layouts available in the system programmatically somehow? Are there reasons not to expose them all, or it hard to do?

That would be prefered but there are ALOT of them in /usr/share/keymaps/i386/ so tab completing all of them in configuration mode would be hilarious.

One way might be to add the most popular languages along with a final option named "custom" or similar where one then can define whatever one like from the /usr/share/keymaps/i386/ directories.

**Comment by dmbaturin** [comment]
I think a custom layout option is a good idea.

**Pull request merged**
