### PR TITLE
T2205: Don't change offload sg if driver is 'hv_netvsc'

### PR DESCRIPTION
**Pull request by suuei**

### CODE REVIEW

**Review by c-po — CHANGES_REQUESTED** [review]
Why is a modechange to 755 required?

**Comment by suuei** [comment]
Sorry, the permissions have been changed due to an operational error.
Is this the right way to fix it?

**Comment by jjakob** [comment]
I think the right way would be to not fail on setting these and silently continue, like https://github.com/vyos/vyos-1x/pull/272 . Not just scatter-gather but all properties set in this file. In addition I'd add a check in config mode, when a setting wants to be set on a interface that doesn't support it, print a warning to the console. (Exit status of ethtool --get-... will probably be 76, as in code from above PR, the validate function should check all of these and print warnings).

You can modify the PR by doing a rebase (`git rebase -i HEAD~`), picking the commit you want to edit, chmod the file back to the old mode,  make any changes you want to the commit, then `git commit --amend -a`, `git rebase --continue` and `git push --force`.

**Comment by c-po** [comment]
Please also check our development guidelines at https://docs.vyos.io/en/latest/contributing/development.html#submit-a-patch as there is no task id assigned to the commit.

**Comment by suuei** [comment]
Thank you for your advice.

I tried to check an interface that supports offload sg using `ethtool -k eth0` .
However, regardless of whether the interface supports changing offload sg settings, the result contained the following lines:
```
scatter-gather: on
	tx-scatter-gather: on
	tx-scatter-gather-fraglist: off [fixed]
```
Do you have any good ideas?

**Comment by jjakob** [comment]
Discussion continued at T2205

**Comment by thomas-mangin** [comment]
Yes, the behaviour was changed/reverted with
https://github.com/vyos/vyos-1x/commit/dcbd5f430907747f8c29111fbe9f5737865a7ae8

However explicit messages for known drivers are good for the users.

**Pull request closed without merging**
