### PR TITLE
reverse-proxy: T5999: Allow root for exact match in backend rule URL

### PR DESCRIPTION
**Pull request by cleopold73**
## Change Summary

Allow single / to be valid for exact match in backend rule URLs.  This allows for redirects from just a hostname.

## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5999

## Component(s) name

load-balancing reverse-proxy

## Proposed changes

Small change to the regex to allow zero or more characters instead of one or more characters in the validatior.

## How to test

The below should be accepted.

```
set load-balancing reverse-proxy backend cacti rule 10 url-path exact /
```

And generate the haproxy.cfg file to have a line like:

```
    acl 10 path  /
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
What about “begin” and “end?” as they use the same regex

**Review by sever-sever — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Comment by cleopold73** [comment]
> What about “begin” and “end?” as they use the same regex

I kind of thought about that, but all urls begin with / for begin for a single / just matches all URLs, and maybe end could be in someone's use case, but I couldn't really think up a valid one.

**Comment by c-po** [comment]
If you mean ^ and $ to indicate start/end - that’s always added under the hood

**Comment by sever-sever** [comment]
I mean nodes /start/end/exact 😊

**Pull request merged**
