### PR TITLE
proxy-ndp: T2898: Support NDP Proxy

### PR DESCRIPTION
**Pull request by jack9603301**
Stateless NAT66 relies on the ndp proxy to respond to the ndp query
request from the translated prefix address, so we need to introduce
 the ndppd service program to respond to these requests.

### CODE REVIEW

**Comment by jack9603301** [comment]
Already basically ready to merge

**Comment by jack9603301** [comment]
@c-po This function can be merged first after passing the test

**Comment by c-po** [comment]
Hi @jack9603301 thanks! Please use `get_config_dict()` when reading in the CLI as this will save us a lot of trouble in the future.

**Comment by jack9603301** [comment]
@c-po Has been migrated to `get_config_dict()`

**Comment by jack9603301** [comment]
@c-po I have modified pr

**Comment by jack9603301** [comment]
I will try to merge the service into #520

**Pull request closed without merging**
