### PR TITLE
T4748: add a CI action to check pull request title format

### PR DESCRIPTION
**Pull request by dmbaturin**
## Change Summary

Fail pull request CI is the title doesn't start with a task number.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): new CI action.

## Related Task(s)

* https://phabricator.vyos.net/T4748

## Component(s) name

GitHub CI.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by jestabro** [comment]
Looks good to me.

**Review by jestabro — APPROVED** [review]

**Comment by sarthurdev** [comment]
The [contributing doc](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) has guidelines for using the format `component: Txxxx: Text here` which would fail this regex.

**Comment by sever-sever** [comment]
It is also a good idea to update and contributing 
https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md
And is it time to EOL crux?

**Review by sever-sever — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
I'd prefer having the component name optionally in front of the Task number - would make thinks easier sortable for instance.

If we can agrree on this the regex would be: `(([a-zA-Z]+:\s)?)T\d+:\s+[^\s]+.*`

image

**Comment by jestabro** [comment]
+1 for optional component name.

**Review by jestabro — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Pull request merged**
