### PR TITLE
image: T4516: Added system image tools

### PR DESCRIPTION
**Pull request by zdc**
## Change Summary

Added system image tools

Note that this needs to be merged along with:

https://github.com/vyos/vyatta-op/pull/61
https://github.com/vyos/vyos-build/pull/352
https://github.com/vyos/vyatta-cfg-system/pull/212

for a successful build and image update.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4516

## Component(s) name

system image

## Proposed changes

This commit adds the whole set of system image tools written from the scratch in Python that allows performing all the operations on images:

* check information
* perform installation and deletion
* versions management

Also, it contains a new service that will update the GRUB menu and keep tracking its version in the future.

WARNING: The commit contains non-reversible changes. Because of boot menu changes, it will not be possible to manage images from older VyOS versions after an update.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by jestabro** [comment]
PR's needed for build; draft state until the current one is moved from draft.
https://github.com/vyos/vyatta-op/pull/61
https://github.com/vyos/vyos-build/pull/352
https://github.com/vyos/vyatta-cfg-system/pull/212

**Comment by jestabro** [comment]
Minor fixes in this repo:
https://github.com/vyos/vyos-1x/compare/current...jestabro:image-tools

To be added to this PR when complete.

**Comment by jestabro** [comment]
Comment above and repo updated.

**Comment by c-po** [comment]
@jestabro as maintainer you can also push to this branch of this PR - just a hint.

**Comment by jestabro** [comment]
Thanks, @c-po ; one minor fix left, at which point I will update the PR repo and open for review.

**Review by jestabro — DISMISSED** [review]

**Comment by sever-sever** [comment]
Has the issue of backward compatibility been resolved?
for example can I load after this to 1.3 and delete any image?

**Comment by jestabro** [comment]
One can _not_ mange system images from earlier images, after the update, as the grub files have been reorganized. This is a long needed change, so we should discuss the issue. One can consider adding tools to save and rebuild the original grub files for an image, however, moving forward will prevent relying on old tools.

**Comment by jestabro** [comment]
Move to draft for discussion and testing.

**Comment by jestabro** [comment]
A simple compatibility layer has been added to support image management with legacy tools from older images after an update. Other minor fixes are added. There is a short list below of remaining missing features, all of which should be simple to implement. For that and the need for independent testing, it remains in draft temporarily --- note that once in rolling, it is non-trivial to back out of changes of this order; therefore review, testing, and discussion is needed. Despite the clear need for circumspection, the image-tools revision provides a major step forward from the legacy framework.

Still pending:
- [x] (1) restore RAID 1 install option to 'image install' (slightly tricky)
        -- needs a final round of testing
- [x] (2) add compatibility with legacy RAID 1 installs
- [x] (3) new images should use
/usr/libexec/vyos/system/standalone_root_pw_reset
instead of
/opt/vyatta/sbin/standalone_root_pw_reset
(easy)
- [ ] (4) restore support for Xen installs (presumed easy, but I haven't looked at it yet)
- [x] (5) fix issues observed by @sever-sever and others in tests:
        - missing ability to select from numbered list in set (default)/delete image
        - misleading error message on attempt to update to 1.2.x series (1.3.x raises DowngradingImageTools exception)
        - unnecessary prompt to confirm on set default
        - need to fix wording of some messages
- [x] (6) check messages/prompts and update vyos-build/scripts/check-qemu-install

**Review by sever-sever — APPROVED** [review]
Overall it works very well! I couldn't break it in my tests.

**Review by dmbaturin — APPROVED** [review]

**Comment by jestabro** [comment]
@sever-sever pointed out a few issues/questions that will be added to the checklist above.

**Comment by jestabro** [comment]
After merging, remaining issues of (1) non-interactive runs of add/delete image, resp. (2) check compatibility with XCP-NG images, will be handled in:
https://vyos.dev/T5751
https://vyos.dev/T5752

**Pull request merged**
