### PR TITLE
op mode: T5582: Add 'force ntp synchronization'

### PR DESCRIPTION
**Pull request by dmbaturin**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5582

## Component(s) name

Op mode.

## Proposed changes

Add a command to force NTP sync.

## How to test

```
run force ntp synchronization
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by indrajitr** [comment]
Wondering if this should be wrapped via `show_ntp.sh` to make it vrf aware.

**Review by sever-sever — APPROVED** [review]

**Comment by dmbaturin** [comment]
@indrajitr Oh, chronyd doesn't seem to have an option to explicitly synchronize with any particular server, only to force ab abrupt synchronization instead of gradual clock slewing. Where it will get the time and through which VRF is determined by the config and the user can't influence it.

**Comment by indrajitr** [comment]
@dmbaturin: Oh true, I didn't think about that aspect. Thank you!

**Comment by c-po** [comment]
> Wondering if this should be wrapped via `show_ntp.sh` to make it vrf aware.

No need to add it to `show_ntp.sh` as this can also be done as we have it for `ping`. The VRF tagNode follows the command `force ntp synchronization vrf <name>` and the VR fis then passed on the commandline: `<command>sudo ip vrf exec "$5" chronyc makestep</command>`

Other then that, a very good addition

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Review by c-po — APPROVED** [review]

**Pull request merged**
