### PR TITLE
vyos.ethtool: T6070: fix EEE reading the incorrect status line

### PR DESCRIPTION
**Pull request by up-n-atom**
EEE enabled status is on the 2nd line of ethtool output and not the 3rd. Subsequently, reading the 3rd line was causing an out-of-bounds access for the bnx2x driver as well.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T6070

## Related PR(s)

N/A

## Component(s) name

ethernet

## Proposed changes

Same as commit message

## How to test

```
ethtool --show-eee eth0
```

## Smoketest result

N/A

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I wonder why ghe artifical data used while testing worked out?

https://github.com/vyos/vyos-1x/pull/2689

Any idea? I fed back the ethtool and hardcoded the result for validation testing, as I do not have an EEE capable NIC

**Comment by up-n-atom** [comment]
It certainly wouldn't error out with those tests cases because it would be reading the `Tx LPI: ...` line but should have always returned False or disabled.

Were you possibly including the command into the output? ie. `$ sudo ethtool --show-eee eno1`

**Review by dmbaturin — CHANGES_REQUESTED** [review]
I have two (plus one) concerns about all such code.

1. Without an example of the output in question, it's completely impossible to judge the code when reading it unless you remember the output by heart (unlikely) or have a chance to easily test the command (also not always possible).
I believe we must always include examples.

2. Do you think we can generalize that code to avoid hardcoded line numbers? That would be perfect because we never know how it may change.

3. With `ethtool` specifically: is there a specific reason why we still parse its human-readable output instead of using `ethtool --json`? Can we start doing it from this case?

**Comment by up-n-atom** [comment]
As a first time contributor, I agree fully but I'm definitely not the person to go about that. From my perspective, I was actually quite surprised to witness output parsing rather than netlink being utilized for such purposes but that is neither here nor there.

**Comment by dmbaturin** [comment]
I don't mind merging the emergency fix now, but I wanted to draw attention to the issue: I think we all should work together to switch to `--json` here, since it will greatly simplify the script.

**Comment by c-po** [comment]
> I don't mind merging the emergency fix now, but I wanted to draw attention to the issue: I think we all should work together to switch to `--json` here, since it will greatly simplify the script.

Unfortunately `ethtool` is not feature on par when using JSON output. It‘s only implemented for a subset of commands.

https://git.kernel.org/pub/scm/network/ethtool/ethtool.git/tree/ethtool.c and search for `.json` - maybe we should spend time in adding missing JSON support at least for the features we use.

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
Reviewed the original PR and output used for testing, seems like an off-by-one error in the initial implementation.

We should come up with a JSON patch for EEE to ethtool and until it‘s upstreamed can use our own build.

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
