### PR TITLE
op-mode: T6694: Move some op-mode commands to the "execute" family

### PR DESCRIPTION
**Pull request by natali-rs1985**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): command renaming

## Related Task(s)

* https://vyos.dev/T6694
## Component(s) name

op mode

## Proposed changes

Rename commands:
```force netns```—  to ```execute shell netns```.
```force vrf```—  to ```execute shell vrf```.
```force owping``` —  to ```execute owping```.
```force twping``` — to ```execute twping```.
```monitor bandwidth-test``` —  to ```execute bandwidth-test```. 
```telnet``` — to ```execute telnet```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
If you move telnet in op-mode, any reason to not also use ssh?

**Comment by natali-rs1985** [comment]
> If you move telnet in op-mode, any reason to not also use ssh?

You mean to add op-mode command `execute ssh user [username] host [host]`?

**Comment by natali-rs1985** [comment]
> > If you move telnet in op-mode, any reason to not also use ssh?
> 
> You mean to add op-mode command `execute ssh user [username] host [host]`?

**Review by dmbaturin — APPROVED** [review]

**Comment by dmbaturin** [comment]
I wouldn't be against moving SSH to `execute` right away, although we can also do it later as well. We will have more candidates for moving between command families in any case, this certainly will not be the last  PR in that op mode reorganization series.

**Review by c-po — APPROVED** [review]

**Pull request merged**
