### PR TITLE
http-api: T4749: transition to config_dict for conf_mode http-api.py

### PR DESCRIPTION
**Pull request by jestabro**
## Change Summary

Use config_dict for access to config settings. This is the standard modernization, and is useful for merging the defaultValue to be added for default authentication method (key | token). One needs a bit of manipulation of the http_api dict to maintain backwards compatibility of the generated /etc/vyos/http-api.conf file.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T4749
* https://phabricator.vyos.net/T4574

## Component(s) name

http-api

## How to test

The test is that nothing should have changed in behavior of REST form/json or graphql requests.

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [X] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by jestabro** [comment]
Convert to draft to check addition of defaultValue.

**Review by c-po — APPROVED** [review]

**Review by sever-sever — APPROVED** [review]
Maybe in another PR but maybe it will be better to name the option in the CLI as `graphql` instead of `gql`

**Comment by jestabro** [comment]
@sever-sever I agree with you on that.

**Comment by c-po** [comment]
> Maybe in another PR but maybe it will be better to name the option in the CLI as `graphql` instead of `gql`

+1

**Pull request merged**
