### PR TITLE
container: T5407: increase priority before protocol static

### PR DESCRIPTION
**Pull request by jvoss**
## Change Summary
Increase the priority of container configuration to `450` to before protocols/static (`480`).

This is necessary when static routes are pointed at container networks (`pod-<NETWORK_NAME>`). Otherwise configuration validation fails on boot and the entire static route stanza is dropped from the configuration.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5407

## Component(s) name

* container

## Proposed changes
This PR updates the priority of container configuration to come before protocol/static. This ensures that any container networks are created prior to any potential static route pointed at a container network.

Prior to this change, after reboot, any static route configured using an interface `pod-<NETWORK-NAME>` fails validation and static routes are rejected from the configuration. This presents a configuration error message to users when entering configuration mode. Additionally no static routes are installed.

## How to test
1. Configure a container network and container as well as a static route:

```
container {
  name test {
     image ubuntu:20.04
     network TEST {
     }
  }
  network TEST {
     prefix 192.168.0.0/24
  }
}
[...]
protocols {
     static {
         route 192.168.0.0/24 {
             interface pod-TEST {
             }
         }
     }
}
```

2. Validate the route was installed:

```
jvoss@test-R1:~$ show ip route static
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

S>* 192.168.1.0/24 [1/0] is directly connected, pod-TEST, weight 1, 00:00:45
```

3. Reboot

4. Validate the static route persisted in the configuration (prior to this change it is missing)

```
jvoss@test-R1# show protocols static 
 route 192.168.1.0/24 {
     interface pod-TEST {
     }
 }
[edit]
```

6. Validate the route was installed:

```
jvoss@test-R1:~$ show ip route static
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

S>* 192.168.1.0/24 [1/0] is directly connected, pod-TEST, weight 1, 00:00:57
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sever-sever** [comment]
Why not change this priority only for “container networks” and leave original priority for other container nodes?
There was time when container images loaded during the boot. If you change the whole priority it will be completely impossible to download images before static routes. In case if we will return it in the future.

**Review by sever-sever — CHANGES_REQUESTED** [review]
You can set priority only for container networks and leave original priority for other container configuration

**Comment by jvoss** [comment]
I agree and think that would be a better solution. However, is it possible for the nested network tag node to have a priority other than it's "container" parent node?

I was working under the assumption that all container configuration had a singular priority option.

**Comment by sever-sever** [comment]
> I agree and think that would be a better solution. However, is it possible for the nested network tag node to have a priority other than it's "container" parent node?
> 
> I was working under the assumption that all container configuration had a singular priority option.

It is possible and we have it in some parts of interfaces and other nodes
Set priority under required section

**Comment by jvoss** [comment]
> It is possible and we have it in some parts of interfaces and other nodes
> 
> Set priority under required section

Excellent. I will update and test. Thanks!

**Comment by sever-sever** [comment]
You can get all priorities with
```
/opt/vyatta/sbin/priority.pl
```

**Comment by c-po** [comment]
I think switching priorities only "masks" the error. We have a similar situation for static routes and DHCP. 
Actually routing to a container interface was never considered (yet) - users are very creative, thanks for this.

A Workaround would be:

`set protocols static route 192.168.0.0/24 next-hop 192.168.0.1` as the container "gateway" will always be at the first host address of the given prefix.

Would this work for you?

**Comment by jvoss** [comment]
> `set protocols static route 192.168.0.0/24 next-hop 192.168.0.1` as the container "gateway" will always be at the first host address of the given prefix.

Unfortunately this does not work for my use case (which is loosely related to T5398). I have a static VRF-leaked route to a container in the default VRF. 

While your suggested configuration is valid and rendered to FRR correctly, the static route never appears in the routing table. However using an interface does.

**Comment by c-po** [comment]
You know you can add static routes that leak to a VRF?
Can you paste the real config? I do not see a VRF in your given example

**Comment by jvoss** [comment]
> You know you can add static routes that leak to a VRF? Can you paste the real config? I do not see a VRF in your given example

I am aware. This is what I am doing:

```
vrf {
    name CUSTOMER {
        protocols {
            static {
                route 172.31.6.0/24 {
                    description "route-leak services container network"
                    interface pod-SERVICES {
                        vrf default
                    }
                }
            }
        }
        table 1042
    }
}
```

There is an inverse static route outside of the VRF that points to the CUSTOMER VRF. The configuration works great until reboot because of the issues in this PR.

**Comment by jvoss** [comment]
@sever-sever fwiw - I did attempt to adjust the priority for only the node `container/network` built a package, installed and rebooted. Unfortunately this approach was unsuccessful:

```
# /opt/vyatta/sbin/priority.pl

[...]
450 container/network
[...]
480 protocols/static
[...]
```

The container network was created fine on startup:
```
jvoss@test-R1:~$ show ip route connected 
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

[...omitted...]
C>* 192.168.1.0/24 is directly connected, pod-TEST, 02:07:42
```

However the route is still rejected in the configuration load somewhere I have yet to determine:

```
jvoss@test-R1:~$ config
WARNING: There was a config error on boot: saving the configuration now could overwrite data.
You may want to check and reload the boot config
[edit]
jvoss@test-R1# show vrf name TEST protocols static
Configuration under specified path is empty
[edit]
jvoss@test-R1# load
Loading configuration from 'config.boot'
Load complete. Use 'commit' to make changes effective.
[edit]
jvoss@test-R1# compare
[vrf name TEST protocols]
+ static {
+     route 192.168.1.0/24 {
+         description "test"
+         interface pod-TEST {
+             vrf "default"
+         }
+     }
+ }

[edit]
```

And obviously not installed:
```
jvoss@test-R1:~$ show ip route vrf TEST static 
jvoss@test-R1:~$ 
```

Committing the pending configuration above installs the route:
```
jvoss@test-R1# compare
[vrf name TEST protocols]
+ static {
+     route 192.168.1.0/24 {
+         description "test"
+         interface pod-TEST {
+             vrf "default"
+         }
+     }
+ }

[edit]
jvoss@test-R1# commit
[edit]
jvoss@test-R1# run show ip route vrf TEST static
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, F - PBR,
       f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup
       t - trapped, o - offload failure

VRF TEST:
S>* 192.168.1.0/24 [1/0] is directly connected, pod-TEST (vrf default), weight 1, 00:00:29
[edit]
```

I suspect the reason why this does not work is because the container network is not actually up until an associated container is. Therefore it would still fail validation when the interface is verified to exist (because it doesn't yet).

**Comment by c-po** [comment]
Re-thinking this change in priority might actually be okay. Here is why:

As all our containers **must** be pre-loaded by the `add container image` command, there is no network connectivity required when booting up the system. As long as this design decision stays I don't see any ricochets.

**Review by c-po — APPROVED** [review]

**Pull request merged**
