### PR TITLE
accel-ppp: T6187: use correct CPU counts adjusted for SMT

### PR DESCRIPTION
**Pull request by dmbaturin**
## Change Summary

Use `vyos.cpu.get_core_count()` to get the correct number of physical cores instead of halving the number of apparent logical cores — halving `os.cpu_count()` makes the system appear to have fewer CPUs than it really has if SMT is disabled.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): optimization.

## Component(s) name

Mainly accel-ppp

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by Apachez-** [comment]
Something that not just affect accel-ppp is the use of E- and P-cores (mainly for Intel CPU's but I guess its a matter of time before AMD will also do that).

Can E-cores be avoided (by configuration) or should they be counted as a 0.5 core or such?

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
> Something that not just affect accel-ppp is the use of E- and P-cores (mainly for Intel CPU's but I guess its a matter of time before AMD will also do that).
> 
> Can E-cores be avoided (by configuration) or should they be counted as a 0.5 core or such?

It's the users choice and thus responsibility if you use a system with E and P cores or not. Introducing a factor feels wrong - how should it be? Is 0.5 the right value? What would happen e.g. with 20th Gen processors, will the factor be 0.66 then? We should count them all as one and hand this one off to the user.

**Comment by Apachez-** [comment]
The factor could be part of the configuration to make it forward compatible.

Like having an "e-core_weight" to default to lets say 0.5 and a "p-core_weight" to default to 1.0.

**Comment by dmbaturin** [comment]
@mergifyio backport sagitta

**Pull request merged**
