### PR TITLE
T5133: Add description for firewall group entries

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add description for firewall group entries
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5133

## Component(s) name

firewall
## How to test
```
set firewall group network-group sn network 172.16.99.0/24 description first
set firewall group network-group sn1 network 172.16.101.0/24 description second
set firewall group network-group sn1 include sn
```
check sets:
```
vyos@r4# sudo nft list sets
...
table ip filter {
}
table ip vyos_filter {
	set N_sn {
		type ipv4_addr
		flags interval
		auto-merge
		elements = { 172.16.99.0/24 }
	}
	set N_sn1 {
		type ipv4_addr
		flags interval
		auto-merge
		elements = { 172.16.99.0/24, 172.16.101.0/24 }
	}
}
...
```

## Smoketest result
```
vyos@r4:~$ /usr/libexec/vyos/tests/smoke/cli/test_firewall.py
test_bridge_basic_rules (__main__.TestFirewall.test_bridge_basic_rules) ... ok
test_flow_offload (__main__.TestFirewall.test_flow_offload) ... ok
test_geoip (__main__.TestFirewall.test_geoip) ... ok
test_groups (__main__.TestFirewall.test_groups) ... ok
test_ipv4_advanced (__main__.TestFirewall.test_ipv4_advanced) ... ok
test_ipv4_basic_rules (__main__.TestFirewall.test_ipv4_basic_rules) ... ok
test_ipv4_dynamic_groups (__main__.TestFirewall.test_ipv4_dynamic_groups) ... ok
test_ipv4_mask (__main__.TestFirewall.test_ipv4_mask) ... ok
test_ipv4_state_and_status_rules (__main__.TestFirewall.test_ipv4_state_and_status_rules) ... ok
test_ipv4_synproxy (__main__.TestFirewall.test_ipv4_synproxy) ... ok
test_ipv6_advanced (__main__.TestFirewall.test_ipv6_advanced) ... ok
test_ipv6_basic_rules (__main__.TestFirewall.test_ipv6_basic_rules) ... ok
test_ipv6_dynamic_groups (__main__.TestFirewall.test_ipv6_dynamic_groups) ... ok
test_ipv6_mask (__main__.TestFirewall.test_ipv6_mask) ... ok
test_nested_groups (__main__.TestFirewall.test_nested_groups) ... ok
test_source_validation (__main__.TestFirewall.test_source_validation) ... ok
test_sysfs (__main__.TestFirewall.test_sysfs) ... ok
test_zone_basic (__main__.TestFirewall.test_zone_basic) ... ok
test_zone_flow_offload (__main__.TestFirewall.test_zone_flow_offload) ... ok

----------------------------------------------------------------------
Ran 19 tests in 130.029s

OK
vyos@r4:~$ 

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by GurliGebis** [comment]
Is it possible to print the description in the nft output some how?
That would make debugging stuff easier 🙂

**Comment by c-po** [comment]
I‘d rather add tve description element to the network group itself, as this heavily clutters the config.

If one really wants a per address description, a comment can be used.

**Comment by sever-sever** [comment]
> I‘d rather add tve description element to the network group itself, as this heavily clutters the config.
> 
> If one really wants a per address description, a comment can be used.

Should we close it as **wontfix**?
It could be useful if you have 100 addresses for the address-group and  for some of them you set a description.

**Comment by c-po** [comment]
```
cpo@LR1.wue3# set firewall group address-group test123 description foo
cpo@LR1.wue3# set firewall group address-group test123 address 1.2.3.4
cpo@LR1.wue3# comment firewall group address-group test123 address baz
[edit]
cpo@LR1.wue3# show firewall
+group {
+    address-group test123 {
+        /* baz */
+        address 1.2.3.4
+        description foo
+    }
+}
```
Moving the address leafNode to a tagNode will clutter the configuration.

**Pull request closed without merging**
