### PR TITLE
dhcpv6-server: T3379: Add option global-parameters

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add options for configuration "global-parameters" name-server.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

T3379
## Component(s) name

dhcpv6-server
## Proposed changes

Add ability to configure global option "name-server" for dhcpv6-server,
## How to test
VyOS configuration
```
set interfaces ethernet eth1 address '2001:db8::1/48'
set service dhcpv6-server global-parameters name-server '2001:db8::1'
set service dhcpv6-server global-parameters name-server '2001:db8::2'
set service dhcpv6-server shared-network-name SHARED subnet 2001:db8::/48
```
dhcpdv6.conf
```

log-facility local7;

option dhcp6.name-servers 2001:db8::1;
option dhcp6.name-servers 2001:db8::2;

# Shared network configration(s)
shared-network SHARED {
    subnet6 2001:db8::/48 {
    }
    on commit {
        set shared-networkname = "SHARED";
    }
}


```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
@sever-sever I am so not a fan of passing down raw configuration variables from the CLI into the daemon. There is no way in verifying that input and if a user configures something wrong - the daemon will not start and VyOS is blamed.

We have this option in DHCP and OpenVPN since the early days and we should not repeat that old wrong (in my opinion) decission. Please rather add a proper CLI node to support configuring global DNS servers.

**Comment by sever-sever** [comment]
>  Please rather add a proper CLI node to support configuring global DNS servers.

@c-po done.

**Comment by c-po** [comment]
Can you please also extend https://github.com/vyos/vyos-1x/blob/current/smoketest/scripts/cli/test_service_dhcpv6-server.py for this new CLI command?

**Comment by sever-sever** [comment]
> Can you please also extend https://github.com/vyos/vyos-1x/blob/current/smoketest/scripts/cli/test_service_dhcpv6-server.py for this new CLI command?

Done.

**Pull request merged**
