### PR TITLE
op-mode: T2874: Add new utill for monitor mtu-check

### PR DESCRIPTION
**Pull request by sever-sever**

### CODE REVIEW

**Comment by c-po** [comment]
Is this a periodic check which runs until it’s aborted by Ctrl-C?

If not it should not be placed under monitor. Monitor commands are run in foreground (or background) constantly so I wonder if this is the case for this command.

**Comment by sever-sever** [comment]
> Is this a periodic check which runs until it’s aborted by Ctrl-C?

No, it is.

It is difficult to find the best place for it.
It more as ping/traceroute

Separate command in the main op-mode menu?

```
mtu-check
show mtu-check
discovery mtu-check
```
I can't find the best place.

**Comment by c-po** [comment]
show mtu host x.x.x.x interface foo? or force?

**Review by c-po — CHANGES_REQUESTED** [review]
Your commit contains unwanted files (vyshim and mkjson.o) please remove them.

I also would use force subsystem over show in op-mode.

**Pull request closed without merging**
