### PR TITLE
T1981: Fix ipv6 route-map for bgp

### PR DESCRIPTION
**Pull request by hameno**
## Change Summary
Add template to generate zebra "ipv6 protocol bgp route-map xxx"

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T1981

## Component(s) name

bgp

## How to test
```
set policy route-map SET-SRC rule 10 action 'permi'
set policy route-map SET-SRC rule 10 set src 2001:db8::1
set protocols bgp route-map 'SET-SRC'
```
Check zebra
```
vyos@r14# vtysh -c "show run zebra"
Building configuration...

Current configuration:
!
frr version 8.4.2
frr defaults traditional
hostname debian
log syslog
log facility local7
hostname r14
service integrated-vtysh-config
!
route-map SET-SRC permit 10
 set src 2001:db8::1
exit
!
ipv6 protocol bgp route-map SET-SRC
!
end
[edit]
vyos@r14# 
```

## Checklist:

- [X] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [X] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [X] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Hoe does it behave if both IPv4 and IPv6 route maps are present?

**Comment by hameno** [comment]
I only tested this by manually applying `ipv6 protocol bgp route-map SET-SRC` in vtysh. It then correctly applied the source IP to the kernel routes (checked with `vtysh -c 'show route-map SET-SRC'`  and `ip -6 route show`) 
Not sure how I can test this change (not sure how to build it from my fork)

**Comment by c-po** [comment]
Turns out this change is more complex the initially thought.
Your change will applly the same route-map used in IPv4 to IPv6, too but that might be something users might think is wrong or would do it differently.

This not only applies to BGP but also to ISIS and Babel routing protocols.

I propose adjusting the CLI for all routing protocols from

`set protocol bgp route-map foo` -> `set protocol bgp zebra ip route-map foo`

Then we can have: `set protocol bgp zebra ipv6 route-map bar`

OSPF would change form `set protocol ospf route-map foo` -> `set protocol ospf zebra ip route-map foo`

`zebra` could re replaced by `kernel` to make it more generic.

**Comment by c-po** [comment]
Closing this PR in favor of https://vyos.dev/T5150 which is currently in progress and will be PR'd soon

**Comment by c-po** [comment]
See new implementation in https://github.com/vyos/vyos-1x/pull/1943

**Pull request closed without merging**
