### PR TITLE
bgp: T2771: Adding address families in BGP

### PR DESCRIPTION
**Pull request by Cheeze-It**
In this commit we add more address families within
BGP. This should bring VyOS the ability to enable
the rest of the capabilities within FRR.

## Change Summary

We are going to be adding the following address families here.

IPv4 Labeled Unicast
IPv4 Multicast
IPv4 VPN
IPv4 Flowspec
IPv6 Labeled Unicast
IPv6 Multicast
IPv6 VPN
IPv6 Flowspec

The administrative distances are also added for existing and new address families
including a check to make sure everything is properly commit and not missing
when specifying said distances.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T2771

## Component(s) name

BGP

## How to test

```
Here's the configuration that was added:

set protocols bgp 1 address-family ipv4-flowspec local-install interface 'lo'
set protocols bgp 1 address-family ipv4-flowspec local-install interface 'eth0'
set protocols bgp 1 address-family ipv4-multicast distance external '25'
set protocols bgp 1 address-family ipv4-multicast distance internal '30'
set protocols bgp 1 address-family ipv4-multicast distance local '35'
set protocols bgp 1 address-family ipv4-multicast distance prefix 10.0.0.0/24 distance '110'
set protocols bgp 1 address-family ipv4-unicast distance external '10'
set protocols bgp 1 address-family ipv4-unicast distance internal '15'
set protocols bgp 1 address-family ipv4-unicast distance local '20'
set protocols bgp 1 address-family ipv4-unicast distance prefix 10.0.0.0/24 distance '110'
set protocols bgp 1 address-family ipv6-multicast distance external '45'
set protocols bgp 1 address-family ipv6-multicast distance internal '50'
set protocols bgp 1 address-family ipv6-multicast distance local '55'
set protocols bgp 1 address-family ipv6-multicast distance prefix 2001::/64 distance '110'
set protocols bgp 1 address-family ipv6-unicast distance external '60'
set protocols bgp 1 address-family ipv6-unicast distance internal '65'
set protocols bgp 1 address-family ipv6-unicast distance local '70'
set protocols bgp 1 address-family ipv6-unicast distance prefix 2001::/64 distance '110'
set protocols bgp 1 neighbor 10.0.0.1 address-family ipv4-flowspec
set protocols bgp 1 neighbor 10.0.0.1 remote-as '1'
set protocols bgp 1 neighbor 10.0.0.2 address-family ipv4-vpn
set protocols bgp 1 neighbor 10.0.0.2 remote-as '2'
set protocols bgp 1 neighbor 10.0.0.3 address-family ipv4-labeled-unicast
set protocols bgp 1 neighbor 10.0.0.3 remote-as 3
set protocols bgp 1 neighbor 10.0.0.4 address-family ipv4-unicast
set protocols bgp 1 neighbor 10.0.0.4 remote-as '4'
set protocols bgp 1 neighbor 10.0.0.5 address-family ipv4-multicast
set protocols bgp 1 neighbor 10.0.0.5 remote-as '5'
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast allowas-in number '5'
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast as-override
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast attribute-unchanged as-path
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast attribute-unchanged med
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast attribute-unchanged next-hop
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast maximum-prefix '5000'
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast nexthop-self
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast route-server-client
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast soft-reconfiguration inbound
set protocols bgp 1 neighbor 10.0.0.55 address-family ipv4-unicast weight '100'
set protocols bgp 1 neighbor 10.0.0.55 remote-as '500'
set protocols bgp 1 neighbor 10.0.0.55 timers connect '10'
set protocols bgp 1 neighbor 10.0.0.55 timers holdtime '20'
set protocols bgp 1 neighbor 10.0.0.55 timers keepalive '30'
set protocols bgp 1 neighbor 2001::1 address-family ipv6-flowspec
set protocols bgp 1 neighbor 2001::1 remote-as '1'
set protocols bgp 1 neighbor 2001::2 address-family ipv6-vpn
set protocols bgp 1 neighbor 2001::2 remote-as '2'
set protocols bgp 1 neighbor 2001::3 address-family ipv6-labeled-unicast
set protocols bgp 1 neighbor 2001::3 remote-as '3'
set protocols bgp 1 neighbor 2001::4 address-family ipv6-unicast
set protocols bgp 1 neighbor 2001::4 remote-as '4'
set protocols bgp 1 neighbor 2001::5 address-family ipv6-multicast
set protocols bgp 1 neighbor 2001::5 remote-as '5'
set protocols bgp 1 parameters always-compare-med
set protocols bgp 1 parameters bestpath as-path multipath-relax
set protocols bgp 1 parameters bestpath compare-routerid
set protocols bgp 1 parameters bestpath med missing-as-worst
set protocols bgp 1 parameters cluster-id '10.0.0.67'
set protocols bgp 1 parameters dampening half-life '30'
set protocols bgp 1 parameters dampening max-suppress-time '200'
set protocols bgp 1 parameters dampening re-use '10000'
set protocols bgp 1 parameters dampening start-suppress-time '15000'
set protocols bgp 1 parameters default local-pref '100'
set protocols bgp 1 parameters deterministic-med
set protocols bgp 1 parameters distance global external '170'
set protocols bgp 1 parameters distance global internal '170'
set protocols bgp 1 parameters distance global local '170'
set protocols bgp 1 parameters graceful-restart stalepath-time '300'
set protocols bgp 1 parameters log-neighbor-changes
set protocols bgp 1 parameters network-import-check
set protocols bgp 1 parameters no-client-to-client-reflection
set protocols bgp 1 parameters no-fast-external-failover
set protocols bgp 1 parameters router-id '10.0.0.67'
set protocols bgp 1 peer-group testing remote-as '500'
delete protocols bgp 1 neighbor 10.0.0.3
```

```
Here's how the actual configuration looks under FRR:

vyos@vyos:~$ vtysh -c "show run bgp"
Building configuration...

Current configuration:
!
frr version 7.5.1-20210317-02-g301dee3fd
frr defaults traditional
hostname debian
log syslog
log facility local7
hostname vyos
service integrated-vtysh-config
!
router bgp 1
 no bgp fast-external-failover
 bgp router-id 10.0.0.67
 bgp log-neighbor-changes
 bgp always-compare-med
 no bgp ebgp-requires-policy
 no bgp client-to-client reflection
 bgp cluster-id 10.0.0.67
 bgp deterministic-med
 bgp graceful-restart stalepath-time 300
 bgp bestpath as-path multipath-relax
 bgp bestpath compare-routerid
 bgp bestpath med missing-as-worst
 neighbor testing peer-group
 neighbor testing remote-as 500
 neighbor 10.0.0.1 remote-as 1
 neighbor 10.0.0.2 remote-as 2
 neighbor 10.0.0.4 remote-as 4
 neighbor 10.0.0.5 remote-as 5
 neighbor 10.0.0.55 remote-as 500
 neighbor 10.0.0.55 timers 6 20
 neighbor 10.0.0.55 timers connect 10
 neighbor 2001::1 remote-as 1
 neighbor 2001::2 remote-as 2
 neighbor 2001::3 remote-as 3
 neighbor 2001::4 remote-as 4
 neighbor 2001::5 remote-as 5
 !
 address-family ipv4 unicast
  distance bgp 10 15 20
  distance 110 10.0.0.0/24
  bgp dampening 30 10000 15000 200
  neighbor 10.0.0.55 next-hop-self
  neighbor 10.0.0.55 soft-reconfiguration inbound
  neighbor 10.0.0.55 maximum-prefix 5000
  neighbor 10.0.0.55 route-server-client
  neighbor 10.0.0.55 allowas-in 5
  neighbor 10.0.0.55 weight 100
  neighbor 10.0.0.55 attribute-unchanged as-path next-hop med
 exit-address-family
 !
 address-family ipv4 multicast
  distance bgp 25 30 35
  distance 110 10.0.0.0/24
  neighbor 10.0.0.5 activate
 exit-address-family
 !
 address-family ipv4 vpn
  neighbor 10.0.0.2 activate
 exit-address-family
 !
 address-family ipv4 flowspec
  neighbor 10.0.0.1 activate
  local-install eth0
  local-install lo
 exit-address-family
 !
 address-family ipv6 unicast
  distance bgp 60 65 70
  distance 110 2001::/64
  neighbor 2001::4 activate
 exit-address-family
 !
 address-family ipv6 multicast
  distance bgp 45 50 55
  distance 110 2001::/64
  neighbor 2001::5 activate
 exit-address-family
 !
 address-family ipv6 labeled-unicast
  neighbor 2001::3 activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor 2001::2 activate
 exit-address-family
 !
 address-family ipv6 flowspec
  neighbor 2001::1 activate
 exit-address-family
!
line vty
!
end
```

There however *IS* a problem that is an FRR problem. Therefore I have to ask that we hold onto this addition until we are able to have FRR fix the problem that is seen [here](https://github.com/FRRouting/frr/issues/8246). Please don't merge yet.

Also, I will be needing more help for smoketests. I figure it might be easier to add said smoketests separately but I am unsure.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

I will add documentation later as I just don't want to blast all of that in one go. But I will be doing that.

### CODE REVIEW

**Comment by sever-sever** [comment]
Thanks. Great work!!!
How to generate a flowspec route? How it will work with a firewall for blocking traffic?

**Comment by Cheeze-It** [comment]
> Thanks. Great work!!!
> How to generate a flowspec route? How it will work with a firewall for blocking traffic?

Thanks my friend :)

I actually am unsure if in FRR we can *do* a route addition into flowspec. Usually one uses something like ExaBGP or similar to generate said route. Adding into FRR for VyOS will allow for VyOS (I hope) to actually receive and redistribute flowspec routes. Like we can use FRR as a route reflector that can also reflect flowspec. I *think* the way that we make a flowspec route work with an interface is within the "local-interface" command. However I still am unsure if that will properly work. This will require a lot of testing to see if we *think* it works the way it seems to be laid out in the FRR CLI. At the very least though at least VyOS should be able to speak flowspec for route reflection duties.

**Comment by c-po** [comment]
Hi @Cheeze-It,

I know the FRR error on commit, is there any workaround for this like a reduced config for only multicast?
If so, can you please provide smoketests for this new feature as this will make every developers life a ton easier in the future.

**Comment by Cheeze-It** [comment]
> Hi @Cheeze-It,
> 
> I know the FRR error on commit, is there any workaround for this like a reduced config for only multicast?
> If so, can you please provide smoketests for this new feature as this will make every developers life a ton easier in the future.

We can remove the specific offending config which is IPv4 Labeled Unicast. Everything else works.

Adding the smoketest will be something I will need help on. But the configuration I have listed above we can use as some of the smoketests as it's fairly complete. There's more we can add I just haven't been able to add more yet. But I will do so I hope within the week.

**Comment by c-po** [comment]
Above configuration can very easy be transformed and used in the BGPs smoketest https://github.com/vyos/vyos-1x/blob/current/smoketest/scripts/cli/test_protocols_bgp.py. Adding such a big feature without a proper testcase will be bad in the future when we do all kind of refactoring - just PM me if you need some more help.

**Comment by Cheeze-It** [comment]
Added another check to the protocols_bgp.py. Seems we have a new one. On a BGP neighbor we can't have override-capability and strict-capability-match enabled at the same time. I added a verification check on it.

**Comment by c-po** [comment]
This one might need a rebase after #793

**Comment by Cheeze-It** [comment]
Closing PR, will rebase and re-PR.

**Pull request closed without merging**
