### PR TITLE
smoketests: T5887: remove IXGB driver

### PR DESCRIPTION
**Pull request by c-po**
From Kernel commit e485f3a6eae0 ("ixgb: Remove ixgb driver")

There are likely no users of this driver as the hardware has been discontinued since 2010. Remove the driver and all references to it in documentation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe): discontinued driver

## Related Task(s)

* https://vyos.dev/T5887

## Related PR(s)

* https://github.com/vyos/vyos-build/pull/482

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by dmbaturin — APPROVED** [review]
If IGB and IXGBE drivers can handle all hardware that the IXGB driver was used for, I think this is perfectly safe.

If there's no way to move forward without removing it, we'll need to include deprecation warnings for the affected hardware in 1.4 release notes.

**Review by sever-sever — APPROVED** [review]

**Comment by sarthurdev** [comment]
It appears no other drivers handle the hardware (https://cateee.net/lkddb/web-lkddb/IXGB.html). I wouldn't think this hardware is in use given it only handles a couple of PCI-X XFP intel cards.

**Comment by c-po** [comment]
> It appears no other drivers handle the hardware (https://cateee.net/lkddb/web-lkddb/IXGB.html). I wouldn't think this hardware is in use given it only handles a couple of PCI-X XFP intel cards.

I have the very same opinion, it only affects Intel 82597EX PCI-X cards with their CX4, SR and LR models

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
