### PR TITLE
ndptool: T2706: Fix the sending function in NDP protocol monitoring

### PR DESCRIPTION
**Pull request by jack9603301**

### CODE REVIEW

**Comment by c-po** [comment]
Please explain in the commit message why this is moved and also what is the benefit of faking those ndp messages. I wonder why this is needed.

**Comment by c-po** [comment]
When emitting commands monitor is definately the wrong place

**Comment by jack9603301** [comment]
Maybe you can give me a proper order?

**Comment by jack9603301** [comment]
I will close this PR because no suitable place has been found and the send NDP function has been removed

**Comment by c-po** [comment]
Why not imagine of a proper place yourself?

**Comment by jack9603301** [comment]
This PR will be closed. Due to the submission of @c-po, there will be conflicts in the merging of this pr. agree with the modification of @c-po and delete the function of sending commands. If there is an appropriate location, the PR will be re submitted at the right time. The task list has been closed, and NDP protocol monitoring features are supported.

**Pull request closed without merging**
