### PR TITLE
T5747: op-mode add show interfaces summary

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add op-mode `show interfaces summary`
Add `MAC`, `VRF` and `MTU` options:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5747

## Component(s) name

interfaces
## How to test
```
vyos@r4# run show interfaces summary 
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address         MAC                VRF        MTU  S/L    Description
-----------  -----------------  -----------------  -------  -----  -----  -------------
dum0         203.0.113.1/32     96:44:ad:c5:a1:a5  default   1500  u/u
eth0         192.168.122.14/24  52:54:00:f1:fd:77  default   1500  u/u    WAN
eth1         192.0.2.1/24       52:54:00:04:33:2b  foo       1500  u/u    LAN-eth1
eth2         -                  52:54:00:40:2e:af  default   1504  u/u    LAN-eth2
eth3         -                  52:54:00:09:a4:b4  default   1500  A/D
eth4         -                  52:54:00:2c:51:09  default   1500  A/D
eth5         -                  52:54:00:f3:1d:e8  default   1500  A/D
lo           127.0.0.1/8        00:00:00:00:00:00  default  65536  u/u
             ::1/128
vtun10       10.10.0.1/24       n/a                default   1500  u/u

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by jestabro — APPROVED** [review]

**Comment by c-po** [comment]
Is it a good idea to have the number of output columns depending on the data it displays? So if IPv6 EUI64 addresses are in use, we do not see MACs.

Another idea would be a new `show interfaces summary` command that displays MAC, MTU and VRF information and keep the old `show interfaces` as is?

**Comment by sever-sever** [comment]
> Is it a good idea to have the number of output columns depending on the data it displays? So if IPv6 EUI64 addresses are in use, we do not see MACs.
> 
> Another idea would be a new `show interfaces summary` command that displays MAC, MTU and VRF information and keep the old `show interfaces` as is?

So replace MAC with VRF? :)

**Comment by sever-sever** [comment]
@c-po The idea shows part of the information was don't break output if you connected via Serial console
Or small terminal width

**Comment by c-po** [comment]
> > Is it a good idea to have the number of output columns depending on the data it displays? So if IPv6 EUI64 addresses are in use, we do not see MACs.
> > Another idea would be a new `show interfaces summary` command that displays MAC, MTU and VRF information and keep the old `show interfaces` as is?
> 
> So replace MAC with VRF? :)

Nope, in addition to MAC and MTU, also add VRF

**Comment by c-po** [comment]
> @c-po The idea shows part of the information was don't break output if you connected via Serial console Or small terminal width

Serial consoles will line/break, paginate, depending on `set terminal width` and `set terminal length` - nevertheless with this also in mind it might be an additional reason to use a new subnode under `show interface`

**Comment by sever-sever** [comment]
Added `show interfaces summary`
```
vyos@r4# run show interfaces summary 
Codes: S - State, L - Link, u - Up, D - Down, A - Admin Down
Interface    IP Address         MAC                VRF        MTU  S/L    Description
-----------  -----------------  -----------------  -------  -----  -----  -------------
dum0         203.0.113.1/32     96:44:ad:c5:a1:a5  default   1500  u/u
eth0         192.168.122.14/24  52:54:00:f1:fd:77  default   1500  u/u    WAN
eth1         192.0.2.1/24       52:54:00:04:33:2b  foo       1500  u/u    LAN-eth1
eth2         -                  52:54:00:40:2e:af  default   1504  u/u    LAN-eth2
eth3         -                  52:54:00:09:a4:b4  default   1500  A/D
eth4         -                  52:54:00:2c:51:09  default   1500  A/D
eth5         -                  52:54:00:f3:1d:e8  default   1500  A/D
lo           127.0.0.1/8        00:00:00:00:00:00  default  65536  u/u
             ::1/128
vtun10       10.10.0.1/24       n/a                default   1500  u/u
[edit]
vyos@r4# 

```

**Review by c-po — APPROVED** [review]

**Comment by c-po** [comment]
@MergifyIo backport sagitta

**Pull request merged**
