### PR TITLE
op-mode: T2841: Fix monitor bandwidth-test initiate ipv6

### PR DESCRIPTION
**Pull request by sever-sever**

### CODE REVIEW

**Comment by c-po** [comment]
I this backwards compatible with the old implementation? Lets assume testing 1.2.5 and 1.3.x?

**Comment by sever-sever** [comment]
> I this backwards compatible with the old implementation? Lets assume testing 1.2.5 and 1.3.x?

No, without "cherry-pick",  it uses different ports and client-server apps. I mean you can't start client  iperf3 and use server iperf2 and vise versa.
let me think.

**Comment by sever-sever** [comment]
@c-po how about that option "initiate6" ? commit updated

**Comment by c-po** [comment]
Why not build a small bash wrapper which checks for FQDN, IPv4 or IPv6 address and alters the command options? That would be the most compatible way.

**Comment by sever-sever** [comment]
I don't know how to check fqdn name.
It can contain both ipv4 + ipv6 addresses

**Comment by c-po** [comment]
Superseeded by https://github.com/vyos/vyos-1x/commit/8ae88b5ba5cbc34b9992ccdde4229d44cfe56225

**Pull request closed without merging**
