### PR TITLE
T5775: firewall: re-add state-policy to firewall. These commands are …

### PR DESCRIPTION
**Pull request by nicolas-fort**
…now included in <set firewall global-options state-policy> node.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [x] Other (please describe):
Re add state-policy to firewall

## Related Task(s)

* https://vyos.dev/T5775

## Component(s) name

firewall

## How to test

Config:
```
vyos@ZONE-STATE:~$ show config comm | grep fire
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy established log
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy related action 'accept'
set firewall ipv4 forward filter rule 101 action 'drop'
set firewall ipv4 forward filter rule 101 protocol 'gre'
set firewall ipv4 input filter rule 22 action 'reject'
set firewall ipv4 input filter rule 22 source address '1.2.3.4'
set firewall ipv4 name LAN_to_LOCAL rule 10 action 'accept'
set firewall ipv4 name LAN_to_WAN default-action 'accept'
set firewall ipv4 name LOCAL_to_WAN default-action 'accept'
set firewall ipv4 name WAN_to_LAN default-action 'drop'
set firewall ipv4 name WAN_to_LOCAL default-action 'drop'
set firewall ipv4 name WAN_to_LOCAL rule 10 action 'accept'
set firewall ipv4 name WAN_to_LOCAL rule 10 source address '192.168.0.0/16'
set firewall zone LAN from WAN firewall name 'WAN_to_LAN'
set firewall zone LAN interface 'eth1'
set firewall zone LOCAL from LAN firewall name 'LAN_to_LOCAL'
set firewall zone LOCAL from WAN firewall name 'WAN_to_LOCAL'
set firewall zone LOCAL local-zone
set firewall zone WAN from LAN firewall name 'LAN_to_WAN'
set firewall zone WAN from LOCAL firewall name 'LOCAL_to_WAN'
set firewall zone WAN interface 'eth0'
vyos@ZONE-STATE:~$ 
```
Generate ipv4 ruleset:
```
vyos@ZONE-STATE:~$ sudo nft -s list table ip vyos_filter
table ip vyos_filter {
        chain VYOS_FORWARD_filter {
                type filter hook forward priority filter; policy accept;
                jump VYOS_STATE_POLICY
                meta l4proto gre counter drop comment "ipv4-FWD-filter-101"
                counter accept comment "FWD-filter default-action accept"
        }

        chain VYOS_INPUT_filter {
                type filter hook input priority filter; policy accept;
                jump VYOS_STATE_POLICY
                ip saddr 1.2.3.4 counter reject comment "ipv4-INP-filter-22"
                counter accept comment "INP-filter default-action accept"
        }

        chain VYOS_OUTPUT_filter {
                type filter hook output priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter accept comment "OUT-filter default-action accept"
        }

        chain VYOS_FRAG_MARK {
                type filter hook prerouting priority -450; policy accept;
                ip frag-off & 16383 != 0 meta mark set 0x000ffff1 return
        }

        chain NAME_LAN_to_LOCAL {
                counter accept comment "ipv4-NAM-LAN_to_LOCAL-10"
                counter drop comment "LAN_to_LOCAL default-action drop"
        }

        chain NAME_LAN_to_WAN {
                counter accept comment "LAN_to_WAN default-action accept"
        }

        chain NAME_LOCAL_to_WAN {
                counter accept comment "LOCAL_to_WAN default-action accept"
        }

        chain NAME_WAN_to_LAN {
                counter drop comment "WAN_to_LAN default-action drop"
        }

        chain NAME_WAN_to_LOCAL {
                ip saddr 192.168.0.0/16 counter accept comment "ipv4-NAM-WAN_to_LOCAL-10"
                counter drop comment "WAN_to_LOCAL default-action drop"
        }

        chain VYOS_ZONE_FORWARD {
                type filter hook forward priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY
                oifname "eth1" counter jump VZONE_LAN
                oifname "eth0" counter jump VZONE_WAN
        }

        chain VYOS_ZONE_LOCAL {
                type filter hook input priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY
                counter jump VZONE_LOCAL_IN
        }

        chain VYOS_ZONE_OUTPUT {
                type filter hook output priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY
                counter jump VZONE_LOCAL_OUT
        }

        chain VZONE_LAN {
                iifname "eth1" counter return
                iifname "eth0" counter jump NAME_WAN_to_LAN
                iifname "eth0" counter return
                counter drop comment "zone_LAN default-action drop"
        }

        chain VZONE_LOCAL_IN {
                iifname "lo" counter return
                iifname "eth1" counter jump NAME_LAN_to_LOCAL
                iifname "eth1" counter return
                iifname "eth0" counter jump NAME_WAN_to_LOCAL
                iifname "eth0" counter return
                counter drop comment "zone_LOCAL default-action drop"
        }

        chain VZONE_LOCAL_OUT {
                oifname "lo" counter return
                oifname "eth0" counter jump NAME_LOCAL_to_WAN
                oifname "eth0" counter return
                counter drop comment "zone_LOCAL default-action drop"
        }

        chain VZONE_WAN {
                iifname "eth0" counter return
                iifname "eth1" counter jump NAME_LAN_to_WAN
                iifname "eth1" counter return
                counter drop comment "zone_WAN default-action drop"
        }

        chain VYOS_STATE_POLICY {
                ct state established log prefix "[STATE-POLICY-EST-A]" counter accept
                ct state invalid counter drop
                ct state related counter accept
                return
        }
}
vyos@ZONE-STATE:~$
```

## Smoketest result

```
root@ZONE-STATE:/usr/libexec/vyos/tests/smoke/cli# ./test_firewall.py 
test_bridge_basic_rules (__main__.TestFirewall.test_bridge_basic_rules) ... ok
test_flow_offload (__main__.TestFirewall.test_flow_offload) ... 
Interface "eth0" does not support hardware offload

ok
test_geoip (__main__.TestFirewall.test_geoip) ... Updating GeoIP. Please wait...
Updating GeoIP. Please wait...
ok
test_groups (__main__.TestFirewall.test_groups) ... ok
test_ipv4_advanced (__main__.TestFirewall.test_ipv4_advanced) ... ok
test_ipv4_basic_rules (__main__.TestFirewall.test_ipv4_basic_rules) ... ok
test_ipv4_mask (__main__.TestFirewall.test_ipv4_mask) ... ok
test_ipv4_state_and_status_rules (__main__.TestFirewall.test_ipv4_state_and_status_rules) ... ok
test_ipv4_synproxy (__main__.TestFirewall.test_ipv4_synproxy) ... 
"synproxy" option allowed only for action synproxy

ok
test_ipv6_advanced (__main__.TestFirewall.test_ipv6_advanced) ... ok
test_ipv6_basic_rules (__main__.TestFirewall.test_ipv6_basic_rules) ... ok
test_ipv6_mask (__main__.TestFirewall.test_ipv6_mask) ... ok
test_nested_groups (__main__.TestFirewall.test_nested_groups) ... 
Group "smoketest_network1" has a circular reference

ok
test_source_validation (__main__.TestFirewall.test_source_validation) ... ok
test_sysfs (__main__.TestFirewall.test_sysfs) ... ok
test_zone_basic (__main__.TestFirewall.test_zone_basic) ... ok

----------------------------------------------------------------------
Ran 16 tests in 37.858s

OK
root@ZONE-STATE:/usr/libexec/vyos/tests/smoke/cli# 

```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by sarthurdev** [comment]
Assume [migrator](https://github.com/vyos/vyos-1x/blob/current/src/migration-scripts/firewall/10-to-11#L65) can also be updated to instead move old node to the new `global-options` root?

**Comment by nicolas-fort** [comment]
> Assume [migrator](https://github.com/vyos/vyos-1x/blob/current/src/migration-scripts/firewall/10-to-11#L65) can also be updated to instead move old node to the new `global-options` root?

That's correct. Migration scripts updated

**Comment by nicolas-fort** [comment]
Custom iso was built and migration was tested.
Config on 1.3.4:
```
vyos@State-Readd:~$ show config comm | grep "state\|fire"
set firewall all-ping 'enable'
set firewall broadcast-ping 'disable'
set firewall config-trap 'disable'
set firewall ipv6-receive-redirects 'disable'
set firewall ipv6-src-route 'disable'
set firewall ip-src-route 'disable'
set firewall log-martians 'enable'
set firewall name LAN_to_LOCAL default-action 'accept'
set firewall name LAN_to_WAN default-action 'accept'
set firewall name LAN_to_WAN enable-default-log
set firewall name LOCAL_to_LAN default-action 'accept'
set firewall name LOCAL_to_WAN default-action 'accept'
set firewall name WAN_to_LAN default-action 'drop'
set firewall name WAN_to_LOCAL default-action 'drop'
set firewall name WAN_to_LOCAL rule 10 action 'accept'
set firewall name WAN_to_LOCAL rule 10 log 'enable'
set firewall name WAN_to_LOCAL rule 10 protocol 'tcp'
set firewall name WAN_to_LOCAL rule 10 source address '192.168.0.0/16'
set firewall name WAN_to_LOCAL rule 20 action 'accept'
set firewall name WAN_to_LOCAL rule 20 state new 'enable'
set firewall name WAN_to_LOCAL rule 20 state related 'enable'
set firewall receive-redirects 'disable'
set firewall send-redirects 'enable'
set firewall source-validation 'disable'
set firewall state-policy established action 'accept'
set firewall state-policy invalid action 'drop'
set firewall state-policy invalid log enable
set firewall state-policy related action 'accept'
set firewall syn-cookies 'enable'
set firewall twa-hazards-protection 'disable'
set zone-policy zone LAN from LOCAL firewall name 'LOCAL_to_LAN'
set zone-policy zone LAN from WAN firewall name 'WAN_to_LAN'
set zone-policy zone LOCAL from LAN firewall name 'LAN_to_LOCAL'
set zone-policy zone LOCAL from WAN firewall name 'WAN_to_LOCAL'
set zone-policy zone WAN from LAN firewall name 'LAN_to_WAN'
set zone-policy zone WAN from LOCAL firewall name 'LOCAL_to_WAN'
vyos@State-Readd:~$ 

```

Config present in 1.5 after updating from 1.3.4:

```
vyos@State-Readd:~$ show config comm | grep "fire\|state"
set firewall global-options all-ping 'enable'
set firewall global-options broadcast-ping 'disable'
set firewall global-options ip-src-route 'disable'
set firewall global-options ipv6-receive-redirects 'disable'
set firewall global-options ipv6-src-route 'disable'
set firewall global-options log-martians 'enable'
set firewall global-options receive-redirects 'disable'
set firewall global-options send-redirects 'enable'
set firewall global-options source-validation 'disable'
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy invalid log
set firewall global-options state-policy related action 'accept'
set firewall global-options syn-cookies 'enable'
set firewall global-options twa-hazards-protection 'disable'
set firewall ipv4 name LAN_to_LOCAL default-action 'accept'
set firewall ipv4 name LAN_to_WAN default-action 'accept'
set firewall ipv4 name LAN_to_WAN enable-default-log
set firewall ipv4 name LOCAL_to_LAN default-action 'accept'
set firewall ipv4 name LOCAL_to_WAN default-action 'accept'
set firewall ipv4 name WAN_to_LAN default-action 'drop'
set firewall ipv4 name WAN_to_LOCAL default-action 'drop'
set firewall ipv4 name WAN_to_LOCAL rule 10 action 'accept'
set firewall ipv4 name WAN_to_LOCAL rule 10 log
set firewall ipv4 name WAN_to_LOCAL rule 10 protocol 'tcp'
set firewall ipv4 name WAN_to_LOCAL rule 10 source address '192.168.0.0/16'
set firewall ipv4 name WAN_to_LOCAL rule 20 action 'accept'
set firewall ipv4 name WAN_to_LOCAL rule 20 state 'new'
set firewall ipv4 name WAN_to_LOCAL rule 20 state 'related'
set firewall zone LAN default-action 'drop'
set firewall zone LAN from LOCAL firewall name 'LOCAL_to_LAN'
set firewall zone LAN from WAN firewall name 'WAN_to_LAN'
set firewall zone LAN interface 'eth1'
set firewall zone LAN interface 'eth2'
set firewall zone LAN interface 'eth3'
set firewall zone LOCAL default-action 'drop'
set firewall zone LOCAL from LAN firewall name 'LAN_to_LOCAL'
set firewall zone LOCAL from WAN firewall name 'WAN_to_LOCAL'
set firewall zone LOCAL local-zone
set firewall zone WAN default-action 'drop'
set firewall zone WAN from LAN firewall name 'LAN_to_WAN'
set firewall zone WAN from LOCAL firewall name 'LOCAL_to_WAN'
set firewall zone WAN interface 'eth0'
vyos@State-Readd:~$ 
```

And relevant (not all) nft chains in 1.5:
```
table ip vyos_filter {
        chain VYOS_FORWARD_filter {
                type filter hook forward priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter packets 0 bytes 0 accept comment "FWD-filter default-action accept"
        }

        chain VYOS_INPUT_filter {
                type filter hook input priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter packets 53 bytes 10259 accept comment "INP-filter default-action accept"
        }

        chain VYOS_OUTPUT_filter {
                type filter hook output priority filter; policy accept;
                jump VYOS_STATE_POLICY
                counter packets 24 bytes 1668 accept comment "OUT-filter default-action accept"
        }
        chain VYOS_ZONE_FORWARD {
                type filter hook forward priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY
                oifname { "eth1", "eth2", "eth3" } counter packets 0 bytes 0 jump VZONE_LAN
                oifname "eth0" counter packets 0 bytes 0 jump VZONE_WAN
        }

        chain VYOS_ZONE_LOCAL {
                type filter hook input priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY
                counter packets 53 bytes 10259 jump VZONE_LOCAL_IN
        }

        chain VYOS_ZONE_OUTPUT {
                type filter hook output priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY
                counter packets 24 bytes 1668 jump VZONE_LOCAL_OUT
        }
        chain VYOS_STATE_POLICY {
                ct state established counter packets 36 bytes 2808 accept
                ct state invalid log prefix "[STATE-POLICY-INV-D]" counter packets 0 bytes 0 drop
                ct state related counter packets 12 bytes 1008 accept
                return
        }
}
table ip6 vyos_filter {
        chain VYOS_IPV6_FORWARD_filter {
                type filter hook forward priority filter; policy accept;
                jump VYOS_STATE_POLICY6
                counter packets 0 bytes 0 accept comment "FWD-filter default-action accept"
        }

        chain VYOS_IPV6_INPUT_filter {
                type filter hook input priority filter; policy accept;
                jump VYOS_STATE_POLICY6
                counter packets 7 bytes 656 accept comment "INP-filter default-action accept"
        }

        chain VYOS_IPV6_OUTPUT_filter {
                type filter hook output priority filter; policy accept;
                jump VYOS_STATE_POLICY6
                counter packets 34 bytes 3512 accept comment "OUT-filter default-action accept"
        }

        chain VYOS_ZONE_FORWARD {
                type filter hook forward priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY6
                oifname { "eth1", "eth2", "eth3" } counter packets 0 bytes 0 jump VZONE_LAN
                oifname "eth0" counter packets 0 bytes 0 jump VZONE_WAN
        }

        chain VYOS_ZONE_LOCAL {
                type filter hook input priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY6
                counter packets 7 bytes 656 jump VZONE_LOCAL_IN
        }

        chain VYOS_ZONE_OUTPUT {
                type filter hook output priority filter + 1; policy accept;
                jump VYOS_STATE_POLICY6
                counter packets 34 bytes 3512 jump VZONE_LOCAL_OUT
        }
        chain VYOS_STATE_POLICY6 {
                ct state established counter packets 0 bytes 0 accept
                ct state invalid log prefix "[STATE-POLICY-INV-D]" counter packets 0 bytes 0 drop
                ct state related counter packets 0 bytes 0 accept
                return
        }
}

**Comment by GurliGebis** [comment]
@nicolas-fort do you need some extra testing of this, before it can be merged into 1.4 and 1.5?
It would really simplify a lot of configuration, so having it in before 1.4 is released would be great :)

**Comment by c-po** [comment]
@nicolas-fort while working on this could you please consider the following optimisations to the CLI for inclusion in this PR:

Make the following list of CLI nodes valueless

```
set firewall global-options all-ping 'enable'
set firewall global-options broadcast-ping 'disable'
set firewall global-options ip-src-route 'disable'
set firewall global-options ipv6-receive-redirects 'disable'
set firewall global-options ipv6-src-route 'disable'
set firewall global-options log-martians 'enable'
set firewall global-options receive-redirects 'disable'
set firewall global-options send-redirects 'enable'
set firewall global-options source-validation 'disable'
set firewall global-options state-policy established action 'accept'
set firewall global-options state-policy invalid action 'drop'
set firewall global-options state-policy invalid log
set firewall global-options state-policy related action 'accept'
set firewall global-options syn-cookies 'enable'
set firewall global-options twa-hazards-protection 'disable'
```

**Review by sarthurdev — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Review by dmbaturin — APPROVED** [review]

**Comment by GurliGebis** [comment]
Backport? 🙂

**Pull request merged**
