### PR TITLE
op-mode: T3536: Fix for show ip route longer-prefixes

### PR DESCRIPTION
**Pull request by sever-sever**
## Change Summary

Add checks for pattern "/" in routes for longer-prefixes. Op-mode.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://phabricator.vyos.net/T3536

## Component(s) name

static route
## How to test
Expect no errors for values without prefix
```
vyos@r6-roll:~$ show ip route 192.168.122.0 longer-prefixes 
vyos@r6-roll:~$ 
```
Expect longer-prefixes with "/x"
```
vyos@r6-roll:~$ show ip route 192.168.122.0/8 longer-prefixes 
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, E - EIGRP, N - NHRP,
       T - Table, v - VNC, V - VNC-Direct, A - Babel, D - SHARP,
       F - PBR, f - OpenFabric,
       > - selected route, * - FIB route, q - queued, r - rejected, b - backup

S>* 192.168.0.0/16 [1/0] unreachable (blackhole), weight 1, 00:47:07
C>* 192.168.122.0/24 is directly connected, eth0, 01:08:26
vyos@r6-roll:~$ 
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
I wonder why we need to preprocess this and can simply pass this down into FRR?

**Comment by sever-sever** [comment]
> I wonder why we need to preprocess this and can simply pass this down into FRR?

Frr itself doesn't allow to set longer-prefixes without "prefix"

```
r4-1.3# show ip route 1.1.1.1 
  <cr>           
  json           JavaScript Object Notation
  nexthop-group  Nexthop Group Information


r4-1.3# show ip route 1.1.1.1/24 
  <cr>             
  json             JavaScript Object Notation
  longer-prefixes  Show route matching the specified Network/Mask pair only
  nexthop-group    Nexthop Group Information
```
Without check we get “unknown command”

      
```
r6:~$ show ip route 1.1.1.1 longer-prefixes 
% Unknown command: show ip route 1.1.1.1 longer-prefixes
```

**Comment by c-po** [comment]
Well, this PR would mask what is indeed a real error.

So I would rather not touch this behavior. But while working at it it would probably make sense to replace the command by `<command>${vyos_op_scripts_dir}/vtysh_wrapper.sh $@</command>`

**Comment by sever-sever** [comment]
> So I would rather not touch this behavior.

We allow it in the command description and at the same time we get "command not found"
```
vyos@r6-roll:~$ show ip route 1.1.1.1 
Possible completions:
  <Enter>       Execute the current command
  longer-prefixes
                Show longer prefixes of routes for specified IP address or prefix
```
Ok, I replace the command with "wrapper". 
```
-                <command>if [[ $4 =~ .*\/[0-9] ]]; then vtysh -c "show ip route $4 longer-prefixes"; fi</command>
+                <command>${vyos_op_scripts_dir}/vtysh_wrapper.sh $@</command>

```

**Comment by c-po** [comment]
Thanks

**Pull request merged**
