### PR TITLE
ddclient: T5708: Additional smoketests for web-options

### PR DESCRIPTION
**Pull request by indrajitr**
## Change Summary

Additional smoketests for web-options validating failure scenarios.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5708

## Related PR(s)

vyos/vyos-1x#2467

## Component(s) name

dns dynamic

## Smoketest result

```
vyos@vyos15a3:~$ python3 /usr/libexec/vyos/tests/smoke/cli/test_service_dns_dynamic.py TestServiceDDNS.test_06_dyndns_web_options
test_06_dyndns_web_options (__main__.TestServiceDDNS.test_06_dyndns_web_options) ... 
"web-options" is applicable only when using HTTP(S) web request to
obtain the IP address

ok

----------------------------------------------------------------------
Ran 1 test in 306.209s

OK
```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by c-po — APPROVED** [review]

**Comment by sever-sever** [comment]
Test please the whole `/usr/libexec/vyos/tests/smoke/cli/test_service_dns_dynamic.py` next time
it fails.
```
 DEBUG - ----------------------------------------------------------------------
DEBUG - Ran 3 tests in 7.616s
DEBUG - 
DEBUG - OK
DEBUG - Running Testcase: /usr/libexec/vyos/tests/smoke/cli/test_service_dns_dynamic.py
DEBUG - test_01_dyndns_service_standard (__main__.TestServiceDDNS.test_01_dyndns_service_standard) ... ok
DEBUG - test_02_dyndns_service_ipv6 (__main__.TestServiceDDNS.test_02_dyndns_service_ipv6) ... ok
DEBUG - test_03_dyndns_service_dual_stack (__main__.TestServiceDDNS.test_03_dyndns_service_dual_stack) ... ok
DEBUG - test_04_dyndns_rfc2136 (__main__.TestServiceDDNS.test_04_dyndns_rfc2136) ... ok
DEBUG - test_05_dyndns_hostname (__main__.TestServiceDDNS.test_05_dyndns_hostname) ... ok
DEBUG - test_06_dyndns_web_options (__main__.TestServiceDDNS.test_06_dyndns_web_options) ... ok
DEBUG - test_07_dyndns_vrf (__main__.TestServiceDDNS.test_07_dyndns_vrf) ... ERROR
DEBUG - test_07_dyndns_vrf (__main__.TestServiceDDNS.test_07_dyndns_vrf) ... FAIL
DEBUG - 
DEBUG - ======================================================================
DEBUG - ERROR: test_07_dyndns_vrf (__main__.TestServiceDDNS.test_07_dyndns_vrf)
DEBUG - ----------------------------------------------------------------------
DEBUG - Traceback (most recent call last):
DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_service_dns_dynamic.py", line 304, in test_07_dyndns_vrf
DEBUG -     self.cli_set(['vrf', 'name', vrf_name, 'table', vrf_table])
DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/base_vyostest_shim.py", line 68, in cli_set
DEBUG -     self._session.set(config)
DEBUG -   File "/usr/lib/python3/dist-packages/vyos/configsession.py", line 150, in set
DEBUG -     self.__run_command([SET] + path + value)
DEBUG -   File "/usr/lib/python3/dist-packages/vyos/configsession.py", line 139, in __run_command
DEBUG -     raise ConfigSessionError(output)
DEBUG - vyos.configsession.ConfigSessionError: Number is not in any of allowed ranges
DEBUG - 
DEBUG - 
DEBUG - 
DEBUG - VRF routing table must be in range from 100 to 65535
DEBUG - Value validation failed
DEBUG - Set failed
DEBUG - 
DEBUG - 
DEBUG - ======================================================================
DEBUG - FAIL: test_07_dyndns_vrf (__main__.TestServiceDDNS.test_07_dyndns_vrf)
DEBUG - ----------------------------------------------------------------------
DEBUG - Traceback (most recent call last):
DEBUG -   File "/usr/libexec/vyos/tests/smoke/cli/test_service_dns_dynamic.py", line 50, in tearDown
DEBUG -     self.assertTrue(process_running(DDCLIENT_PID))
DEBUG - AssertionError: False is not true
DEBUG - 
DEBUG - ----------------------------------------------------------------------
```

**Comment by indrajitr** [comment]
All tests passed for me. But I see what the issue is - the randomly generated table number was greater than 65535 in your case. Fix coming up.

**Comment by sever-sever** [comment]
> All tests passed for me. But I see what the issue is - the randomly generated table number was greater than 65535 in your case. Fix coming up.

Thanks :) It was by auto build. system and not pass the smoketest

**Comment by indrajitr** [comment]
Right, this would have surfaced anytime (wish it did locally in my test). Sorry about this.
Fix here: vyos/vyos-1x#2470

**Pull request merged**
