### PR TITLE
interfaces: T5254: Disable interface changes in bond members

### PR DESCRIPTION
**Pull request by aapostoliuk**
## Change Summary

If an interface is a bond member, disable to change interface options 
which should be changed under the bond interface section.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5254

## Component(s) name

interfaces

## Proposed changes

If interface is  bond member, disable to change interface options 
which should be changed under bond interface section.

Suggested allowed options for changes :
'description',
'disable',
'disable_flow_control',
'disable_link_detect',
'duplex',
'eapol',
'mirror',
'offload',
'redirect',
'ring-buffer',
'speed',
'hw_id'

All others will be disabled for changes in the interface ethernet section if that interface is a bond member.

For example:
You can not add interface 'eth0' to bond interface 'bond0', if 'mtu' is configured in the interface 'eth0' section.
You can not change 'mtu' in the interface 'eth0' section if interface 'eth0' is a bond member.

## How to test

Configuration:
```
set interfaces bonding bond0 member interface 'eth1'

vyos@vyos# set interfaces ethernet eth1 mtu 9000
[edit]
vyos@vyos# commit

Cannot configure mtu on interface eth1. Interface is a bond member

[[interfaces ethernet eth1]] failed
Commit failed
[edit]
vyos@vyos#

```
## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [x] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Comment by c-po** [comment]
Is there a specific reason to not allow these changes? Taking your MTU example, it's valid in Linux to change the underlaying interfaces MTU - if it makes sense is a different topic. What happens on the OS did you check if Linux simply ignores the interface MTU and uses the bond interfaces mtu as "real deal"?

This is also always a topic of confusion with e.g. Switching gear where you have  PortChannel that carries VLANs and the underlaying interfaces sometimes inherit the PortChannel VLAN configuration inside the CLI

**Comment by aapostoliuk** [comment]
> Is there a specific reason to not allow these changes? Taking your MTU example, it's valid in Linux to change the underlaying interfaces MTU - if it makes sense is a different topic. What happens on the OS did you check if Linux simply ignores the interface MTU and uses the bond interfaces mtu as "real deal"?
> 
> This is also always a topic of confusion with e.g. Switching gear where you have PortChannel that carries VLANs and the underlaying interfaces sometimes inherit the PortChannel VLAN configuration inside the CLI

According to the Task, there is a problem when the user changes description on ethernet interface, MTU changes too to default value 1500.

Configuration:
```
set interfaces bonding bond0 address '192.168.1.1/24'
set interfaces bonding bond0 member interface 'eth1'
set interfaces bonding bond0 member interface 'eth2'
set interfaces bonding bond0 mode '802.3ad'
set interfaces bonding bond0 mtu '9000'

```
Before:
```
vyos@vyos:~$ ip link
4: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 0c:ed:5b:62:00:01 brd ff:ff:ff:ff:ff:ff
    alias test
5: eth2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 0c:ed:5b:62:00:01 brd ff:ff:ff:ff:ff:ff permaddr 0c:ed:5b:62:00:02
    alias test3
6: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0c:ed:5b:62:00:01 brd ff:ff:ff:ff:ff:ff

vyos@vyos:~$ ping 192.168.1.2 size 2000 do-not-fragment
PING 192.168.1.2 (192.168.1.2) 2000(2028) bytes of data.
2008 bytes from 192.168.1.2: icmp_seq=2 ttl=255 time=1.61 ms
2008 bytes from 192.168.1.2: icmp_seq=3 ttl=255 time=1.70 ms
2008 bytes from 192.168.1.2: icmp_seq=4 ttl=255 time=2.06 ms
2008 bytes from 192.168.1.2: icmp_seq=5 ttl=255 time=2.45 ms
```

Then:
```
vyos@vyos# set interfaces ethernet eth1 description test1
[edit]
vyos@vyos# set interfaces ethernet eth2 description test2
[edit]
vyos@vyos# commit
[  837.397024] bond0: (slave eth1): speed changed to 0 on port 1
[  837.687424] bond0: (slave eth2): speed changed to 0 on port 2
```


After configuring:
```
vyos@vyos:~$ ip link
4: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 0c:ed:5b:62:00:01 brd ff:ff:ff:ff:ff:ff
    alias test1
5: eth2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 0c:ed:5b:62:00:01 brd ff:ff:ff:ff:ff:ff permaddr 0c:ed:5b:62:00:02
    alias test2
6: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 0c:ed:5b:62:00:01 brd ff:ff:ff:ff:ff:ff

vyos@vyos:~$ ping 192.168.1.2 size 2000 do-not-fragment
PING 192.168.1.2 (192.168.1.2) 2000(2028) bytes of data.
^C
--- 192.168.1.2 ping statistics ---
15 packets transmitted, 0 received, 100% packet loss, time 14363ms
```
Changing MTU on the ethernet interface changes it in real. And MTU on bond interface seems not working.

**Comment by c-po** [comment]
Okay, understood. Why not take a simple approach using `verify()` to check that underlaying interface and bond interface MTU matches? Would reduce the amount of code to maintain.

**Comment by aapostoliuk** [comment]
> Okay, understood. Why not take a simple approach using `verify()` to check that underlaying interface and bond interface MTU matches? Would reduce the amount of code to maintain.

Because if you change MTU under bond interface, the old MTU will be left under ethernet configuration. And it can be confusing.
I see only two approaches.
1. Clear ethernet configuration options which should be changed under bond interface.
2. Left these options under ethernet configuration, but ignore them.

The second option, in my opinion, is not so obvious to view.

**Comment by c-po** [comment]
> Because if you change MTU under bond interface, the old MTU will be left under ethernet configuration. And it can be confusing. I see only two approaches.

That's exactly what my idea addresses. You wan't to change the MTU on a bond? You need to do:

```
# Create bond
set interfaces bond member interface eth0
set interfaces bond member interface eth1

# Change MTU
set interfaces ethernet eth0 mtu 9000
set interfaces ethernet eth1 mtu 9000
set interfaces bond bond0 mtu 9000
```

If MTU of the underlaying interface does not match the bond MTU - verify() will raise a config error. This is the most cleanest solution in my opinion as CLI reflects the "real deal" and not shows values that are masked/ignored under the hood"

Another, additional idea would be (we use this already for SNMP) that if bond MTU is changed, it will change the underlaying eth MTU via CLI automatically, so the user needs to chabge the MTU in one place only - still the verify from above must be implemented as safety measure.

**Pull request closed without merging**
