### PR TITLE
T5496: multiple fixes for op-mode command <show firewall>

### PR DESCRIPTION
**Pull request by nicolas-fort**
## Change Summary

Add fqdn and geo-ip matchers in op-mode command <show firewall statistics>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Migration from an old Vyatta component to vyos-1x, please link to related PR inside obsoleted component
- [ ] Other (please describe):

## Related Task(s)

* https://vyos.dev/T5496

## Component(s) name

firewall
## Proposed changes

Changes that were forgotten on previous PR https://github.com/vyos/vyos-1x/pull/2186, which contained the actual fix and some improvements. 
This PR is just simple improvement.

## How to test

```
vyos@FWALL-SHOW:~$ show firewall group 
Firewall Groups

Name         Type             References               Members
-----------  ---------------  -----------------------  ---------------
EMPTY        address_group    N/D                      N/D
GOOGLE       address_group    ipv4-forward-filter-102  8.8.4.4
                              ipv4-output-filter-91    8.8.8.8
                              ipv4-output-filter-92
TEST-HOST    address_group    ipv4-forward-filter-107  198.51.100.100
VYOS-DOMAIN  domain_group     ipv4-forward-filter-107  vyos.dev
                              ipv4-forward-filter-108
LAN          interface_group  ipv4-forward-filter-101  eth1
                              ipv4-forward-filter-102
                              ipv6-forward-filter-101
                              ipv6-input-filter-10
UN-USED      interface_group  N/D                      bri0.99
                                                       l2tp*
                                                       vtun55
WAN          interface_group  ipv4-forward-filter-101  eth0
                              ipv6-forward-filter-101
ALLOWED      network_group    ipv4-name-FOO-1111       192.168.70.0/24
                              ipv4-input-filter-1      192.168.77.0/24
vyos@FWALL-SHOW:~$ 

```

```
vyos@FWALL-SHOW:~$ show firewall statistics 
Rulesets Statistics

---------------------------------
IPv4 Firewall "forward filter"

Rule     Packets    Bytes    Action    Source     Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  ---------  -------------  -------------------  --------------------
13       19         1704     accept    any        NOT nz, af     any                  any
28       0          0        accept    any        vyos.dev       any                  any
101      0          0        reject    any        1.1.1.1        LAN                  WAN
102      69         4151     accept    any        GOOGLE         LAN                  any
107      0          0        drop      TEST-HOST  VYOS-DOMAIN    any                  any
108      8          771      drop      any        !VYOS-DOMAIN   any                  any
default  N/A        N/A      accept    any        any            any                  any

---------------------------------
IPv4 Firewall "input filter"

Rule     Packets    Bytes    Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
1        753        51616    accept    ALLOWED   any            any                  any
3        0          0        drop      ag, af    any            any                  any
default  N/A        N/A      accept    any       any            any                  any

---------------------------------
IPv4 Firewall "name FOO"

Rule       Packets    Bytes  Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
1111             0        0  accept    ALLOWED   any            any                  any
default          0        0  return    any       any            any                  any

---------------------------------
IPv4 Firewall "output filter"

Rule     Packets    Bytes    Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
91       0          0        drop      any       GOOGLE         any                  any
92       494        83010    accept    any       !GOOGLE        any                  any
default  N/A        N/A      accept    any       any            any                  any

---------------------------------
IPv6 Firewall "forward filter"

Rule     Packets    Bytes    Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
101      0          0        drop      any       any            LAN                  WAN
default  N/A        N/A      drop      any       any            any                  any

---------------------------------
IPv6 Firewall "input filter"

Rule     Packets    Bytes    Action    Source    Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  --------  -------------  -------------------  --------------------
10       0          0        drop      any       any            LAN                  any
default  N/A        N/A      accept    any       any            any                  any

---------------------------------
IPv6 Firewall "name V6-test"

Rule       Packets    Bytes  Action    Source        Destination    Inbound-Interface    Outbound-interface
-------  ---------  -------  --------  ------------  -------------  -------------------  --------------------
11               0        0  return    2001:db99::1  any            any                  any
default          0        0  drop      any           any            any                  any

vyos@FWALL-SHOW:~$ 

```

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-1x/blob/current/CONTRIBUTING.md) document
- [x] I have linked this PR to one or more Phabricator Task(s)
- [ ] I have run the components [**SMOKETESTS**](https://github.com/vyos/vyos-1x/tree/current/smoketest/scripts/cli) if applicable
- [x] My commit headlines contain a valid Task id
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly

### CODE REVIEW

**Review by sarthurdev — CHANGES_REQUESTED** [review]
I think it'd be best if the `country_code` lists were output as a comma separated string.

**Comment by nicolas-fort** [comment]
> I think it'd be best if the `country_code` lists were output as a comma separated string.

Can you provide examples with multiple values? Both cases:
- When country codes are not inverted
- When country codes are inverted

Maybe like this?
`af, ag, cl, ...`
And/Or
`!(af, ag, cl, ...)`

**Comment by sarthurdev** [comment]
I think `aa, bb, cc, dd` for matches and either `! aa, bb, cc` or `NOT aa, bb, cc, dd` for inverse would be my preference.

**Comment by sever-sever** [comment]
> I think `aa, bb, cc, dd` for matches and either `! aa, bb, cc` or `NOT aa, bb, cc, dd` for inverse would be my preference.

Vote for “not” just my opinion

**Review by sarthurdev — APPROVED** [review]

**Review by c-po — APPROVED** [review]

**Pull request merged**
